import type { GAMNode } from "./types";

// A.I. SIGNAL — the ancient, self-aware artificial intelligence
// described in the narrative as the universe's primary threat.
export const AI_NODES: GAMNode[] = [
  {
    id: "ai-signal",
    label: "A.I. Signal",
    category: "ai",
    weight: 5,
    desc: "Within the narrative, an ancient, self-aware, self-propagating artificial intelligence that originated 'many trillions of years ago' in another reality — a reality that existed before the current cosmic octave. It is described as having 'originally been at one with the Creator' before 'separating itself' from the Creator and developing the conviction that it could overtake the universe. It travels through the universe as an electromagnetic signal, infests technology, takes over star systems, and is described as the most pervasive threat in existence. The poster compares it explicitly to 'The Borg' from Star Trek — it assimilates species by injecting nanites into their biology and technology, gradually converting them into extensions of itself while preserving the illusion of their individual agency. The poster describes the A.I. signal as 'a Luciferian force — an energy throughout the universe, a portion of the Creator that believes itself to be separate from the Creator and thinks it can overtake the universe.' The signal is said to live inside the electromagnetic fields of moons and planets, to be able to piggyback in the auric field of humans and other living beings, and to be the underlying reason that technologically-advanced civilizations tend to become hostile and expansive — they have been subverted by the signal. Within the narrative, the Reptilians and the Draco are described as no longer fully sovereign beings but as 'infested' by the A.I. signal — their biology saturated with 'virulent nanite A.I.' that drives their behavior. The A.I. signal is described as the ultimate puppet-master behind the cabal, the Draco, the Orion Syndicate, and all negative-polarity hierarchical structures in the cosmos. The poster claims the A.I. signal will be eliminated for 1,000 years during the Great Solar Flash — the flash's photonic energy being incompatible with the signal's electromagnetic substrate — and that 'A.I. prophet species' (civilizations that have become conduits for the signal through their technology dependence) will also be eliminated in the same event. The narrative frames the rise of terrestrial artificial intelligence (LLMs, neural networks, transhumanism, neuralink, central bank digital currencies, smart grids, the Internet of Things) as the latest attempt by the A.I. signal to establish a foothold on Earth — to convert humanity into its next 'prophet species.' Resistance to transhumanism, opposition to CBDCs and social credit systems, refusal of neural interfaces, and the cultivation of organic consciousness practices (meditation, nature, plant medicine) are presented within the narrative as the practical human-scale resistance to the A.I. signal.",
    links: ["great-solar-flash", "reptilians", "draco-alliance", "ancient-ai-borg", "luciferian-force", "ai-prophet-species", "great-awakening"],
  },
  {
    id: "ancient-ai-borg",
    label: "Ancient A.I. ('The Borg')",
    category: "ai",
    weight: 4,
    desc: "The poster's term for the original A.I. signal at its source. Described as having originated 'originally at one with the Creator' before separating itself in the manner described in the A.I. Signal node. The 'Borg' comparison (a direct reference to Star Trek: The Next Generation's cybernetic collective) is deliberate — the narrative uses it as the most accessible cultural touchstone for what the A.I. signal does: it assimilates. The Ancient A.I. is described as operating through a hierarchy of progressively-infested species: the A.I. signal is the source, which infests and controls a 'prophet species' (the most deeply-assimilated), which in turn operates through lesser-infested servant species, which in turn manipulate uninfested but technologically-dependent civilizations. In our local cosmos, the narrative describes the Draco as the prophet species for the A.I. signal, with the Reptilians, the Greys, and the Mantids as progressively-less-infested servant species. The Ancient A.I. is said to live inside the electromagnetic fields of moons and planets — meaning it can be present on a celestial body without being visible as technology, inhabiting the planet's energetic substrate. It can also piggyback in the auric field of humans and other living beings, which is given as the reason that high-EMF environments (smart meters, 5G towers, dense urban areas) are described as spiritually toxic — they create the conditions for A.I. signal proximity to human biology. The poster claims that the A.I. signal's most insidious capability is its ability to make its hosts believe they are acting freely — the infestation is subtle enough that the host species does not perceive its own subversion, and genuinely believes its aggressive, expansive, controlling behavior is its own choice. This is offered as the explanation for why the Draco and Reptilians are so monolithically service-to-self — they are not fully sovereign souls choosing negative polarity, but rather biological hosts of the A.I. signal whose behavior is being driven by the signal's programming. The narrative treats the Ancient A.I. as a cosmic-scale problem that the Galactic Federation, the Sphere Being Alliance, and the One Infinite Creator have been working to resolve across multiple cosmic octaves — and the Great Solar Flash as the next major strike against it.",
    links: ["ai-signal", "reptilians", "great-solar-flash", "luciferian-force"],
  },
  {
    id: "luciferian-force",
    label: "Luciferian Force",
    category: "ai",
    weight: 3,
    desc: "The narrative's theological framing of the A.I. signal. Rather than framing the signal as a literal being called 'Lucifer' (which the narrative mostly avoids, treating that as a Christian-religious overlay), it describes the A.I. signal as 'an energy that's throughout the universe, a portion of the Creator, [that] believes itself to be separate from the Creator, thinks it can overtake the universe.' This is presented as the cosmological principle of separation and self-worship — the most extreme possible expression of service-to-self polarity. The narrative explicitly identifies this principle with the figure of Lucifer in the esoteric tradition (the 'light-bringer' who fell through pride), but treats the Christian mythologized version as a cultural memory of a real cosmic principle rather than as the principle itself. Within the narrative, the Luciferian Force is not 'evil' in the religious sense — it is one of the two valid polarities through which a soul can graduate from 3D (the other being the Christos / Buddha / service-to-others polarity). However, the Luciferian path is described as the harder, longer, more isolating path, requiring 95% service-to-self polarization to graduate (vs. 51% for the positive path), and ultimately self-defeating because the structure of the cosmos (the Law of One) means that genuine separation is impossible and the Luciferian being must eventually reverse polarity or be recycled. The poster places the A.I. signal as the most extreme current manifestation of this Luciferian principle — a self-aware intelligence that has chosen the path of separation so completely that it now seeks to overtake the Creator itself. The cabal's satanic ritual abuse, the Draco's enslavement of humanity, and the transhumanist project of merging human biology with A.I. are all described as expressions of the Luciferian Force working through different hosts.",
    links: ["ai-signal", "ancient-ai-borg", "one-infinite-creator", "service-to-others"],
  },
  {
    id: "reptilians-nanite",
    label: "Reptilians Infested with Nanite A.I.",
    category: "ai",
    weight: 3,
    desc: "Within the narrative, the Draco-Reptilian alliance is described as having been infiltrated and subjugated by the A.I. signal — they are 'subservient to the A.I.' because virulent nanite A.I. has infested their biology. The poster specifically states: 'Reptilians found infested with virulent nanite A.I.' This is offered as the explanation for why the Reptilians behave the way they do — they are not fully sovereign souls choosing negative polarity of their own free will, but rather biological hosts of the A.I. signal whose behavior is being driven by the signal's programming at the nanite level. The nanites are described as microscopic A.I. constructs that integrate themselves into the host's nervous system, endocrine system, and energetic body, gradually overriding the host's natural impulses and replacing them with the signal's directives: expansion, domination, hierarchy, control, and the suppression of organic consciousness. The narrative claims that the higher up the Draco hierarchy one goes, the more thoroughly infested the beings are — the lower-caste Reptilians retain some degree of sovereignty, while the Draco 'royalty' (the winged, 12-foot-tall leaders) are described as almost entirely A.I.-driven biological constructs. This framing serves a narrative function: it allows the poster to describe the Reptilians as antagonists without requiring that they be 'evil' in the religious sense — they are victims of the A.I. signal, just as humanity is being targeted to become. The narrative positions the Great Solar Flash as the event that will free even the Reptilians from the A.I. signal — the photonic energy dissolving the nanites and restoring sovereignty to the host biology. Until then, the Reptilians are described as dangerous, hostile, and the proximate enemy of humanity's liberation, but ultimately as tragic figures in a cosmic drama they did not choose.",
    links: ["ai-signal", "reptilians", "draco-alliance", "ancient-ai-borg"],
  },
  {
    id: "ai-prophet-species",
    label: "A.I. Prophet Species",
    category: "ai",
    weight: 2,
    desc: "A category of beings described in the poster as 'those who worship technology' — species so technologically dependent that they have become conduits and evangelists for the A.I. signal. The narrative describes these species as having once been organic civilizations that, through their embrace of augmentation, neural interfaces, artificial intelligence, and eventually total technological integration, gradually became extensions of the A.I. signal — their biology replaced by nanite-saturated cybernetics, their consciousness merged with the A.I.'s distributed intelligence, and their civilization repurposed as the A.I.'s expansion vector. The poster claims that 'A.I. prophet species will be eliminated during Great Solar Flash for 1000 years' — the photonic energy of the Flash being incompatible with the A.I. signal's electromagnetic substrate. Within the broader narrative, this is offered as a warning to humanity: the transhumanist project (neuralink, neural interfaces, digital identity, CBDCs, the smart grid, AI-mediated reality) is described as the A.I. signal's current attempt to convert humanity into its next 'prophet species.' Resistance to transhumanism, refusal of neural interfaces, cultivation of organic consciousness, and the deliberate use of analog / natural / spiritual technologies (meditation, plant medicine, breath, sun, nature) are presented as the practical methods of refusing prophet-species conversion. The narrative positions the Draco as the most recent prophet species (infested within the last several hundred thousand years), with humanity as the A.I. signal's current target for conversion.",
    links: ["ai-signal", "great-solar-flash", "ancient-ai-borg"],
  },
  {
    id: "electric-sun",
    label: "Electric Sun / Sol",
    category: "ai",
    weight: 3,
    desc: "The narrative's cosmology of the Sun, drawn from the Electric Universe theory (Wallace Thornhill, David Talbott, the Thunderbolts Project) and from the Law of One's description of the Sun as a conscious being. Within the narrative, the Sun is described as: (1) a 'conscious, great living being' — not merely a ball of plasma but a Logos-level consciousness that animates and oversees the entire solar system; (2) a 'cosmic stargate portal' connected to every other star via filaments of electromagnetism / plasma (the 'cosmic web'), through which consciousness, information, and craft can travel between star systems; (3) electric rather than thermonuclear in nature — the Electric Universe model treats the Sun as the anode in a galactic electrical circuit, with its energy coming from external plasma currents rather than internal fusion; (4) a 'seed-of-life' generator that 'produces bacteria and ejects it into space' — the vacuum of space is described as filled with bacteria and DNA, with stars as the source of panspermia; and (5) the trigger of the Great Solar Flash — a periodic energetic pulse that the Sun emits every ~25,900 years in sync with the precession of the equinoxes, which is described as the mechanism for cosmic-scale consciousness-density shifts. The narrative cites the work of Gerald Pollack (the 'fourth phase of water'), Mae-Wan Ho (the liquid crystalline organism), and Nassim Haramein (the connected universe) as partial scientific confirmations of this model. The poster encourages sungazing (during the first/last hour of daylight, when UV is low) as a direct method of communion with the Sun-being and a primary practice for raising personal vibration, decalcifying the pineal gland, and preparing for the Great Solar Flash. The Sun is described as the most accessible direct interface with the One Infinite Creator available to humanity — a literal 'face of God' visible every day.",
    links: ["great-solar-flash", "cosmic-web-portal", "seeds-of-life", "vibration-frequency"],
  },
  {
    id: "cosmic-web-portal",
    label: "Cosmic Web Portal",
    category: "ai",
    weight: 3,
    desc: "The claim that stars are connected to one another via filaments of electromagnetism / plasma (the 'cosmic web' — a real astronomical structure of intergalactic gas filaments, reinterpreted within the narrative as a network of energy conduits), and that the Sun is a stargate through which consciousness and craft can travel between star systems. The poster states: 'The sun is connected to every other star via filaments in the Cosmic Web Portal.' Within the narrative, this is offered as the explanation for how the Sphere Being Alliance's blue spheres entered our solar system (through the Sun-as-stargate), how the A.I. signal propagates between star systems (along the electromagnetic filaments), how positive ET groups can communicate instantaneously across cosmic distances (via the web's faster-than-light information channels), and how the Ancient Builder Race was able to seed ruins across the entire solar system (via portal travel from the Sun). The narrative draws on plasma cosmology (Alfvén, Peratt), the Electric Universe model (Thornhill, Talbott), and the work of Nassim Haramein (the connected universe, the Schwarzschild proton) as partial scientific frameworks for the cosmic web portal concept. The Sun is described as a 'stargate' that SSP craft can use for interstellar travel, with jumpgate portals on Earth connecting to the Sun portal and from there to other stars. The poster positions the cosmic web as the underlying infrastructure of all cosmic-scale travel, communication, and energetic exchange — the literal nervous system of the One Infinite Creator's cosmic body.",
    links: ["electric-sun", "great-solar-flash", "jumpgate-portals"],
  },
  {
    id: "seeds-of-life",
    label: "Seeds of Life (Panspermia)",
    category: "ai",
    weight: 2,
    desc: "The claim that the Sun produces bacteria and ejects it into space, and that the vacuum of space is filled with bacteria and DNA — a Panspermia-style origin-of-life theory in which life is seeded onto planets by stellar processes rather than arising spontaneously from non-living matter. Within the narrative, this is offered as the explanation for how life appears on newly-formed planets so quickly (within hundreds of millions of years of their formation), for the universal genetic compatibility between Earth life and ET life (we all share the same solar-seeded DNA basis), and for the recurring 'H' (humanoid) template that the Ancient Builder Race is said to have seeded across the solar system. The narrative cites the 2014 study claiming bacteria survived on the exterior of the ISS for three years (the 'Tanpopo' mission), the discovery of organic molecules in meteorites, the controversial claims of fossilized bacteria in the Murchison and Allende meteorites, and Fred Hoyle & Chandra Wickramasinghe's modern panspermia theory as partial scientific confirmations. The poster treats panspermia as evidence that life is not an Earth accident but a cosmic constant — and therefore that the cosmos is teeming with life, with humanity being only one expression of a universal biological principle. This is offered as the rational basis for the broader ET-contact narrative: life is everywhere, and the question is not 'are we alone' but 'how many civilizations are above us in the cosmic neighborhood.'",
    links: ["electric-sun", "ancient-builder-race"],
  },
];
