import type { GAMNode } from "./types";

// ANCIENT CIVILIZATIONS — builder races, lost continents, pre-human ruins
export const ANCIENT_NODES: GAMNode[] = [
  {
    id: "ancient-builder-race",
    label: "Ancient Builder Race",
    category: "ancient",
    weight: 5,
    desc: "Within the narrative, a mysterious, technologically superhuman civilization that existed in our solar system ~1.3–2 billion years ago, building megalithic structures on every planet and moon — the ruins visible today on the Moon, Mars, Venus, Saturn's rings, Iapetus, Ceres, and Antarctica. Said to have been a 5D–7D 'custodian' race that vacated the solar system ~500,000 years ago, leaving their technology (sentinels, crystalline towers, 70-foot-tall giant ruins) behind. The narrative frames them as the source of the 'H' (humanoid) template used by all later ET groups.",
    links: ["ancient-aliens", "sentinels", "ringmakers-saturn", "iapetus", "70ft-giants", "venus", "moon", "mars", "ra"],
  },
  {
    id: "ancient-aliens",
    label: "Ancient Aliens (Theory)",
    category: "ancient",
    weight: 5,
    desc: "The 'ancient astronaut' hypothesis — that extraterrestrials visited Earth in antiquity, genetically engineered or upgraded early humans, and helped build (or directly built) the monumental architecture of antiquity (the pyramids, Göbekli Tepe, Puma Punku, Baalbek, Machu Picchu, etc.). Within the narrative, every ancient 'god' was an ET, every ancient megalith was ET-built, and the Annunaki / Ancient Builder Race / Pleiadians / Atlanteans are the major groups involved. Erich von Däniken's 'Chariots of the Gods' (1968) is the founding text.",
    sources: [
      { label: "Ancient astronauts — Wikipedia", url: "https://en.wikipedia.org/wiki/Ancient_astronauts" },
    ],
    links: ["annunaki", "ancient-builder-race", "atlantis", "giza-complex", "gobekli-tepe", "nazca-lines", "vimanas", "mahabharata"],
  },
  {
    id: "atlantis",
    label: "Atlantis",
    category: "ancient",
    weight: 4,
    desc: "Within the narrative, Atlantis was a real, technologically-advanced global civilization that existed ~50,000–12,000 years ago, founded by survivors of the Mars catastrophe who escaped to Earth, built the pyramids, and were destroyed in a cataclysm (~12,000 years ago) caused by a combination of war, misuse of crystal technology, and a comet impact. Edgar Cayce's readings are the primary source. Described as the immediate predecessor civilization to our own.",
    sources: [
      { label: "Atlantis — Wikipedia", url: "https://en.wikipedia.org/wiki/Atlantis" },
    ],
    links: ["ancient-aliens", "lemuria", "mars-catastrophe", "giza-complex", "ancient-builder-race"],
  },
  {
    id: "lemuria",
    label: "Lemuria / Mu",
    category: "ancient",
    weight: 3,
    desc: "A 19th-century 'lost continent' theory originally proposed to explain lemur distribution across the Indian Ocean, later repurposed by occultists (Madame Blavatsky, James Churchward) as a real pre-Atlantean Pacific civilization. Within the narrative, Lemuria/Mu was a spiritually-advanced, Pleiadian-influenced civilization that existed contemporaneously with or before Atlantis, and was destroyed in an earlier cataclysm. Said to be the source of Polynesian and Tibetan spiritual lineages.",
    sources: [
      { label: "Lemuria (continent) — Wikipedia", url: "https://en.wikipedia.org/wiki/Lemuria_(continent)" },
    ],
    links: ["atlantis", "ancient-aliens", "pleiadians", "tibet-tunnels"],
  },
  {
    id: "giza-complex",
    label: "Giza Complex / Great Pyramid",
    category: "ancient",
    weight: 4,
    desc: "Within the narrative, the Giza pyramids are not tombs but ancient technology — described as 'ascension machines,' energy generators (using the piezoelectric properties of limestone and granite and the aquifer beneath), and initiatory chambers built by Atlantis survivors or ET groups. The Sphinx is dated to ~10,500 BCE (Robert Bauval's Orion correlation), making it far older than mainstream Egyptology accepts. Hidden chambers beneath the Sphinx's paws are said to contain the Hall of Records.",
    sources: [
      { label: "Great Pyramid of Giza — Wikipedia", url: "https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza" },
    ],
    links: ["ancient-aliens", "atlantis", "egyptian-ra", "19.5", "ancient-builder-race"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kheops-Pyramid.jpg/1280px-Kheops-Pyramid.jpg",
    imageCredit: "Wikipedia / public domain",
  },
  {
    id: "cydonia-pyramids",
    label: "Cydonia Pyramids (Mars)",
    category: "ancient",
    weight: 3,
    desc: "Within the narrative, a cluster of pyramid-shaped structures in the Cydonia region of Mars, photographed by Viking in 1976, are artificial constructions built by the Ancient Builder Race or a pre-catastrophe Martian civilization. Richard C. Hoagland popularized the analysis. Said to mirror the geometry of the Giza complex and the '19.5°' tetrahedral mathematics.",
    links: ["face-on-mars", "ancient-builder-race", "mars", "19.5", "richard-hoagland", "giza-complex"],
  },
  {
    id: "face-on-mars",
    label: "Face on Mars (Cydonia)",
    category: "ancient",
    weight: 3,
    desc: "A 2-km-long mesa in the Cydonia region of Mars that, in a 1976 Viking orbiter image, appeared to resemble a humanoid face. Richard Hoagland and others argued it was an artificial monument. Within the narrative, the face is a deliberate ET/Ancient Builder Race monument, surrounded by pyramids and the 'Pharaoh Sarcophagus' structure. Later higher-resolution NASA imagery is dismissed within the community as deliberate obfuscation.",
    sources: [
      { label: "Cydonia (Mars) — Wikipedia", url: "https://en.wikipedia.org/wiki/Cydonia_(Mars)" },
    ],
    links: ["cydonia-pyramids", "mars", "ancient-builder-race", "richard-hoagland", "nasa-coverup"],
  },
  {
    id: "gobekli-tepe",
    label: "Göbekli Tepe",
    category: "ancient",
    weight: 3,
    desc: "A real ~11,600-year-old temple complex in southeastern Turkey — the oldest known megalithic site. Within the narrative, Göbekli Tepe is cited as 'proof' that an advanced prehistoric civilization (Atlantis survivors, ET contact, or Ancient Builder Race influence) existed before mainstream history admits. The fact that it was deliberately buried is taken as evidence of a 'reset' event the builders anticipated.",
    sources: [
      { label: "Göbekli Tepe — Wikipedia", url: "https://en.wikipedia.org/wiki/G%C3%B6bekli_Tepe" },
    ],
    links: ["ancient-aliens", "atlantis", "ancient-builder-race"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/G%C3%B6bekli_Tepe%2C_Urfa.jpg/1280px-G%C3%B6bekli_Tepe%2C_Urfa.jpg",
    imageCredit: "Teomancimit / Wikimedia Commons / CC BY-SA 3.0",
  },
  {
    id: "nazca-lines",
    label: "Nazca Lines",
    category: "ancient",
    weight: 3,
    desc: "Large geoglyphs in the Nazca Desert of Peru (~500 BCE–500 CE). Within the narrative, the Nazca Lines are ET landing strips, ceremonial astronomical markers, or signal art visible only from the air — 'evidence' that the Nazca culture was in contact with aerial / extraterrestrial beings. Erich von Däniken popularized this interpretation.",
    sources: [
      { label: "Nazca Lines — Wikipedia", url: "https://en.wikipedia.org/wiki/Nazca_Lines" },
    ],
    links: ["ancient-aliens", "vimanas", "ancient-builder-race"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Nazca_hummingbird.jpg/1280px-Nazca_hummingbird.jpg",
    imageCredit: "Wikimedia Commons / public domain",
  },
  {
    id: "mahabharata",
    label: "Mahabharata / Ancient Nuclear War",
    category: "ancient",
    weight: 3,
    desc: "The Sanskrit epic Mahabharata describes weapons of mass destruction (the Brahmastra) with effects resembling nuclear explosions. Within the narrative, these are literal descriptions of an ancient nuclear war between ET-influenced civilizations — evidenced by vitrified ruins, radioactive skeletons at Mohenjo-daro, and the 'desert glass' found in the Sahara and Rajasthan. Cited as evidence that advanced technology existed and was lost in antiquity.",
    sources: [
      { label: "Mahabharata — Wikipedia", url: "https://en.wikipedia.org/wiki/Mahabharata" },
    ],
    links: ["vimanas", "ancient-aliens", "atlantis", "ancient-builder-race"],
  },
  {
    id: "vimanas",
    label: "Vimanas (Ancient Flying Machines)",
    category: "ancient",
    weight: 3,
    desc: "Flying palaces/chariots described in Sanskrit epics. Within the narrative, Vimanas are real antigravity craft operated by ancient Indian civilizations, powered by mercury-vortex engines (described in the Samarangana Sutradhara), and the source of the SSP's later antigravity technology. The 'Vaimanika Shastra' is cited as the technical manual.",
    sources: [
      { label: "Vimana — Wikipedia", url: "https://en.wikipedia.org/wiki/Vimana" },
    ],
    links: ["mahabharata", "ancient-aliens", "antigravity", "ancient-builder-race"],
  },
  {
    id: "padmasambhava",
    label: "Padmasambhava",
    category: "ancient",
    weight: 2,
    desc: "The 8th-century Buddhist master who brought Vajrayana Buddhism to Tibet. Within the narrative, Padmasambhava is described as an ascended master / ET being who taught the Tibetan rainbow body ascension practices and concealed 'terma' (hidden teachings) for future generations to discover. Said to be a previous incarnation of the lineage that includes the Dalai Lama.",
    links: ["tibetan-rainbow-body", "dzogchen-rigpa", "ascension", "inner-earth-civilizations"],
  },
  {
    id: "tibetan-rainbow-body",
    label: "Tibetan Rainbow Body",
    category: "ancient",
    weight: 3,
    desc: "Within Tibetan Dzogchen, the 'rainbow body' (jalu) is the final realization in which the practitioner's physical body dissolves into light at death, leaving only hair and nails. Within the Great Awakening narrative, this is treated as documented, repeatable evidence that human consciousness can transition into a 'light body' — the same process being scaled up for all of humanity in the Great Solar Flash ascension.",
    sources: [
      { label: "Rainbow body — Wikipedia", url: "https://en.wikipedia.org/wiki/Rainbow_body" },
    ],
    links: ["light-body-ascension", "dzogchen-rigpa", "ascension", "padmasambhava", "5d-earth"],
  },
  {
    id: "dzogchen-rigpa",
    label: "Dzogchen / Rigpa",
    category: "ancient",
    weight: 3,
    desc: "The highest teachings of Tibetan Buddhism (Dzogchen) and the state of pure awareness they point to (Rigpa = 'non-dual awareness'). Within the narrative, Dzogchen is the most direct path to the rainbow body / light body ascension on Earth, and its teachings are described as the surviving human-accessible version of the same ascension process the Blue Avians / Ra describe from the ET side.",
    links: ["tibetan-rainbow-body", "light-body-ascension", "ascension", "empty-awareness", "padmasambhava"],
  },
  {
    id: "sentinels",
    label: "Sentinels (5D–7D Custodians)",
    category: "ancient",
    weight: 2,
    desc: "Within the narrative, ethereal 5th–7th-density custodians left behind by the Ancient Builder Race to guard their vacated technology across the solar system. Described as non-physical, multidimensional beings who watch over the ruins on the Moon, Mars, Venus, and Saturn. Said to be the source of the 'sentinel' phenomenon reported by SSP personnel.",
    links: ["ancient-builder-race", "venus", "moon", "mars", "saturn"],
  },
  {
    id: "mars-catastrophe",
    label: "Mars Catastrophe → Atlantis Survivors",
    category: "ancient",
    weight: 3,
    desc: "Within the narrative, ~500,000 years ago the planets Maldek and Mars were destroyed in an ancient nuclear war between ET factions. The survivors of the Mars catastrophe escaped to Earth and built Atlantis and the pyramids as their first colony. This is given as the explanation for the ruins on Mars and the asteroid belt (the remains of Maldek).",
    links: ["maldek", "mars", "atlantis", "asteroid-belt", "mahabharata", "ancient-aliens"],
  },
  {
    id: "maldek",
    label: "Maldek (Destroyed Planet → Asteroid Belt)",
    category: "ancient",
    weight: 3,
    desc: "Within the narrative (sourced from the Ra Material), a fifth planet existed between Mars and Jupiter that was destroyed in a war ~500,000–3 million years ago. The asteroid belt is described as its remains ('Brilliant Pebbles' is the SSP term). The souls of Maldek were quarantined on Earth and became a portion of the modern human population. Cited as a cautionary precedent for Earth's current trajectory.",
    links: ["mars-catastrophe", "asteroid-belt", "law-of-one", "ra", "ancient-aliens"],
  },
  {
    id: "asteroid-belt",
    label: "Asteroid Belt (Brilliant Pebbles)",
    category: "ancient",
    weight: 2,
    desc: "Within the narrative, the asteroid belt is the debris of the destroyed planet Maldek. The SSP term 'Brilliant Pebbles' (borrowed from a real SDI missile-defense program) is used to describe both the asteroid belt and the SSP's classified survey of those asteroids for Ancient Builder Race ruins.",
    links: ["maldek", "mars-catastrophe", "ancient-builder-race", "secret-space-program"],
  },
  {
    id: "19.5",
    label: "19.5° Tetrahedral Geometry",
    category: "ancient",
    weight: 3,
    desc: "Richard C. Hoagland's claim that key features across the solar system (Jupiter's Great Red Spot, Mars' Olympus Mons, Earth's Hawaiian volcanoes, the apex of the Cydonia face) lie at 19.5° latitude — the apex of an inscribed tetrahedron inside a rotating sphere. Cited as evidence of 'hyperdimensional physics' — that energy is being drawn into 3D space from higher dimensions at these points. A recurring motif across the narrative.",
    links: ["richard-hoagland", "cydonia-pyramids", "face-on-mars", "giza-complex", "nasa-coverup"],
  },
  {
    id: "egyptian-ra",
    label: "Egyptian Ra (Sun God)",
    category: "ancient",
    weight: 3,
    desc: "Within the narrative, the Egyptian deity Ra was a real 6th-density ET being (the same Ra that channeled the Law of One in 1981) who walked among the ancient Egyptians, helped build the pyramids as ascension machines, and was remembered as the sun god. Said to be the same consciousness now returning as the Sphere Being Alliance / Blue Avians.",
    links: ["ra", "law-of-one", "giza-complex", "ancient-aliens", "sphere-being-alliance"],
  },
  {
    id: "pharaoh-sarcophagus-mars",
    label: "Pharaoh Sarcophagus (Mars)",
    category: "ancient",
    weight: 2,
    desc: "Within the narrative, a structure in the Cydonia region of Mars resembling an Egyptian pharaoh's sarcophagus, cited as evidence that the same ET / Ancient Builder Race civilization built monuments on both Mars and Earth. Part of Hoagland's Cydonia geometry analysis.",
    links: ["cydonia-pyramids", "face-on-mars", "egyptian-ra", "ancient-aliens"],
  },
  {
    id: "tibet-tunnels",
    label: "Tibet Underground Tunnels",
    category: "ancient",
    weight: 2,
    desc: "Within the narrative, a network of secret underground tunnels beneath Tibet (and the Himalayas more broadly) connects to the inner-Earth civilizations (Agartha, Shambhala). Said to have been used by Padmasambhava, by 20th-century Nazi expeditions (the 1938–39 Ahnenerbe Tibet expedition), and to be the source of the Tibetan rainbow body lineages.",
    links: ["inner-earth-civilizations", "agartha", "padmasambhava", "nazi-breakaway", "dzogchen-rigpa"],
  },
];
