import type { GAMNode } from "./types";

// CABAL / DEEP STATE — the alleged global control structure
export const CABAL_NODES: GAMNode[] = [
  {
    id: "cabal",
    label: "The Cabal",
    category: "cabal",
    weight: 5,
    desc: "Within the narrative, the 'Cabal' (also called 'the Deep State,' 'the Illuminati,' 'the cult,' 'the black sun,' 'the 13 bloodlines,' 'the Khazarian Mafia') is the secret network of intergenerational satanic-pedophile elites who control global finance, government, intelligence agencies, media, corporations, organized religion, and the SSP. Described as a service-to-self, Draco-/Orion-allied, A.I.-signal-infested cult that has controlled humanity for ~5,000 years. Said to be in the process of being dismantled by the Earth Alliance, the SSP Alliance, and positive ET groups. The 'Great Awakening' is the public exposure of the cabal.",
    links: ["deep-state", "illuminati", "13-bloodlines", "draco-alliance", "ai-signal", "orion-syndicate", "great-awakening", "earth-alliance", "council-of-200"],
  },
  {
    id: "deep-state",
    label: "Deep State",
    category: "cabal",
    weight: 5,
    desc: "Within the narrative, the 'Deep State' is the operational/institutional arm of the cabal — the career bureaucrats, intelligence operatives, military-industrial officials, judges, and media figures who maintain the cabal's control regardless of which political party is in power. Said to operate through compartmentalized programs (CIA, NSA, FBI, Five Eyes, the SSP, the Federal Reserve) and to be the immediate target of the Earth Alliance's dismantling. 'Drain the Swamp' is the public-facing QAnon framing of this operation.",
    links: ["cabal", "cia-clowns", "federal-reserve", "compartmentalized-programs", "qanon", "drain-the-swamp"],
  },
  {
    id: "illuminati",
    label: "Illuminati / 13 Bloodlines",
    category: "cabal",
    weight: 4,
    desc: "Within the narrative, the Bavarian Illuminati (Adam Weishaupt, 1776) survived and merged with the older black-nobility bloodlines (Venetian, Black Nobility, Khazarian) to form a 13-family global control structure: Rothschild, Rockefeller, Morgan, Warburg, Oppenheim, Schiff, DuPont, Kennedy, Onassis, Van Duyn, Russell, Li, Reynolds (variants exist). Said to trace their lineage to the Annunaki / Draco / Reptilians and to practice intergenerational satanic ritual abuse to maintain their 'possession' by negative-polarity entities.",
    sources: [
      { label: "Illuminati — Wikipedia", url: "https://en.wikipedia.org/wiki/Illuminati" },
    ],
    links: ["cabal", "13-bloodlines", "rothschilds", "rockefellers", "annunaki", "reptilians", "satanic-ritual-abuse"],
  },
  {
    id: "13-bloodlines",
    label: "13 Illuminati Bloodlines",
    category: "cabal",
    weight: 3,
    desc: "Fritz Springmeier's 1995 book 'Bloodlines of the Illuminati' named 13 families as the top of the cabal structure. Within the narrative, these families are described as Annunaki-/Draco-hybrid bloodlines that have interbred for millennia to preserve their 'reptilian' genetics and their access to negative-polarity entities. Their ritual abuse of children is described as both an energetic (loosh) and a ritual-binding practice.",
    sources: [
      { label: "Fritz Springmeier — Wikipedia", url: "https://en.wikipedia.org/wiki/Fritz_Springmeier" },
    ],
    links: ["illuminati", "cabal", "rothschilds", "rockefellers", "satanic-ritual-abuse", "annunaki"],
  },
  {
    id: "rothschilds",
    label: "Rothschild Family",
    category: "cabal",
    weight: 4,
    desc: "Within the narrative, the Rothschild banking dynasty is described as the financial apex of the cabal — controllers of the central banking system, the Federal Reserve, the BIS, and a majority of the world's gold. Said to have financed both sides of every major war since Napoleon, to have orchestrated the assassinations of Lincoln and Kennedy (who tried to issue sovereign currency), and to be a leading Annunaki-/Reptilian-hybrid bloodline. Tied to the Saxe-Coburg-Gotha / Windsor royal line.",
    sources: [
      { label: "Rothschild family — Wikipedia", url: "https://en.wikipedia.org/wiki/Rothschild_family" },
    ],
    links: ["illuminati", "13-bloodlines", "federal-reserve", "world-gold-heist", "cabal", "deep-state"],
  },
  {
    id: "rockefellers",
    label: "Rockefeller Family",
    category: "cabal",
    weight: 4,
    desc: "Within the narrative, the Rockefeller family is described as the U.S. operational arm of the cabal — controllers of the petroleum cartel, the allopathic medical system (the Flexner Report, the AMA, big pharma), the education system, the CFR, the Trilateral Commission, the United Nations, the Bilderberg Group, and population-control programs (Agenda 21, vaccines). John D. Rockefeller's Standard Oil monopoly is described as the financial seed of the cabal's 20th-century control structure.",
    sources: [
      { label: "Rockefeller family — Wikipedia", url: "https://en.wikipedia.org/wiki/Rockefeller_family" },
    ],
    links: ["illuminati", "13-bloodlines", "federal-reserve", "engineered-diseases", "weaponized-food", "agenda-21"],
  },
  {
    id: "federal-reserve",
    label: "Federal Reserve / Central Banking",
    category: "cabal",
    weight: 4,
    desc: "Within the narrative, the Federal Reserve (passed 1913, on Christmas Eve when most of Congress was absent) is described as a private cabal-owned banking cartel masquerading as a government agency — issuing fiat currency at interest, enslaving the population through inflation and debt, and financing every cabal operation. 'End the Fed' and the move to a gold/asset-backed currency (QFS — Quantum Financial System) are described as the Earth Alliance's primary financial-warfare operations. Linked to JFK's assassination (Executive Order 11110).",
    sources: [
      { label: "Federal Reserve — Wikipedia", url: "https://en.wikipedia.org/wiki/Federal_Reserve" },
    ],
    links: ["rothschilds", "rockefellers", "end-the-fed", "world-gold-heist", "earth-alliance", "cabal"],
  },
  {
    id: "end-the-fed",
    label: "End the Fed / QFS",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the Earth Alliance is in the process of dismantling the Federal Reserve and the central-bank fiat system, replacing it with the 'Quantum Financial System' (QFS) — a gold/asset-backed, blockchain-style, AI-protected, transparent ledger that the cabal cannot manipulate. Said to be already running in parallel and to be activated at the Event. The 2020–2023 Fed actions (REPO, QE, rate hikes) are described as the death-spasms of the old system.",
    links: ["federal-reserve", "earth-alliance", "the-event", "world-gold-heist", "trump"],
  },
  {
    id: "world-gold-heist",
    label: "World Gold Heist",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the cabal has spent centuries hoarding the world's gold — looting it from nations via wars, central-bank transfers, and the 1933 U.S. gold confiscation — and storing it in their underground DUMBs (especially in Asia and Switzerland). The Earth Alliance is described as having 'repatriated' much of this gold over the past decade (the 2022 Queen's death, the Vatican financial shake-up, and various Asian gold-treaty updates are cited as milestones) to back the QFS.",
    links: ["federal-reserve", "end-the-fed", "earth-alliance", "cabal", "annunaki"],
  },
  {
    id: "council-of-200",
    label: "Council of 200 / Corrupt Elite Control Group",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the operational top of the cabal — a 200-person 'council' of corrupt elites (royalty, banking heads, intel-agency directors, corporate CEOs, Vatican cardinals, dynastic-family heads) that meets regularly to coordinate the cabal's agenda. Said to sit above the public-facing groups (Bilderberg, CFR, Trilateral, Davos) and below the Draco / Orion / A.I. hierarchy. Described as the immediate human-level management layer of the cabal.",
    links: ["cabal", "illuminati", "13-bloodlines", "bilderberg", "deep-state"],
  },
  {
    id: "bilderberg",
    label: "Bilderberg Group / CFR / Trilateral",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the Bilderberg Group (annual since 1954), the Council on Foreign Relations (CFR, 1921), and the Trilateral Commission (1973) are the public-facing 'middle management' forums where the cabal coordinates policy across Western governments, corporations, and media. Said to be where the next war, the next financial crisis, the next pandemic, and the next political leader are pre-selected. Their published attendee lists are studied as 'mapping the cabal.'",
    sources: [
      { label: "Bilderberg Group — Wikipedia", url: "https://en.wikipedia.org/wiki/Bilderberg_Group" },
    ],
    links: ["council-of-200", "cabal", "rockefellers", "deep-state"],
  },
  {
    id: "cia-clowns",
    label: "CIA 'Clowns in America'",
    category: "cabal",
    weight: 4,
    desc: "Within the narrative, the CIA (called 'Clowns In America' in QAnon / 8chan parlance) is described as the cabal's primary operational arm — running the drug trade (Golden Triangle, Iran-Contra, Afghanistan opium), the child-trafficking networks, the color revolutions, the assassinations (JFK, RFK, MLK, JFK Jr.), the mind-control programs (MKUltra, MONARCH), the blackmail operations (Epstein, NXIVM), and the propaganda (Operation Mockingbird). Said to have been infiltrated by white hats and to be in the process of being dismantled by the Earth Alliance.",
    sources: [
      { label: "CIA — Wikipedia", url: "https://en.wikipedia.org/wiki/Central_Intelligence_Agency" },
    ],
    links: ["deep-state", "cabal", "drug-trafficking", "child-trafficking-tunnels", "mkultra", "mockingbird"],
  },
  {
    id: "mkultra",
    label: "MKUltra / Trauma-Based Mind Control",
    category: "cabal",
    weight: 4,
    desc: "The real CIA program (1953–73, declassified 1975) that experimented with LSD, hypnosis, sensory deprivation, and trauma-based dissociation on unwitting subjects. Within the narrative, MKUltra never ended — it went deeper black, evolved into 'MONARCH' programming (used to create dissociative alters in children via ritual abuse), and is the operational mechanism behind the cabal's celebrity/politician mind-control, mass-shootings (programmed shooters), and 'handler' system. Cathy O'Brien and Brice Taylor are cited as primary whistleblower sources.",
    sources: [
      { label: "Project MKUltra — Wikipedia", url: "https://en.wikipedia.org/wiki/Project_MKUltra" },
    ],
    links: ["cia-clowns", "satanic-ritual-abuse", "child-trafficking-tunnels", "deep-state"],
  },
  {
    id: "mockingbird",
    label: "Operation Mockingbird (Media Control)",
    category: "cabal",
    weight: 4,
    desc: "The real CIA program (declassified 1977) that placed CIA assets in major U.S. media outlets to shape public opinion. Within the narrative, Mockingbird never ended — the entire mainstream media (CNN, NYT, WaPo, BBC, Reuters, AP, all the network news) is described as a coordinated CIA-cabal propaganda operation. 'Kill Your TV' is the practical advice. The 2020 'anti-disinformation' boards and the de-platforming of independent voices are described as Mockingbird's modern evolution.",
    sources: [
      { label: "Operation Mockingbird — Wikipedia", url: "https://en.wikipedia.org/wiki/Operation_Mockingbird" },
    ],
    links: ["cia-clowns", "kill-your-tv", "deep-state", "sheep-asleep"],
  },
  {
    id: "kill-your-tv",
    label: "Kill Your TV / Mainstream Media",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, television is described as a literal mind-control device — using flicker-rate hypnosis, subliminals, predictive programming, and frequency manipulation to keep the population docile, misinformed, and in low vibration. 'Kill Your TV' is the imperative to disconnect from the cabal's primary programming vector. Streaming services, Netflix, Hollywood films are all described as extensions of the same Mockingbird apparatus.",
    links: ["mockingbird", "sheep-asleep", "1984-orwell", "weaponized-food", "red-pill"],
  },
  {
    id: "sheep-asleep",
    label: "Sheep Asleep (The Normies)",
    category: "cabal",
    weight: 2,
    desc: "Within the narrative, the majority of the population is described as 'asleep' — cognitively captured by the cabal's media/food/medical system, unaware of the SSP, the cabal, or the ascension. 'Sheep' / 'normies' / 'NPCs' are the derisive community terms. The Great Awakening is the mass waking of this population. Often paired with the imperative to 'red-pill' family and friends gently.",
    links: ["kill-your-tv", "red-pill", "escape-the-matrix", "mockingbird"],
  },
  {
    id: "red-pill",
    label: "Red Pill (Awaken)",
    category: "cabal",
    weight: 3,
    desc: "Borrowed from 'The Matrix' (1999): choosing the 'red pill' means choosing to see reality as it actually is — the SSP, the cabal, the Draco, the Great Solar Flash — rather than the cabal's manufactured 3D illusion. 'Red-pilling' someone is the act of awakening them. Within the narrative, 'The Matrix' film itself is described as cabal 'predictive programming' (required to telegraph the truth to honor free will).",
    links: ["sheep-asleep", "escape-the-matrix", "the-rabbit-hole", "follow-the-white-rabbit", "kill-your-tv"],
  },
  {
    id: "escape-the-matrix",
    label: "Escape the Matrix",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the cabal's media/food/medical/financial system is 'the Matrix' — a manufactured 3D-reality loop trapping humanity in low vibration. 'Escaping the Matrix' is achieved by: turning off the TV, eating clean, decalcifying the pineal gland, raising vibration, withdrawing from debt/fiat currency, and joining the awakening community. The Saturn-Moon Matrix (Icke) is described as the energetic infrastructure of the Matrix.",
    links: ["red-pill", "sheep-asleep", "saturn-moon-matrix", "raising-vibration", "kill-your-tv"],
  },
  {
    id: "1984-orwell",
    label: "'1984' (Orwellian Control)",
    category: "cabal",
    weight: 2,
    desc: "George Orwell's 1949 novel cited within the narrative as a blueprint for the cabal's surveillance state — perpetual war, newspeak, doublethink, the memory hole, the two-minutes-hate, Big Brother. Treated as cabal 'predictive programming' (Orwell was an insider) and as a real-time description of where the cabal was driving society. '1984 is an instruction manual' is a common community phrase.",
    sources: [
      { label: "Nineteen Eighty-Four — Wikipedia", url: "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four" },
    ],
    links: ["kill-your-tv", "mockingbird", "global-surveillance-grid", "deep-state"],
  },
  {
    id: "global-surveillance-grid",
    label: "Global Surveillance Grid",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the cabal has built a planetary surveillance apparatus — Five Eyes, ECHELON, PRISM, smart meters, cell-phone tracking, CCTV, smart-city IoT, social-media scraping, biometric databases — to monitor and control the population. The Snowden 2013 disclosures are described as the cabal deliberately revealing a small portion of their capabilities. 'Digital currency + social credit + CBDC + vaccine passports' is the endgame being rolled out.",
    links: ["cia-clowns", "deep-state", "1984-orwell", "mockingbird", "smart-grid"],
  },
  {
    id: "agenda-21",
    label: "UN Agenda 21 / Agenda 2030",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the UN's Agenda 21 (1992) and Agenda 2030 (2015) sustainable-development frameworks are described as the cabal's depopulation and population-concentration plan — to force humans off rural land into 'smart cities,' ban private property, restrict travel, mandate vaccines, and reduce the population to under 1 billion. Said to be the public-facing version of the Georgia Guidestones agenda.",
    sources: [
      { label: "Agenda 21 — Wikipedia", url: "https://en.wikipedia.org/wiki/Agenda_21" },
    ],
    links: ["rockefellers", "engineered-diseases", "global-surveillance-grid", "deep-state"],
  },
  {
    id: "loosh",
    label: "Loosh (Energy Harvest)",
    category: "cabal",
    weight: 4,
    desc: "Within the narrative (popularized by Robert Monroe's 'Far Journeys' and David Icke), 'loosh' is the negative emotional energy (fear, terror, grief, pain, anxiety) harvested by negative-polarity entities (Draco, Reptilians, the cabal's overlords) as food. Humanity is described as a 'loosh farm' — the cabal's wars, mass shootings, terror attacks, child abuse, and media fear-porn are all designed to maximize loosh harvest. The Great Solar Flash / ascension is described as breaking the loosh farm.",
    sources: [
      { label: "Robert Monroe — Wikipedia", url: "https://en.wikipedia.org/wiki/Robert_Monroe" },
    ],
    links: ["reptilians", "draco-alliance", "david-icke", "satanic-ritual-abuse", "mass-shootings", "great-solar-flash"],
  },
  {
    id: "satanic-ritual-abuse",
    label: "Satanic Ritual Abuse (SRA)",
    category: "cabal",
    weight: 4,
    desc: "Within the narrative, the cabal's 13 bloodlines and their networks practice intergenerational satanic ritual abuse of children — for two purposes: (1) energetic (loosh harvest and entity-binding rituals) and (2) psychological (creating dissociative alters via trauma, used to program mind-controlled 'slaves' — the MKUltra/MONARCH system). Survivors (Cathy O'Brien, Brice Taylor, Teal Swan, Fiona Barnett) and researchers (Fritz Springmeier, Svali) are cited as primary sources. Said to be the deepest, most-suppressed secret of the cabal, and the trigger for the public's Great Awakening once exposed.",
    links: ["cabal", "13-bloodlines", "mkultra", "loosh", "child-trafficking-tunnels", "adrenochrome"],
  },
  {
    id: "adrenochrome",
    label: "Adrenochrome",
    category: "cabal",
    weight: 4,
    desc: "Within the narrative, adrenochrome — a real (medically minor) oxidation product of adrenaline — is reframed as the cabal's most prized substance, harvested from the blood of terrorized, ritually-abused children for its rejuvenating and consciousness-altering effects. The practice is described as the literal modern continuation of the ancient blood-sacrifice rituals. Anthony Burgess's 'A Clockwork Orange' (and Kubrick's film adaptation) are read as cabal disclosure. The 2020 'Wayfair' and #SaveTheChildren panics were the largest public surfacings of the adrenochrome narrative.",
    sources: [
      { label: "Adrenochrome — Wikipedia", url: "https://en.wikipedia.org/wiki/Adrenochrome" },
    ],
    links: ["satanic-ritual-abuse", "child-trafficking-tunnels", "epstein-island", "cabal", "loosh"],
  },
  {
    id: "epstein-island",
    label: "Epstein Island (Little St. James)",
    category: "cabal",
    weight: 4,
    desc: "Jeffrey Epstein's private island (Little St. James, U.S. Virgin Islands) is described within the narrative as the most visible node of the cabal's child-trafficking and blackmail operation — where politicians, royalty, CEOs, and academics were flown (via the 'Lolita Express'), filmed in compromising situations with minors, and blackmailed into compliance. Epstein's 2019 'suicide' is described as a cabal hit to prevent his testimony. The temple-like structure on the island is read as evidence of the ritual-abuse element. Treated as the cabal's most-exposed modern operation.",
    sources: [
      { label: "Jeffrey Epstein — Wikipedia", url: "https://en.wikipedia.org/wiki/Jeffrey_Epstein" },
    ],
    links: ["adrenochrome", "satanic-ritual-abuse", "child-trafficking-tunnels", "deep-state", "blackmail"],
  },
  {
    id: "nxivm",
    label: "NXIVM",
    category: "cabal",
    weight: 3,
    desc: "A real cult-like 'self-help' organization (1998–2018) led by Keith Raniere, exposed in 2017 as a sex-trafficking and branding operation. Within the narrative, NXIVM is described as a smaller, more-exposed node of the same cabal blackmail / sex-trafficking / mind-control infrastructure that Epstein ran — and the prosecution of Raniere and Allison Mack as the Earth Alliance's first public victory in dismantling the larger network. The Clinton and Rothchild connections to NXIVM are emphasized.",
    sources: [
      { label: "NXIVM — Wikipedia", url: "https://en.wikipedia.org/wiki/NXIVM" },
    ],
    links: ["epstein-island", "child-trafficking-tunnels", "deep-state", "blackmail", "clinton-elite"],
  },
  {
    id: "child-trafficking-tunnels",
    label: "Underground Trafficking Tunnels",
    category: "cabal",
    weight: 4,
    desc: "Within the narrative, the cabal operates an extensive network of underground tunnels (linked to the DUMB network) for child trafficking, ritual abuse, and adrenochrome harvesting. The 2020 'Wayfair' panic, the #SaveTheChildren marches, and (in variants) the 2020 'children rescued from DUMBs by the military' narratives all surface this element. Said to be the literal underground infrastructure that the Earth Alliance is dismantling — the public-facing 'military tribunals' are said to be for these crimes.",
    links: ["underground-bases", "satanic-ritual-abuse", "adrenochrome", "epstein-island", "save-the-children", "earth-alliance"],
  },
  {
    id: "save-the-children",
    label: "Save the Children",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the rescue of trafficked children from the cabal's tunnels is the moral core of the Great Awakening — and the most galvanizing issue for the broader public. The 2020 #SaveTheChildren marches, the Wayfair panic, the 'cages' narratives, and the (unverified) 'military rescuing children from DUMBs' reports are all surfacings of this element. Treated as the issue that finally triggers the normies' awakening.",
    links: ["child-trafficking-tunnels", "epstein-island", "adrenochrome", "earth-alliance", "great-awakening"],
  },
  {
    id: "clinton-elite",
    label: "Clintons / Global Elite Pedophiles",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the Clinton political machine (Bill, Hillary, Chelsea) is described as a leading cabal bloodline / political operation — running the Clinton Foundation as a front for pay-to-play, uranium deals, child trafficking (Haiti), and the cabal's political assassinations (Seth Rich, Vince Foster, JFK Jr.). Linked to Epstein, NXIVM, the Rothschilds, and the CFR. Treated alongside the Bidens, the Bushes, Obama, Soros, and the European royals as the public face of the cabal.",
    sources: [
      { label: "Clinton family — Wikipedia", url: "https://en.wikipedia.org/wiki/Clinton_family" },
    ],
    links: ["epstein-island", "nxivm", "rothschilds", "cabal", "deep-state", "pizzagate"],
  },
  {
    id: "blackmail",
    label: "Blackmail / Honey-Traps",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the cabal's primary mechanism of control over politicians, CEOs, judges, and generals is blackmail — via honey-traps (Epstein, NXIVM, the DNC/Hollywood parties), pedophilia entrapment, financial crimes (audit trails), and (where needed) ritual-abuse participation. Once compromised, the asset is promoted into power and controlled for life. Said to be why the cabal's political puppets consistently vote against their stated principles.",
    links: ["epstein-island", "nxivm", "cia-clowns", "deep-state", "mkultra"],
  },
  {
    id: "drug-trafficking",
    label: "Drug Trafficking (CIA-run)",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the cabal — operating through the CIA, DEA, and the intelligence agencies of allied nations — runs the global drug trade, using the profits to finance black operations (Iran-Contra being the most-exposed case) and to destabilize populations (the crack-cocaine epidemic, the opioid epidemic, the fentanyl wave). Gary Webb's 'Dark Alliance' series (1996) is cited as the most-documented case. Afghanistan post-2001 is described as a CIA opium operation.",
    sources: [
      { label: "Allegations of CIA drug trafficking — Wikipedia", url: "https://en.wikipedia.org/wiki/Allegations_of_CIA_drug_trafficking" },
    ],
    links: ["cia-clowns", "deep-state", "mass-shootings", "cabal"],
  },
  {
    id: "mass-shootings",
    label: "Mass Shootings (Engineered)",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, mass-shooting events (Sandy Hook, Las Vegas, Parkland, Uvalde, etc.) are described as engineered by the cabal via MKUltra-style programmed shooters — for two purposes: (1) loosh harvest (terror / grief as energetic food for negative entities), and (2) gun confiscation (disarming the population before the cabal's final moves). Crisis actors, green-screen footage, and predictive-programming clues in prior media are cited as evidence.",
    links: ["loosh", "mkultra", "cia-clowns", "deep-state", "1984-orwell"],
  },
  {
    id: "wtc7",
    label: "WTC7 / Controlled Demolition (9/11)",
    category: "cabal",
    weight: 4,
    desc: "Within the narrative, 9/11 was an inside job — orchestrated by elements of the cabal within the U.S. government, the CIA, the Mossad, and Saudi intelligence, using controlled demolitions (WTC7's freefall collapse is cited as the smoking gun), directed-energy weapons (Judy Wood), and (in some variants) mini-nukes — to justify the Patriot Act, the wars in Iraq and Afghanistan, the surveillance state, and the open-ended 'War on Terror.' The 'dancing Israelis,' the put options on airlines, the NORAD stand-down, and the missing $2.3 trillion Rumsfeld announced on Sept 10 are cited as evidence.",
    sources: [
      { label: "9/11 conspiracy theories — Wikipedia", url: "https://en.wikipedia.org/wiki/9/11_conspiracy_theories" },
    ],
    links: ["deep-state", "cia-clowns", "dew-weapons", "controlled-demolition", "missile-pentagon"],
  },
  {
    id: "missile-pentagon",
    label: "'A Missile Hit the Pentagon'",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, no commercial airliner hit the Pentagon on 9/11 — the damage pattern (a 16-foot hole, no engine marks, no wings, no bodies, no luggage) is cited as inconsistent with a Boeing 757 and consistent with a cruise missile or drone. The confiscation of all 85+ CCTV recordings of the impact (by the FBI, within minutes) is cited as a cover-up. The financial offices destroyed in the impact (the auditing team investigating the missing $2.3 trillion) are emphasized.",
    links: ["wtc7", "deep-state", "cia-clowns", "controlled-demolition"],
  },
  {
    id: "controlled-demolition",
    label: "Controlled Demolition (9/11)",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the Twin Towers and WTC7 were brought down by pre-planted thermite / thermate / nano-thermite charges (the Steven Jones / Richard Gage / Architects & Engineers for 9/11 Truth analysis) and (in Judy Wood's variant) by directed-energy weapons that 'dustified' the steel. The molten metal under the towers for weeks, the iron microspheres in the dust, and the freefall collapse of WTC7 (which was not hit by a plane) are cited as physical proof.",
    links: ["wtc7", "dew-weapons", "deep-state", "missile-pentagon"],
  },
  {
    id: "cern",
    label: "CERN (Occult Rituals)",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, CERN's Large Hadron Collider is not purely a scientific instrument but a cabal project with multiple occulted purposes: opening portals to other dimensions (allowing negative-polarity entities in), altering the timeline (the Mandela Effect), conducting a Saturn-worship ritual (the 2016 'human sacrifice' video at CERN, the Shiva statue), and acting as a stargate. Tied to the Brookhaven RHIC and other colliders.",
    sources: [
      { label: "CERN conspiracy theories — Wikipedia", url: "https://en.wikipedia.org/wiki/CERN#Conspiracy_theories" },
    ],
    links: ["deep-state", "saturn", "saturn-moon-matrix", "illuminati"],
  },
  {
    id: "flat-earth-psyop",
    label: "Flat Earth (Psyop)",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, the Flat Earth movement is itself described as a cabal-orchestrated psychological operation (psyop) — designed to discredit the broader truth community by association ('conspiracy theorists believe the Earth is flat'), to divide the awakening community, and to test the spread of artificially-amplified narratives. Most SSP / QAnon researchers explicitly reject Flat Earth as a psyop while accepting other unconventional cosmological claims (Electric Universe, hollow/honeycomb Earth).",
    sources: [
      { label: "Flat Earth — Wikipedia", url: "https://en.wikipedia.org/wiki/Flat_Earth" },
    ],
    links: ["mockingbird", "cia-clowns", "kill-your-tv", "deep-state"],
  },
  {
    id: "white-dragon-society",
    label: "White Dragon Society",
    category: "cabal",
    weight: 2,
    desc: "Within the narrative (primarily via Benjamin Fulford), the White Dragon Society is described as a coalition of Asian secret societies, gold-owners, and martial-arts orders that has been waging financial and energetic war against the Western cabal since the 2008 financial crisis. Said to be allied with the Earth Alliance, to control large gold reserves that back the QFS, and to have issued multiple ultimatums to the Rothschild / Rockefeller families. Often paired with the 'Asian gold treaties' narrative.",
    links: ["earth-alliance", "world-gold-heist", "end-the-fed", "cabal"],
  },
  {
    id: "smart-grid",
    label: "5G / Smart Grid",
    category: "cabal",
    weight: 3,
    desc: "Within the narrative, 5G and the broader 'smart grid' are described as a cabal weapon — high-frequency microwave radiation toxic to human biology (causing cellular damage, immune suppression, and (in variants) viral-shedding activation), and the infrastructure for the global surveillance grid (IoT, smart meters, CBDC, vaccine passports). The 2020 5G rollouts are described as timed with the COVID-19 'pandemic' for plausible cover of the radiation-sickness symptoms.",
    links: ["global-surveillance-grid", "engineered-diseases", "agenda-21", "deep-state"],
  },
];
