import type { GAMNode } from "./types";

// CORE / UMBRELLA — the binding concepts of the entire map
export const CORE_NODES: GAMNode[] = [
  {
    id: "great-awakening",
    label: "The Great Awakening",
    category: "core",
    weight: 5,
    desc: "The umbrella term for the entire narrative: a predicted mass awakening of humanity in which secret space programs, extraterrestrial contact, ancient builder races, suppressed technology, and a hidden global control structure are all simultaneously exposed. Described as both a spiritual event (raising of collective consciousness) and a political event (takedown of the 'cabal'). Said to be prophesied in every historical religion under different names.",
    sources: [
      { label: "GreatAwakeningMap.co (poster source)", url: "https://www.greatawakeningmap.co/" },
      { label: "Wikipedia: Great Awakening (disambiguation)", url: "https://en.wikipedia.org/wiki/Great_Awakening" },
    ],
    links: ["great-solar-flash", "full-disclosure", "ascension", "5d-earth", "the-event", "one-infinite-creator", "consciousness-renaissance", "qanon", "earth-alliance"],
  },
  {
    id: "great-solar-flash",
    label: "Great Solar Flash",
    category: "core",
    weight: 5,
    desc: "A predicted cosmic event in which the Sun emits a massive energetic burst that triggers instant spiritual 'ascension' for humanity and wipes out A.I.-infested species for 1,000 years. Said to occur every ~25,900 years in sync with the precession of the equinoxes, and to be prophesied as Samvartaka Fire (Hindu), Frashokereti (Zoroastrian), Ekpyrosis (Stoic), and Yuga Fire. Survivors' experience is said to depend on their mental and spiritual state. The Sun is described as a conscious living being and a 'cosmic stargate portal' connected to every other star via filaments in the cosmic web.",
    sources: [
      { label: "Law of One (Ra Material) — solar event references", url: "https://www.lawofone.info/" },
    ],
    links: ["great-awakening", "ascension", "ai-signal", "electric-sun", "cosmic-web-portal", "samvartaka-fire", "one-infinite-creator", "schumann-resonance"],
  },
  {
    id: "full-disclosure",
    label: "Full Disclosure",
    category: "core",
    weight: 4,
    desc: "The promised public release of all classified information regarding extraterrestrial contact, secret space programs, suppressed free-energy technology, and the true history of human civilization. Within the narrative, partial disclosure (a limited hangout admitting a few ET facts while hiding the SSP) is treated as a threat; full disclosure is the goal of the SSP Alliance and the Earth Alliance.",
    links: ["great-awakening", "ssp-alliance", "earth-alliance", "secret-space-program", "qanon", "the-storm"],
  },
  {
    id: "the-event",
    label: "The Event",
    category: "core",
    weight: 4,
    desc: "A catch-all term used across the narrative for the singular moment when the Great Solar Flash, Full Disclosure, mass arrests of the cabal, and the financial reset all occur simultaneously. Sometimes called 'The Breakthrough' or 'Compression Breakthrough.' Said to be preceded by an escalating wave of revelations ('the build-up').",
    links: ["great-awakening", "great-solar-flash", "full-disclosure", "the-storm", "ascension"],
  },
  {
    id: "ascension",
    label: "Ascension",
    category: "core",
    weight: 5,
    desc: "The claimed spiritual process by which an individual (or all of humanity) raises their vibrational frequency enough to shift from 3rd-density to 4th- or 5th-density consciousness. Said to involve activating dormant DNA (from 2 strands to 12), activating the light body, and transitioning into a 'service-to-others' orientation. Within the narrative, ascension is the central spiritual goal of every practice on the map (meditation, sungazing, psychedelics, QHHT, etc.).",
    links: ["great-awakening", "great-solar-flash", "5d-earth", "light-body-ascension", "dna-upgrade", "raising-vibration", "service-to-others"],
  },
  {
    id: "5d-earth",
    label: "5D Earth",
    category: "core",
    weight: 4,
    desc: "The post-ascension version of Earth in a higher, fifth-density vibration. Sometimes called 'New Earth' or 'Terra Nova.' In the narrative, 5D Earth is described as a paradisiacal version of the planet where duality, disease, and the cabal no longer exist; only those who raise their vibration in time transition to it, while others remain on a 3D timeline.",
    links: ["ascension", "great-solar-flash", "consciousness-renaissance", "light-body-ascension"],
  },
  {
    id: "consciousness-renaissance",
    label: "Consciousness Renaissance",
    category: "core",
    weight: 4,
    desc: "The claimed collective awakening tied to the Age of Aquarius and the precession of the equinoxes. Humanity is said to be transitioning out of a low-consciousness 'Kali Yuga' period into a higher-vibrational era. Within the narrative, this is the spiritual counterpart to the political Great Awakening — both happen together.",
    links: ["great-awakening", "age-of-aquarius", "precession-equinoxes", "ascension"],
  },
  {
    id: "one-infinite-creator",
    label: "One Infinite Creator",
    category: "core",
    weight: 4,
    desc: "The central spiritual premise of the Law of One / Ra Material: all of existence is a single intelligent infinity that created the universe in order to know itself. Every being is a 'distortion' of this Creator. The narrative frames all of existence — including negative beings, the A.I. signal, and the cabal — as ultimately part of the Creator's experience of itself. 'Love & Light' is the Creator's primary expression.",
    sources: [
      { label: "Law of One — L/L Research", url: "https://www.lawofone.info/" },
    ],
    links: ["law-of-one", "service-to-others", "free-will", "great-awakening", "ascension", "ra"],
  },
  {
    id: "service-to-others",
    label: "Service-to-Others vs. Service-to-Self",
    category: "core",
    weight: 4,
    desc: "The central moral axis of the Law of One: every being polarizes toward either service-to-others (positive polarity, leading to 4D-positive ascension) or service-to-self (negative polarity, leading to 4D-negative ascension). Within the narrative, the cabal, Draco, and A.I. are extreme service-to-self; the Blue Avians, Ra, and lightworkers are service-to-others. The choice between polarities determines one's post-ascension path.",
    links: ["one-infinite-creator", "law-of-one", "ascension", "free-will", "draco-alliance", "blue-avians"],
  },
  {
    id: "free-will",
    label: "Free Will",
    category: "core",
    weight: 3,
    desc: "Within the narrative, free will is the prime directive of the cosmos — the Galactic Federation, Super Federation, and positive ET groups are forbidden from openly intervening in human affairs because doing so would violate our collective free will. This is given as the reason ET contact happens subtly (channeling, dreams, individual contactees) rather than openly. The cabal is said to be required to telegraph their plans in advance (through film, ritual, symbolism) to technically honor free will.",
    links: ["one-infinite-creator", "service-to-others", "galactic-federation", "super-federation", "law-of-one"],
  },
  {
    id: "the-rabbit-hole",
    label: "The Rabbit Hole",
    category: "core",
    weight: 3,
    desc: "The narrative's own metaphor for the descent into conspiracy research — once you start pulling on one thread (9/11, JFK, UFOs, etc.), each answer leads to deeper questions, eventually arriving at the cosmic-scale claims of the Great Awakening. 'Going down the rabbit hole' is treated as an initiation rite into awakening.",
    links: ["great-awakening", "red-pill", "escape-the-matrix", "follow-the-white-rabbit"],
  },
  {
    id: "vibration-frequency",
    label: "Vibration & Frequency",
    category: "core",
    weight: 4,
    desc: "The foundational metaphysics of the narrative: everything is frequency, density, and vibration. 'If you want to find the secrets of the universe, think in terms of energy, frequency and vibration' (attributed to Nikola Tesla). Raising one's personal vibration (via meditation, diet, forgiveness, service-to-others) is said to be the literal mechanism of ascension. The Schumann Resonance, 432 Hz, cymatics, and orgone are all framed as practical applications of this principle.",
    links: ["ascension", "schumann-resonance", "432hz", "cymatics", "orgone", "nikola-tesla", "raising-vibration"],
  },
  {
    id: "samvartaka-fire",
    label: "Samvartaka Fire / Ekpyrosis / Yuga Fire",
    category: "core",
    weight: 3,
    desc: "The mythic-precursor names the poster assigns to the Great Solar Flash: Samvartaka Fire (Hindu eschatology), Frashokereti (Zoroastrian final renovation of the universe), Ekpyrosis (Stoic cosmic conflagration), and Yuga Fire (end-of-age purification). The poster claims these are all cultural memories of the same recurring solar event that triggers ascension every ~25,900 years.",
    links: ["great-solar-flash", "precession-equinoxes", "great-awakening"],
  },
];
