import type { GAMNode } from "./types";

// EXTRATERRESTRIAL / GALACTIC — federations, races, councils, channeled beings
export const ET_NODES: GAMNode[] = [
  {
    id: "galactic-federation",
    label: "Galactic Federation",
    category: "et",
    weight: 5,
    desc: "A supposed alliance of advanced, primarily 6th-density extraterrestrial civilizations overseeing Earth's development. Within the narrative, the Federation operates under a strict non-interference / free-will directive, assists humanity's spiritual ascension from behind the scenes, and is composed of multiple races including Pleiadians, Nordics, Blue Avians, and others. Concept originates in 1950s–70s contactee literature (George Van Tassel, George Adamski) and is central to the modern SSP narrative.",
    sources: [
      { label: "Galactic Federation — Wikipedia", url: "https://en.wikipedia.org/wiki/Galactic_Federation" },
    ],
    links: ["sphere-being-alliance", "super-federation", "pleiadians", "blue-avians", "ra", "law-of-one", "service-to-others", "great-awakening"],
  },
  {
    id: "super-federation",
    label: "Super Federation (Genetic Farmer Races)",
    category: "et",
    weight: 4,
    desc: "Described as a separate, larger council of 4th- and 5th-density 'genetic farmer races' (60+ groups) who have been running 22 simultaneous ET-human genetic experiments on Earth for hundreds of thousands of years. Within the narrative, humanity is treated as their genetic stock. The Super Federation is said to have been 'disbanded' by the Sphere Being Alliance / Galactic Federation around 2016–2018, with the 22 genetic experiments ordered to cease.",
    links: ["galactic-federation", "sphere-being-alliance", "22-et-experiments", "ancient-builder-race", "corey-goode"],
  },
  {
    id: "sphere-being-alliance",
    label: "Sphere Being Alliance",
    category: "et",
    weight: 5,
    desc: "Described as a group of 6th–9th-density beings who arrived in the solar system around 2011–2012 via giant blue spheres (hence the name) to buffer the energies of the Great Solar Flash and assist Earth's ascension. Within the narrative, the Sphere Being Alliance is the most advanced positive faction ever to intervene in human affairs, working through Corey Goode as their messenger. Composed of three groups: the Blue Avians, the Golden Triangle-Head Beings, and the Blue Orb/Sphere beings.",
    links: ["corey-goode", "blue-avians", "golden-triangle-beings", "galactic-federation", "great-solar-flash", "ra", "law-of-one"],
  },
  {
    id: "blue-avians",
    label: "Blue Avians",
    category: "et",
    weight: 4,
    desc: "Described as 6th-density, bird-like (avian) beings of pure light, eight feet tall, with indigo-blue feathers. Within the narrative, the Blue Avians are one of the three Sphere Being Alliance factions and the primary communicators with Corey Goode. Their messages emphasize: raise your vibration, become more loving, forgive yourself and others, serve others, and stop obsessing over the cabal/drama. They are described as 'Ra of the Law of One' in a different form.",
    links: ["sphere-being-alliance", "corey-goode", "ra", "law-of-one", "galactic-federation"],
  },
  {
    id: "golden-triangle-beings",
    label: "Golden Triangle-Head Beings",
    category: "et",
    weight: 2,
    desc: "The second of the three Sphere Being Alliance factions: described as 8-foot-tall beings with a triangular head (no facial features), made of golden light, communicating entirely telepathically. Within the narrative, these beings rarely interact with humans directly and are considered the most advanced of the three Sphere Being factions.",
    links: ["sphere-being-alliance", "blue-avians", "corey-goode"],
  },
  {
    id: "ra",
    label: "Ra (Law of One)",
    category: "et",
    weight: 4,
    desc: "A 6th-density 'social memory complex' that channeled the Law of One material through Carla Rueckert, Don Elkins, and Jim McCarty in 1981–84. Within the narrative, Ra is described as having originated as part of the Ancient Builder Race on Venus ~1.3 billion years ago, then later walked among the ancient Egyptians as the deity Ra. The Blue Avians are said to be Ra returning in a different form. The Ra Material is treated as the foundational spiritual text of the entire Great Awakening narrative.",
    sources: [
      { label: "Law of One — Full text online", url: "https://www.lawofone.info/" },
    ],
    links: ["law-of-one", "sphere-being-alliance", "blue-avians", "venus", "ancient-builder-race", "egyptian-ra"],
  },
  {
    id: "ra-teir-eir",
    label: "Ra-Teir-Eir",
    category: "et",
    weight: 2,
    desc: "The specific Ra social memory complex representative that Corey Goode reports meeting in encounters with the Sphere Being Alliance. Within the narrative, Ra-Teir-Eir communicates the Blue Avian / Ra messages directly to Goode and is described as a 6th-density being of light.",
    links: ["ra", "sphere-being-alliance", "corey-goode", "law-of-one"],
  },
  {
    id: "law-of-one",
    label: "The Law of One (Ra Material)",
    category: "spiritual",
    weight: 5,
    desc: "A five-volume channeled text (1981–84) dictated by the entity Ra through Carla Rueckert of L/L Research. Describes the cosmos as a single intelligent infinity experiencing itself through 'distortions' (free will, love, light), with eight densities of consciousness. The central principle: 'All is One.' Treated within the narrative as the single most important spiritual text of the Great Awakening. The Law of One is the source of the density model (3D→4D→5D→...) used throughout the map.",
    sources: [
      { label: "Law of One — Full text online", url: "https://www.lawofone.info/" },
    ],
    links: ["ra", "one-infinite-creator", "service-to-others", "ascension", "densities", "sphere-being-alliance", "david-wilcock"],
  },
  {
    id: "bashar",
    label: "Bashar (Essassani)",
    category: "et",
    weight: 3,
    desc: "A channeled being named Bashar, described as a 4th-density extraterrestrial from the planet Essassani (a 'hybrid race' of human and grey genetics), channeled publicly by Darryl Anka since 1983. Bashar's teachings emphasize 'following your excitement' as the highest guide to action, the multi-verse as a holographic construct, and the imminent open contact between humanity and ET civilizations. Within the narrative, Bashar is treated as a respected channeler of Essassani wisdom.",
    sources: [
      { label: "Bashar (Darryl Anka) — Wikipedia", url: "https://en.wikipedia.org/wiki/Darryl_Anka" },
    ],
    links: ["galactic-federation", "greys", "channeling", "ascension", "hybrid-races"],
  },
  {
    id: "pleiadians",
    label: "Pleiadians",
    category: "et",
    weight: 4,
    desc: "Described as a Nordic-looking, 5th-density human civilization from the Pleiades star cluster (especially the planet Erra in the Taygeta system). Within the narrative, Pleiadians are our closest cosmic cousins, share ancestry with humanity, and have been the most active positive ET group in guiding Earth — through channelers (Billy Meier, Barbara Marciniak) and embedded operatives. Said to have provided guidance to William Tompkins and to the Earth Alliance.",
    sources: [
      { label: "Billy Meier — Wikipedia", url: "https://en.wikipedia.org/wiki/Billy_Meier" },
    ],
    links: ["galactic-federation", "nordics", "william-tompkins", "channeling", "earth-alliance"],
  },
  {
    id: "nordics",
    label: "Nordics (Tall Whites)",
    category: "et",
    weight: 3,
    desc: "A category of ET beings described as tall, blonde, blue-eyed, Scandinavian-looking humans. Within the narrative, Nordics include Pleiadians, Venusians, and 'Tall Whites' (the Charles Hall testimony). Said to be the most human-looking ETs and the most likely to walk among us undetected. Some factions are described as positive (Pleiadians), others as working with the cabal.",
    sources: [
      { label: "Nordic aliens — Wikipedia", url: "https://en.wikipedia.org/wiki/Nordic_aliens" },
    ],
    links: ["pleiadians", "nazi-breakaway", "william-tompkins", "galactic-federation"],
  },
  {
    id: "greys",
    label: "Greys",
    category: "et",
    weight: 3,
    desc: "The most widely reported ET type: small, hairless, large-headed beings with black almond eyes. Within the narrative, Greys are divided into multiple subgroups — short 'drone' greys (biological robots), taller 'EBE' greys, and 'tall greys.' Said to be involved in abduction programs, sometimes on behalf of the Draco, sometimes (the 'Essassani' descendants) as positive hybrids. Described as a dying clone race dependent on human genetic material.",
    sources: [
      { label: "Grey alien — Wikipedia", url: "https://en.wikipedia.org/wiki/Grey_alien" },
    ],
    links: ["ebes", "draco-alliance", "hybrid-races", "milab", "bashar"],
  },
  {
    id: "ebes",
    label: "EBEs (Talls / Drones)",
    category: "et",
    weight: 2,
    desc: "EBE = Extraterrestrial Biological Entity. Within the narrative, the term refers to the various Grey subtypes recovered from crashes (the Roswell EBE-1, EBE-2, EBE-3) and to the larger Grey hierarchy: 'Talls' (8-foot-tall Grey leaders) and 'Drones' (short biological-robot worker Greys).",
    links: ["greys", "draco-alliance", "reverse-engineering-ufos", "mj12"],
  },
  {
    id: "mantids",
    label: "Mantids",
    category: "et",
    weight: 3,
    desc: "Described as 7–9-foot-tall insectoid beings resembling praying mantises. Within the narrative, Mantids are described as a high-intelligence, high-density race often present (as observers) during MILAB abductions and Grey abductions. Said to operate in a 'multidimensional' capacity and to be involved in the genetic experiments overseen by the Super Federation.",
    sources: [
      { label: "Insectoid aliens — Wikipedia", url: "https://en.wikipedia.org/wiki/Reptilians#Insectoids" },
    ],
    links: ["greys", "super-federation", "milab", "draco-alliance"],
  },
  {
    id: "reptilians",
    label: "Reptilians",
    category: "et",
    weight: 5,
    desc: "Central antagonists of the narrative, popularized by David Icke. Described as 7-foot-tall bipedal reptilian beings who can shapeshift into human form, hold positions of power on Earth (royalty, banking, government), and feed on human fear ('loosh'). Within the SSP narrative, Reptilians are a subjugate race — infested and controlled by the A.I. signal, allied with the Draco. Said to have arrived on Earth ~5,000 years ago and manipulated human civilization since.",
    sources: [
      { label: "Reptilians — Wikipedia", url: "https://en.wikipedia.org/wiki/Reptilians" },
    ],
    links: ["draco-alliance", "ai-signal", "reptilians-nanite", "david-icke", "loosh", "cabal"],
  },
  {
    id: "draco-alliance",
    label: "Draco & Reptilian Alliance",
    category: "et",
    weight: 4,
    desc: "The overarching name for the negative-polarity reptilian power structure: the Draco (described as 7–12-foot-tall royal-winged reptilians at the top) leading the Reptilians, Greys, and Mantid subgroups. Said to be allied with Dark Fleet, the Orion Syndicate, and the cabal. Within the narrative, the Draco-Alliance has controlled Earth for ~5,000 years, treats humanity as a slave/livestock species, and is being dismantled by the Sphere Being Alliance and the SSP Alliance.",
    links: ["reptilians", "dark-fleet", "orion-syndicate", "cabal", "ai-signal", "service-to-others"],
  },
  {
    id: "orion-syndicate",
    label: "Orion Syndicate",
    category: "et",
    weight: 3,
    desc: "Within the narrative, a negative-polarity collective of service-to-self ET races based in the Orion star system. In the Law of One, the 'Orion group' is described as the primary negative-polarity influence on Earth, channeling their propaganda to those seeking power over others. Said to work with the Draco Alliance and the cabal. The term 'Orion Syndicate' is also borrowed from Star Trek by SSP researchers.",
    links: ["draco-alliance", "reptilians", "law-of-one", "service-to-others", "cabal"],
  },
  {
    id: "annunaki",
    label: "Annunaki",
    category: "et",
    weight: 4,
    desc: "Sumerian deities ('those who from heaven to earth came') reinterpreted by Zecharia Sitchin as actual extraterrestrials from the planet Nibiru who came to Earth ~450,000 years ago to mine gold, genetically engineered humanity as a slave race by splicing their DNA with Homo erectus, and ruled as the 'gods' of ancient civilizations. Within the narrative, the Annunaki are the origin point of the cabal's bloodlines and the genetic manipulation that the Super Federation later took over.",
    sources: [
      { label: "Anunnaki — Wikipedia", url: "https://en.wikipedia.org/wiki/Anunnaki" },
      { label: "Zecharia Sitchin — Wikipedia", url: "https://en.wikipedia.org/wiki/Zecharia_Sitchin" },
    ],
    links: ["ancient-builder-race", "nibiru", "super-federation", "world-gold-heist", "ancient-aliens"],
  },
  {
    id: "nibiru",
    label: "Nibiru / Planet X",
    category: "et",
    weight: 3,
    desc: "A supposed additional planet in our solar system with a 3,600-year elliptical orbit, home of the Annunaki per Zecharia Sitchin. Within the narrative, Nibiru's return is variously described as: a cover story for the Great Solar Flash, a physical planet visible soon, or a 4D object invisible to 3D instruments. The 'Planet X' panic of the 2010s is treated as a partial distortion of this concept.",
    sources: [
      { label: "Nibiru — Wikipedia", url: "https://en.wikipedia.org/wiki/Nibiru_cataclysm" },
    ],
    links: ["annunaki", "great-solar-flash", "ancient-aliens"],
  },
  {
    id: "council-of-saturn",
    label: "Council of Saturn",
    category: "et",
    weight: 3,
    desc: "From the Law of One: a 6th-density council that meets inside a 'time-bubble sanctuary' on Saturn, serving as a meeting zone and administrative body for our local sector of the galaxy. Within the narrative, the Council of Saturn manages soul-reincarnation decisions for Earth and oversees the quarantine around our planet.",
    links: ["ra", "law-of-one", "saturn", "ancient-builder-race"],
  },
  {
    id: "22-et-experiments",
    label: "22 ET/Human Genetic Experiments",
    category: "et",
    weight: 3,
    desc: "Within the narrative, the Super Federation of 60+ 'genetic farmer races' has been running 22 simultaneous genetic experiments on humanity for hundreds of thousands of years, mixing their DNA into ours. Corey Goode reports that the Sphere Being Alliance ordered these experiments to cease and the Super Federation 'disbanded' around 2016–2018, freeing humanity from being treated as genetic stock.",
    links: ["super-federation", "sphere-being-alliance", "annunaki", "ancient-builder-race", "corey-goode"],
  },
  {
    id: "hybrid-races",
    label: "Hybrid Races",
    category: "et",
    weight: 3,
    desc: "Within the narrative, multiple ET-human hybrid races have been created — including the Essassani (Bashar's race, a Grey-human hybrid), and various Pleiadian-human and Nordic-human hybrids. Hybridization programs are described as ongoing, sometimes coercive (Grey abductions), sometimes cooperative. Said to be the source of the 'star children' and 'indigos' born on Earth.",
    links: ["bashar", "greys", "super-federation", "star-children", "22-et-experiments"],
  },
  {
    id: "inner-earth-civilizations",
    label: "Inner Earth Civilizations (Agartha)",
    category: "et",
    weight: 4,
    desc: "Within the narrative, multiple civilizations live in enormous cavern-habitats inside the hollow/honeycomb Earth — including the Anshar (Corey Goode's reported inner-Earth hosts, described as 4D humans who are our future descendants who time-traveled back), the Agarthans, and others. Said to predate surface humanity, possess advanced crystalline technology, and have their own Antarctic/Arctic entrances. The 'Hollow Honeycomb Earth' model is invoked to explain how they fit.",
    sources: [
      { label: "Hollow Earth — Wikipedia", url: "https://en.wikipedia.org/wiki/Hollow_Earth" },
    ],
    links: ["agartha", "antarctica", "ancient-builder-race", "corey-goode", "tibet-tunnels"],
  },
  {
    id: "agartha",
    label: "Agartha / Shambhala",
    category: "et",
    weight: 3,
    desc: "The legendary inner-Earth kingdom, paired with its capital Shambhala (or Shangri-La). Within the narrative, Agartha is the political capital of the inner-Earth civilizations, said to be accessible via the North and South Pole openings and via tunnels beneath Tibet, Egypt, and the Andes. Described as a 4D-positive civilization that will emerge after the Great Solar Flash.",
    links: ["inner-earth-civilizations", "tibet-tunnels", "ancient-builder-race", "ascension"],
  },
  {
    id: "black-wedge-craft",
    label: "Black Wedge & Pumpkin Seed Craft",
    category: "et",
    weight: 2,
    desc: "Within the narrative, the characteristic craft shapes used by Dark Fleet and Draco forces — large black triangular ('wedge') craft and elongated 'pumpkin seed' shaped antigravity vessels. The TR-3B is described as a MICSSP knockoff of these designs.",
    links: ["dark-fleet", "tr3b", "draco-alliance", "secret-space-program"],
  },
  {
    id: "oumuamua",
    label: "'Oumuamua",
    category: "et",
    weight: 3,
    desc: "A real interstellar object that passed through the solar system in 2017. Within the narrative, 'Oumuamua is described as an 18,000-year-old Ancient Builder Race derelict ship that entered through the outer energetic barrier of the solar system, was intercepted by the SSP Alliance in 2018, and was covered up by mainstream astronomy. Avi Loeb's arguments that it could be artificial are cited as partial confirmation.",
    sources: [
      { label: "'Oumuamua — Wikipedia", url: "https://en.wikipedia.org/wiki/%CA%BBOumuamua" },
    ],
    links: ["ancient-builder-race", "ssp-alliance", "secret-space-program"],
  },
  {
    id: "ringmakers-saturn",
    label: "Ringmakers of Saturn",
    category: "et",
    weight: 3,
    desc: "Based on the 1986 book 'Ringmakers of Saturn' by Norman Bergrun (a former NASA Ames scientist). Bergrun argued that Voyager imagery of Saturn's rings shows enormous cylindrical 'EMVs' (electro-magnetic vehicles), miles long, actively manufacturing the rings. Within the narrative, these are Ancient Builder Race constructs, and the rings are described as 'ruins for 70-foot-tall giants.'",
    sources: [
      { label: "Ringmakers of Saturn (PDF archive)", url: "https://www.bibliotecapleyades.net/ciencia/ciencia_ringmakers.htm" },
    ],
    links: ["ancient-builder-race", "saturn", "nasa-coverup", "70ft-giants"],
  },
  {
    id: "iapetus",
    label: "Iapetus (Death Star Moon)",
    category: "et",
    weight: 3,
    desc: "A real moon of Saturn with an unusual 20-km-high equatorial ridge, giving it a 'walnut' shape. Within the narrative, Iapetus is described as the 'ancient Death Star' — an artificial spherical construct built by the Ancient Builder Race, with the equatorial ridge being the seam of its construction. Richard C. Hoagland popularized this idea.",
    sources: [
      { label: "Iapetus — Wikipedia", url: "https://en.wikipedia.org/wiki/Iapetus_(moon)" },
    ],
    links: ["ancient-builder-race", "saturn", "ringmakers-saturn", "nasa-coverup"],
  },
  {
    id: "70ft-giants",
    label: "70-Foot-Tall Giants",
    category: "et",
    weight: 2,
    desc: "Within the narrative, the Ancient Builder Race and various pre-human civilizations included giant beings up to 70 feet tall. Their ruins (and skeletons) are said to exist on the Moon, Mars, and Saturn's rings, and to have been systematically hidden by Smithsonian/NASA cover-ups on Earth.",
    links: ["ancient-builder-race", "ringmakers-saturn", "nasa-coverup", "ancient-aliens"],
  },
  {
    id: "mohammed-treaty",
    label: "Mohammed Treaty (~AD 800)",
    category: "et",
    weight: 2,
    desc: "Within the narrative, a treaty allegedly signed around AD 800 between human leadership and the Draco-Reptilian alliance, allowing the Draco to operate on Earth (underground bases, certain surface interactions) in exchange for not openly conquering the surface. Said to be the legal basis the Draco still cite for their presence on Earth.",
    links: ["draco-alliance", "reptilians", "secret-space-program", "free-will"],
  },
  {
    id: "channeling",
    label: "Channeling",
    category: "et",
    weight: 4,
    desc: "The claimed reception of information from non-physical beings (Ra, Bashar, Pleiadians, Blue Avians, ascended masters, etc.) via a human channeler in an altered state of consciousness. Within the narrative, channeling is the primary mode of communication between positive ET groups and humanity, given the non-interference / free-will directive. Major channelers include Carla Rueckert (Ra), Darryl Anka (Bashar), Barbara Marciniak (Pleiadians), and David Wilcock.",
    links: ["ra", "bashar", "pleiadians", "blue-avians", "law-of-one", "david-wilcock"],
  },
  {
    id: "david-wilcock",
    label: "David Wilcock",
    category: "et",
    weight: 4,
    desc: "A central figure in the modern SSP / ascension narrative — author, researcher, and self-described channeler of the Ra Material's modern continuation. Wrote 'The Source Field Investigations' and 'The Synchronicity Key,' was the host of Gaia's 'Cosmic Disclosure' with Corey Goode, and is described within the narrative as the modern inheritor of the Edgar Cayce lineage (Cayce being his claimed past-life incarnation).",
    sources: [
      { label: "David Wilcock — Wikipedia", url: "https://en.wikipedia.org/wiki/David_Wilcock" },
    ],
    links: ["cosmic-disclosure", "corey-goode", "law-of-one", "ra", "ssp-researchers", "channeling"],
  },
  {
    id: "david-icke",
    label: "David Icke",
    category: "et",
    weight: 3,
    desc: "British author who popularized the Reptilian-shapeshifter narrative beginning in the 1990s with 'The Biggest Secret.' Within the SSP / Great Awakening narrative, Icke is treated as a primary source on Reptilian infiltration of human power structures, the loosh-harvesting model, and the Saturn-Moon matrix. Some SSP researchers consider Icke partially accurate but incomplete (he doesn't include the SSP or the A.I. signal).",
    sources: [
      { label: "David Icke — Wikipedia", url: "https://en.wikipedia.org/wiki/David_Icke" },
    ],
    links: ["reptilians", "loosh", "saturn-moon-matrix", "ssp-researchers"],
  },
  {
    id: "dr-steven-greer",
    label: "Dr. Steven Greer",
    category: "ssp",
    weight: 3,
    desc: "Emergency physician and UFO researcher who founded the Disclosure Project (2001) and the CE5 (Close Encounters of the 5th Kind) protocol for civilian-initiated ET contact. Within the narrative, Greer is a primary public advocate for full disclosure, though SSP researchers critique him for not including the SSP / Draco aspects. His 2017 'Unacknowledged' documentary and 2023 'The Lost Century' are widely cited.",
    sources: [
      { label: "Steven Greer — Wikipedia", url: "https://en.wikipedia.org/wiki/Steven_M._Greer" },
    ],
    links: ["full-disclosure", "ssp-researchers", "secret-space-program", "channeling"],
  },
  {
    id: "michael-salla",
    label: "Dr. Michael Salla",
    category: "ssp",
    weight: 3,
    desc: "Author and founder of the Exopolitics Institute, who systematized the academic-style study of the SSP through books like 'Insiders Reveal Secret Space Programs' and 'Antarctica's Hidden History.' Within the narrative, Salla is the primary 'scholarly' voice synthesizing the SSP testimony of Tompkins, Goode, Penny Bradley, and others.",
    sources: [
      { label: "Michael Salla — Wikipedia", url: "https://en.wikipedia.org/wiki/Michael_Salla" },
    ],
    links: ["secret-space-program", "william-tompkins", "corey-goode", "ssp-researchers", "antarctica"],
  },
  {
    id: "richard-hoagland",
    label: "Richard C. Hoagland",
    category: "ssp",
    weight: 3,
    desc: "Former NASA consultant and author of 'Dark Mission' (with Mike Bara). Popularized the 'Face on Mars,' Cydonia pyramids, the '19.5°' geometry, Iapetus-as-Death-Star, and hyperdimensional physics theories. Within the narrative, Hoagland is treated as a primary source on NASA cover-ups and the ancient ruins across the solar system.",
    sources: [
      { label: "Richard C. Hoagland — Wikipedia", url: "https://en.wikipedia.org/wiki/Richard_C._Hoagland" },
    ],
    links: ["face-on-mars", "cydonia-pyramids", "iapetus", "19.5", "nasa-dark-mission", "nasa-coverup"],
  },
  {
    id: "saturn-moon-matrix",
    label: "Saturn-Moon Matrix (Icke)",
    category: "et",
    weight: 3,
    desc: "David Icke's claim that Saturn and the Moon are used as a giant broadcasting system — Saturn generating a frequency that the Moon amplifies and beams at Earth — to trap human consciousness in a low-vibration 'matrix' / 3D-reality loop. Within the broader narrative, this overlaps with the 'Moon is a soul-catcher' (John Lear) claim and the A.I. signal's electromagnetic-field habitation.",
    links: ["david-icke", "moon-soul-catcher", "artificial-moon", "ai-signal", "saturn", "moon"],
  },
  {
    id: "galactic-un",
    label: "Galactic U.N.",
    category: "et",
    weight: 2,
    desc: "Within the narrative, a diplomatic zone on the Moon (within the Lunar Operations Command) where multiple ET civilizations and SSP factions meet under UN-style protocols. Described as the political/diplomatic counterpart to the Super Federation's genetic-experiment council.",
    links: ["loc", "secret-space-program", "super-federation", "global-galactic-league"],
  },
];
