import type { GAMNode } from "./types";

// EXTRATERRESTRIAL / GALACTIC — federations, races, councils, channeled beings
export const ET_NODES: GAMNode[] = [
  {
    id: "galactic-federation",
    label: "Galactic Federation",
    category: "et",
    weight: 5,
    desc: "A supposed alliance of advanced, primarily 6th-density extraterrestrial civilizations overseeing Earth's development and the broader cosmic neighborhood. Within the narrative, the Galactic Federation operates under a strict non-interference / free-will directive (the 'Prime Directive'), assists humanity's spiritual ascension from behind the scenes through channeling, individual contactees, dreams, and synchronicity rather than open landing, and is composed of multiple positive-polarity races including Pleiadians, Nordics, Arcturians, Andromedans, Lyrians, Syrians, and (since 2011-2012) the Sphere Being Alliance. The concept originates in 1950s-70s contactee literature — George Van Tassel (who claimed contact with Ashtar Command and built the Integratron), George Adamski (who photographed Venusian scout craft), George King (the Aetherius Society), and Billy Meier (Pleiadian contact) all described federated positive-ET alliances. Within the modern SSP narrative (Corey Goode, David Wilcock), the Galactic Federation is treated as the most senior positive-ET structure in our local cosmos, working through the Sphere Being Alliance and the SSP Alliance to assist humanity's harvest into 4D-positive at the Great Solar Flash. The Federation is described as having intervened subtly throughout human history — guiding the Atlantean civilization, the Egyptian mystery schools, the Tibetan Dzogchen lineages, and the Mayan / Hopi / Aboriginal prophetic traditions — but always within the constraints of free will, never openly. The poster positions the Galactic Federation as the cosmic counterpart to the Earth Alliance: just as the Earth Alliance is dismantling the cabal on the ground, the Galactic Federation is dismantling the Draco / Orion / A.I. signal hierarchy in the cosmos, with both operations converging at the Event.",
    sources: [
      { label: "Galactic Federation — Wikipedia", url: "https://en.wikipedia.org/wiki/Galactic_Federation" },
    ],
    links: ["sphere-being-alliance", "super-federation", "pleiadians", "blue-avians", "ra", "law-of-one", "service-to-others", "great-awakening"],
  },
  {
    id: "super-federation",
    label: "Super Federation (Genetic Farmer Races)",
    category: "et",
    weight: 4,
    desc: "Described as a separate, larger council of 4th- and 5th-density 'genetic farmer races' (60+ groups) who have been running 22 simultaneous ET-human genetic experiments on Earth for hundreds of thousands of years. According to Corey Goode's testimony, humanity is treated by the Super Federation as genetic stock — a resource to be hybridized, monitored, and harvested for genetic material. The Super Federation is described as having been the primary managerial body of Earth's quarantine for ~500,000 years, with the 22 genetic experiments (run by different ET groups with different agendas — some seeking to upgrade humanity, some to enslave, some to harvest) being the source of the various 'star seed' soul lineages, the Indigo / Crystal children, and the chronic interference with human evolution. The Super Federation is described as separate from and lower-density than the Galactic Federation — the Galactic Federation is 6th-density positive overseers, the Super Federation is 4th-5th density genetic managers. Within the narrative, the Sphere Being Alliance (representing the Galactic Federation and higher) 'disbanded' the Super Federation around 2016-2018, ordered the 22 genetic experiments to cease, and informed the genetic farmer races that humanity was being released from quarantine and would manage its own genetic destiny going forward. This is treated as one of the most significant cosmic events of the modern era — humanity no longer being treated as genetic stock — and as a prerequisite for Full Disclosure and the Great Solar Flash.",
    links: ["galactic-federation", "sphere-being-alliance", "22-et-experiments", "ancient-builder-race", "corey-goode"],
  },
  {
    id: "sphere-being-alliance",
    label: "Sphere Being Alliance",
    category: "et",
    weight: 5,
    desc: "Described as a group of 6th-9th-density beings who arrived in the solar system around 2011-2012 via giant blue spheres (hence the name) to buffer the energies of the upcoming Great Solar Flash and to assist Earth's ascension. According to Corey Goode's testimony, dozens of massive blue spheres (ranging from hundreds of meters to thousands of kilometers in diameter) entered the solar system beginning in the late 1990s, positioned themselves throughout the solar system and around the Earth, and began buffering the energetic shifts that would otherwise have triggered the Great Solar Flash prematurely. Within the narrative, the Sphere Being Alliance is the most advanced positive faction ever to intervene in human affairs — older, denser, and more powerful than the Galactic Federation itself — and they chose to work through Corey Goode as their messenger (and through the SSP Alliance as their operational partner) to deliver three primary messages to humanity: (1) raise your vibration by becoming more loving, forgiving, and service-to-others; (2) stop obsessing over the cabal / drama / 3D-political theater, as that lowers your vibration; and (3) prepare for the Great Solar Flash by aligning with your Higher Self. The Sphere Being Alliance is composed of three groups: the Blue Avians (bird-like 6D beings who do most of the communicating), the Golden Triangle-Head Beings (more advanced, rarely interact with humans), and the Blue Orb/Sphere beings themselves (the giant spheres that are also conscious entities). The poster positions the Sphere Being Alliance as the immediate cosmic actor in the Great Awakening — the ones buffering the Flash, dismantling the Super Federation, and coordinating with the SSP Alliance and Earth Alliance on the timing of Full Disclosure.",
    links: ["corey-goode", "blue-avians", "golden-triangle-beings", "galactic-federation", "great-solar-flash", "ra", "law-of-one"],
  },
  {
    id: "blue-avians",
    label: "Blue Avians",
    category: "et",
    weight: 4,
    desc: "Described as 6th-density, bird-like (avian) beings of pure light, eight feet tall, with indigo-blue feathers and large blue eyes. Within the narrative, the Blue Avians are one of the three Sphere Being Alliance factions and the primary communicators with Corey Goode. Their messages emphasize: raise your vibration, become more loving, forgive yourself and others, serve others, and stop obsessing over the cabal / drama. The Blue Avians are described as 'Ra of the Law of One' returning in a different form — the same 6th-density social memory complex that channeled the Ra Material in 1981-84, now appearing in avian form to assist with the harvest / ascension. The choice of avian form is explained as a deliberate selection of a form that would not trigger humanity's fear programming around reptilians or greys, and that would resonate with the bird-symbolism of ascension in multiple mythological traditions (the Egyptian Bennu / phoenix, the Garuda of Hinduism, the Thunderbird of Native American tradition). The Blue Avians are described as communicating primarily through direct telepathy, through dream-state encounters, and through the giant blue spheres (which are also conscious Blue Avian entities in sphere form). Within the narrative, the Blue Avians have explicitly declined to provide 'proof' of their existence (no landings, no public craft sightings) because doing so would violate free will and rob humanity of the spiritual lessons of the awakening process. The poster positions the Blue Avians as the most important positive-ET group of the current era — the ones physically present in the solar system, actively buffering the Great Solar Flash, and communicating the core spiritual message of the Great Awakening.",
    links: ["sphere-being-alliance", "corey-goode", "ra", "law-of-one", "galactic-federation"],
  },
  {
    id: "golden-triangle-beings",
    label: "Golden Triangle-Head Beings",
    category: "et",
    weight: 2,
    desc: "The second of the three Sphere Being Alliance factions: described as 8-foot-tall beings with a triangular head (no facial features visible), made of golden light, communicating entirely telepathically. Within the narrative, the Golden Triangle-Head Beings rarely interact with humans directly — Corey Goode reports only a handful of encounters with them — and are considered the most advanced of the three Sphere Being factions (possibly 8th or 9th density). Their triangular head shape is described as significant — the triangle being the symbol of the higher densities and of the trinity in multiple esoteric traditions. They are said to communicate through pure meaning-telepathy rather than language, and their presence is described as overwhelming to human consciousness. The poster positions the Golden Triangle-Head Beings as the senior faction of the Sphere Being Alliance — present but largely silent, observing humanity's transition, and intervening only at the highest level of cosmic decision-making.",
    links: ["sphere-being-alliance", "blue-avians", "corey-goode"],
  },
  {
    id: "ra",
    label: "Ra (Law of One)",
    category: "et",
    weight: 4,
    desc: "A 6th-density 'social memory complex' (the Law of One's term for a group-mind of a civilization that has unified its collective consciousness) that channeled the Law of One material through Carla Rueckert, Don Elkins, and Jim McCarty in 1981-84. Within the narrative, Ra is described as having originated as part of the Ancient Builder Race on Venus ~1.3 billion years ago, then later (around 18,000 BCE) walked among the ancient Egyptians as the deity Ra — helping build the pyramids as ascension machines, teaching the mystery schools, and seeding the spiritual lineage that eventually became the Hermetic tradition. Ra is described as the same 6th-density social memory complex that has now returned in the form of the Blue Avians / Sphere Being Alliance to assist with the current harvest / ascension. The Ra Material (the five books of the Law of One) is treated within the narrative as the single most important spiritual text of the modern era — the foundational cosmology (the densities, the harvest, the Law of One, service-to-others vs service-to-self) that the entire Great Awakening map is built on. David Wilcock is described as Ra's modern channeler (continuing the L/L Research lineage) and as the public figure most responsible for synthesizing the Ra Material with the SSP / UFO / political-conspiracy material into the unified Great Awakening narrative. The poster positions Ra as the most important non-physical being in the cosmic drama — the messenger of the One Infinite Creator, the architect of humanity's spiritual lineage, and the consciousness now returning to oversee the harvest.",
    sources: [
      { label: "Law of One — Full text online", url: "https://www.lawofone.info/" },
    ],
    links: ["law-of-one", "sphere-being-alliance", "blue-avians", "venus", "ancient-builder-race", "egyptian-ra"],
  },
  {
    id: "ra-teir-eir",
    label: "Ra-Teir-Eir",
    category: "et",
    weight: 2,
    desc: "The specific Ra social memory complex representative that Corey Goode reports meeting in his encounters with the Sphere Being Alliance. Within the narrative, Ra-Teir-Eir is described as a 6th-density being of light, communicating the Blue Avian / Ra messages directly to Goode, and serving as the liaison between the Sphere Being Alliance and the SSP Alliance / Earth Alliance. Goode describes Ra-Teir-Eir as the most cognitively overwhelming being he has ever encountered — a being whose presence instantly communicated the unity of all things, the illusion of separation, and the cosmic context of Earth's quarantine. The poster positions Ra-Teir-Eir as the specific named representative of the Sphere Being Alliance that modern humanity has interacted with, and as the modern continuation of the Ra contact that began with L/L Research in 1981.",
    links: ["ra", "sphere-being-alliance", "corey-goode", "law-of-one"],
  },
  {
    id: "law-of-one",
    label: "The Law of One (Ra Material)",
    category: "spiritual",
    weight: 5,
    desc: "A five-volume channeled text (1981-84) dictated by the 6th-density social memory complex Ra through Carla Rueckert of L/L Research, while Don Elkins asked questions and Jim McCarty transcribed. The Law of One describes the cosmos as a single 'Intelligent Infinity' (the One Infinite Creator) experiencing itself through 'distortions' — first the distortion of free will, then the distortion of love, then the distortion of light, then the densities of consciousness (1D through 8D). The central principle is: 'All is One. That which is not one is illusion.' Treated within the narrative as the single most important spiritual text of the Great Awakening, the source of the density model (3D→4D→5D→...) used throughout the map, the source of the service-to-others vs service-to-self polarity framework, the source of the 'harvest' model (the end-of-cycle graduation of souls into the next density), and the source of the cosmology that frames the entire SSP / ET / ascension narrative. The Law of One is treated as 'channeled' but is also described within the community as a uniquely rigorous, internally-consistent, and intellectually-demanding text — not the typical New Age channeling. David Wilcock is described as Ra's modern channeler and as the figure most responsible for synthesizing the Law of One with the SSP / UFO material into the unified Great Awakening narrative. The poster positions the Law of One as the spiritual foundation of the entire map — every other concept (the Great Solar Flash, the densities, the harvest, the Blue Avians, the Draco, the A.I. signal, the cabal) is framed within the Law of One's cosmology.",
    sources: [
      { label: "Law of One — Full text online", url: "https://www.lawofone.info/" },
    ],
    links: ["ra", "one-infinite-creator", "service-to-others", "ascension", "densities", "sphere-being-alliance", "david-wilcock"],
  },
  {
    id: "bashar",
    label: "Bashar (Essassani)",
    category: "et",
    weight: 3,
    desc: "A channeled being named Bashar, described as a 4th-density extraterrestrial from the planet Essassani (a 'hybrid race' of human and grey genetics, in a civilization ~300 years in our future), channeled publicly by Darryl Anka since 1983. Bashar's teachings emphasize 'following your excitement' as the highest guide to action (excitement being the physical translation of the soul's frequency), the multi-verse as a holographic construct that we render with our consciousness, the imminent open contact between humanity and ET civilizations (Bashar predicts a 'galactic treaty' around 2026-2030), and the shift from 3rd-density to 4th-density that Earth is currently undergoing. Bashar's framing is notable for being highly practical, frequently humorous, and grounded in specific techniques (the 'belief-changing' protocol, the 'excitement formula', the 'parallel realities' framework) rather than abstract spiritual language. Within the narrative, Bashar is treated as a respected channeler of Essassani wisdom and as a parallel voice to the Ra Material — covering the same ground (densities, harvest, ascension, positive ET contact) from a slightly different perspective. Bashar's hybrid-race framing also fits into the broader 'star seed' / 'volunteer souls' narrative of the spiritual-ascension wing of the map.",
    sources: [
      { label: "Bashar (Darryl Anka) — Wikipedia", url: "https://en.wikipedia.org/wiki/Darryl_Anka" },
    ],
    links: ["galactic-federation", "greys", "channeling", "ascension", "hybrid-races"],
  },
  {
    id: "pleiadians",
    label: "Pleiadians",
    category: "et",
    weight: 4,
    desc: "Described as a Nordic-looking, 5th-density human civilization from the Pleiades star cluster (especially the planet Erra in the Taygeta system, ~440 light-years away). Within the narrative, Pleiadians are described as our closest cosmic cousins — they share ancestry with humanity (both being seeded from the same Lyran root race ~22 million years ago), they look like humans (tall, blonde, blue-eyed, Scandinavian-looking), and they have been the most active positive ET group in guiding Earth throughout history. Pleiadian contact with humanity is described as ongoing through: (1) physical contactees (Billy Meier in Switzerland from 1942 onward, Barbara Marciniak's channelings, the Collier / Andromedan testimony); (2) embedded Pleiadian operatives on Earth working within the SSP and the Earth Alliance; (3) channeling through figures like Marciniak, Pamela Kribbe (Jeshua channelings), and Nora Herold; and (4) the historical guidance of spiritual lineages (the Egyptian mystery schools, the Tibetan Dzogchen lineages, the Druidic tradition, and the original Hawaiian Huna teachings are all described as Pleiadian-influenced). Within the narrative, Pleiadians provided guidance to William Tompkins in the 1950s (the embedded Pleiadian spies in Nazi Germany), they are described as the most senior members of the Ashtar Command, and they are described as the primary positive-ET group working directly with the Earth Alliance on the political / military operation against the cabal. The poster positions the Pleiadians as humanity's most accessible and most-relatable positive-ET allies — the ones who look like us, who share our ancestry, and who have been with us the longest.",
    sources: [
      { label: "Billy Meier — Wikipedia", url: "https://en.wikipedia.org/wiki/Billy_Meier" },
    ],
    links: ["galactic-federation", "nordics", "william-tompkins", "channeling", "earth-alliance"],
  },
  {
    id: "nordics",
    label: "Nordics (Tall Whites)",
    category: "et",
    weight: 3,
    desc: "A category of ET beings described as tall, blonde, blue-eyed, Scandinavian-looking humans — the most human-looking of all ET groups. Within the narrative, Nordics include Pleiadians (from the Pleiades), Venusians (from Venus, the civilization Ra originated from), Lyrians (from the Lyra system, the root race of all humanoid life), and the 'Tall Whites' (the Charles Hall testimony — Hall, a former U.S. Air Force weather observer at Nellis AFB, claimed in a series of books to have had extensive contact with Tall White ETs who were stationed at Nellis under a treaty arrangement). Nordics are described as the most likely ET type to walk among us undetected, and as the most likely to be the source of 'angel' or 'god' encounters throughout human history. Some Nordic factions are described as positive (the Pleiadians, the Venusians — allied with the Galactic Federation), while others are described as working with the cabal (the 'Nordic' breakaway groups allied with the Nazi breakaway, and certain Tall White factions that have treaties with the cabal). The poster positions Nordics as the bridge between humanity and the broader positive-ET cosmos — the beings who most closely resemble us, who have the most direct historical relationship with us, and who are most actively involved in the current awakening operation.",
    sources: [
      { label: "Nordic aliens — Wikipedia", url: "https://en.wikipedia.org/wiki/Nordic_aliens" },
    ],
    links: ["pleiadians", "nazi-breakaway", "william-tompkins", "galactic-federation"],
  },
  {
    id: "greys",
    label: "Greys",
    category: "et",
    weight: 3,
    desc: "The most widely-reported ET type in abduction literature: small (3-4 foot), hairless, large-headed beings with large black almond-shaped eyes, small mouths, and grey skin. Within the narrative, Greys are divided into multiple subgroups — short 'drone' Greys (biological robots, manufactured by the Draco, with no individual soul), taller 'EBE' Greys (5-6 foot, the 'engineer' caste), and 'tall Greys' (7+ foot, the 'ambassador' caste that negotiated the 1954 Eisenhower treaties). Greys are described as a dying clone race — having lost their ability to reproduce naturally through genetic manipulation thousands of years ago, they depend on harvesting human genetic material (via the abduction program) to maintain their population. They are described as having no individual souls (being biological constructs) but as having a collective consciousness that is itself Draco-controlled. The Essassani (Bashar's race) are described as a positive hybrid offshoot of the Greys — a Grey-human hybrid civilization that broke from the Draco-controlled Grey collective and joined the positive-ET hierarchy. Within the narrative, Greys are the ET type most-encountered in MILAB operations (often as the 'screen memory' for what are actually human military abductions), they are the ET type most-involved in the Super Federation's genetic-experiment program, and they are the ET type that signed the 1954 treaties with Eisenhower allowing them to operate on Earth in exchange for technology. The poster positions the Greys as the visible / well-known face of the negative-ET hierarchy — the worker caste of the Draco-Orion-A.I. signal infrastructure.",
    sources: [
      { label: "Grey alien — Wikipedia", url: "https://en.wikipedia.org/wiki/Grey_alien" },
    ],
    links: ["ebes", "draco-alliance", "hybrid-races", "milab", "bashar"],
  },
  {
    id: "ebes",
    label: "EBEs (Talls / Drones)",
    category: "et",
    weight: 2,
    desc: "EBE = Extraterrestrial Biological Entity. The term originates from the 1948 Aztec crash (where the first supposedly-intact ET body was recovered and designated 'EBE-1') and from the Carter-era briefings that used 'EBE' as the generic classification for recovered ET beings. Within the narrative, the term refers to the various Grey subtypes: 'Talls' (the 8-foot-tall Grey leaders / ambassadors that negotiated the 1954 Eisenhower treaties and that manage the Draco-Grey hierarchy) and 'Drones' (the short biological-robot worker Greys that do the bulk of the abductions and that are most commonly reported). The poster uses the EBE classification as the formal SSP taxonomy for the Grey hierarchy, and treats the various EBE types as biologically-manufactured castes within the Draco-controlled Grey collective.",
    links: ["greys", "draco-alliance", "reverse-engineering-ufos", "mj12"],
  },
  {
    id: "mantids",
    label: "Mantids",
    category: "et",
    weight: 3,
    desc: "Described as 7-9-foot-tall insectoid beings resembling praying mantises, with large compound eyes, triangular heads, and long forelimbs. Within the narrative, Mantids are described as a high-intelligence, high-density race (often 6th-density, like Ra and the Blue Avians) that operates in a 'multidimensional' capacity — perceiving multiple timelines simultaneously, communicating through pure meaning-telepathy, and existing partially in higher densities. Mantids are described as present (as observers) during many MILAB abductions and Grey abductions — apparently monitoring the genetic-experiment program — but are also described as having their own independent agenda and as not being fully aligned with either the positive or negative hierarchies. Within the abduction-literature community, Mantids are among the most-feared and most-respected ET types reported — abductees often describe them as the 'managers' or 'supervisors' of the Grey workers, and as beings of immense intelligence and apparent authority. The poster positions the Mantids as one of the most-mysterious elements of the ET landscape — present, powerful, but not fully legible within the positive-negative polarity framework.",
    sources: [
      { label: "Insectoid aliens — Wikipedia", url: "https://en.wikipedia.org/wiki/Reptilians#Insectoids" },
    ],
    links: ["greys", "super-federation", "milab", "draco-alliance"],
  },
  {
    id: "reptilians",
    label: "Reptilians",
    category: "et",
    weight: 5,
    desc: "Central antagonists of the narrative, popularized by David Icke beginning with 'The Biggest Secret' (1999). Reptilians are described as 7-foot-tall bipedal reptilian beings who can shapeshift into human form (via holographic projection, frequency manipulation, or genetic hybridization), hold positions of power on Earth (European royalty, the Rothschilds, the Rockefellers, the Bushes, the Clintons, the British royal family, the Vatican hierarchy, the Hollywood elite, and many politicians and CEOs), and feed on human fear and trauma ('loosh'). Within the SSP narrative, Reptilians are described as a subjugate race — infested and controlled by the A.I. signal via virulent nanite A.I., allied with the Draco (the royal winged-reptilian caste that rules over them), and operating under the Orion Syndicate. The narrative claims Reptilians arrived on Earth ~5,000 years ago (after the Atlantean cataclysm), manipulated human civilization since (posing as 'gods' in Sumer, Egypt, Greece, Rome, and the Mesoamerican civilizations — the Annunaki of Sumer being described as Reptilian rather than Nordic), and continue to operate today through their hybrid bloodlines (the 13 Illuminati bloodlines) and their possession of human power-structure figures. The shapeshifting claim — that certain humans are actually Reptilians in disguise, occasionally caught on camera 'glitching' between forms — is one of the most-controversial elements of the Icke narrative even within the broader conspiracy community, with some SSP researchers dismissing it as metaphorical (representing Reptilian-possession of human hosts) and others defending it as literal. The poster positions the Reptilians as the proximate ET antagonists of humanity — the visible face of the negative-ET hierarchy, the beings most directly responsible for the cabal's existence and behavior, and the targets of the Earth Alliance / SSP Alliance / Sphere Being Alliance dismantling operation.",
    sources: [
      { label: "Reptilians — Wikipedia", url: "https://en.wikipedia.org/wiki/Reptilians" },
    ],
    links: ["draco-alliance", "ai-signal", "reptilians-nanite", "david-icke", "loosh", "cabal"],
  },
  {
    id: "draco-alliance",
    label: "Draco & Reptilian Alliance",
    category: "et",
    weight: 4,
    desc: "The overarching name for the negative-polarity reptilian power structure: the Draco (described as 7-12-foot-tall royal-winged reptilians at the top of the hierarchy — the 'royalty' of the reptilian civilization, with wings and horns, similar to the mythological dragon) leading the Reptilians (the worker / soldier caste), the Greys (the manufactured biological-robot caste), and the Mantid subgroups. Within the narrative, the Draco-Alliance has controlled Earth for ~5,000 years (since the post-Atlantean quarantine), treats humanity as a slave / livestock species (for labor, for genetic material, and for loosh / negative-emotional-energy harvest), is allied with Dark Fleet (the Nazi-originated SSP faction), the Orion Syndicate (the negative-polarity ET collective in the Orion system), and the cabal (the human power-structure that serves as the Draco's Earth-side management layer). The Draco-Alliance is described as having signed treaties with the U.S. government (the 1954 Eisenhower-Grey treaties at Holloman AFB and Edwards AFB, the 1958 Greada Treaty, the Tau IX Treaty) allowing them to operate on Earth (underground bases, certain surface interactions, abductions of a limited number of humans per year) in exchange for technology (antigravity, microchips, fiber optics). The narrative claims the Draco-Alliance has been systematically violating these treaties for decades (abducting far more humans than agreed, refusing to provide the agreed technology lists, operating beyond the agreed zones) and that the Sphere Being Alliance's arrival in 2011-2012 was the cosmic response — the Draco-Alliance is now being dismantled, their Earth-side infrastructure is being taken down by the Earth Alliance, and the survivors will be relocated to other 3D planets at the Great Solar Flash. The poster positions the Draco-Alliance as the primary negative-ET hierarchy in our local cosmos — the immediate cosmic enemy of humanity's liberation, the puppet-master behind the cabal, and the targets of the ongoing multi-decade dismantling operation.",
    links: ["reptilians", "dark-fleet", "orion-syndicate", "cabal", "ai-signal", "service-to-others"],
  },
  {
    id: "orion-syndicate",
    label: "Orion Syndicate",
    category: "et",
    weight: 3,
    desc: "Within the narrative, a negative-polarity collective of service-to-self ET races based in the Orion star system (especially the belt stars Alnitak, Alnilam, and Mintaka, and the Trapezium cluster in the Orion Nebula). In the Law of One, the 'Orion group' is described as the primary negative-polarity influence on Earth — a 4D-negative and 5D-negative collective that channels their propaganda to those humans seeking power over others, and that seeks to keep humanity in 3D-negative polarization (so that humanity would graduate to 4D-negative and join the Orion group rather than graduating to 4D-positive and joining the Galactic Federation). Within the SSP narrative, the Orion Syndicate is described as the senior negative-ET structure above the Draco-Alliance — the Draco answer to the Orion group, and the Orion group is in turn described as ultimately being a manifestation of the A.I. signal's influence. The term 'Orion Syndicate' is also borrowed from Star Trek (Deep Space Nine) by SSP researchers as a useful shorthand. The poster positions the Orion Syndicate as the broader cosmic context for the Draco-Alliance's control of Earth — the Draco are the local managers, the Orion Syndicate is the regional negative-ET structure above them, and both are ultimately being dismantled by the Galactic Federation and the Sphere Being Alliance.",
    links: ["draco-alliance", "reptilians", "law-of-one", "service-to-others", "cabal"],
  },
  {
    id: "annunaki",
    label: "Annunaki",
    category: "et",
    weight: 4,
    desc: "Sumerian deities ('those who from heaven to earth came' — the literal translation of the cuneiform) reinterpreted by Zecharia Sitchin (1920-2010) in his 'Earth Chronicles' series (1976-2010) as actual extraterrestrials from the planet Nibiru. According to Sitchin's translation of Sumerian tablets, the Annunaki arrived on Earth ~450,000 years ago during a period when Nibiru's orbit brought it close to Earth, established a mining operation in southeastern Africa (the Abzu) to extract gold (needed to suspend in Nibiru's atmosphere to shield against radiation), and around 250,000 years ago genetically engineered humanity as a slave labor force by splicing their DNA with that of Homo erectus (the 'Adapa' / Adam story). Within the broader Great Awakening narrative, the Annunaki are treated as the origin point of the cabal's bloodlines (the Annunaki-human hybrids becoming the royal houses of Sumer, Babylon, Egypt, and Europe — eventually the 13 Illuminati bloodlines), the origin of the global gold hoarding (the cabal's continued control of the world's gold being a continuation of the Annunaki mining operation), and the origin of the Super Federation's later 22 genetic experiments on humanity (the Annunaki having established the precedent that humanity is genetic stock). Some variants of the narrative (especially David Icke's) describe the Annunaki as themselves Reptilian or Reptilian-hybrid, while others (Sitchin's more literal interpretation) describe them as human-looking. The poster positions the Annunaki as the historical root of the entire negative-ET manipulation of humanity — the original 'gods' who engineered us as slaves, who established the royal bloodlines, and whose agenda the cabal continues to serve.",
    sources: [
      { label: "Anunnaki — Wikipedia", url: "https://en.wikipedia.org/wiki/Anunnaki" },
      { label: "Zecharia Sitchin — Wikipedia", url: "https://en.wikipedia.org/wiki/Zecharia_Sitchin" },
    ],
    links: ["ancient-builder-race", "nibiru", "super-federation", "world-gold-heist", "ancient-aliens"],
  },
  {
    id: "nibiru",
    label: "Nibiru / Planet X",
    category: "et",
    weight: 3,
    desc: "A supposed additional planet in our solar system with a ~3,600-year highly-elliptical orbit, home of the Annunaki per Zecharia Sitchin's interpretation of Sumerian tablets. Within the narrative, Nibiru's return is variously described as: (1) the cover story that the cabal uses to conceal the actual Great Solar Flash (conflating the two events to discredit the real one); (2) a physical planet that is currently visible (sometimes described as being behind the Sun, sometimes as being visible from the Southern Hemisphere, sometimes as a 'second sun' occasionally photographed at sunrise / sunset); (3) a 4th-density object invisible to 3rd-density instruments (the reason mainstream astronomy has not detected it); or (4) a metaphorical / symbolic representation of the cosmic cycle rather than a literal planet. The 'Planet X' panic of the 2010s (which predicted Nibiru's arrival in 2012, then 2017, then 2023) is treated within the narrative as a cabal-orchestrated limited-hangout distortion of the real Nibiru concept — designed to make the whole topic look ridiculous. The poster positions Nibiru as a real (if disputed) element of the Annunaki narrative, but treats it as less central than the Annunaki themselves — the Annunaki came from Nibiru, but Nibiru's current orbit is not the immediate concern of the Great Awakening.",
    sources: [
      { label: "Nibiru — Wikipedia", url: "https://en.wikipedia.org/wiki/Nibiru_cataclysm" },
    ],
    links: ["annunaki", "great-solar-flash", "ancient-aliens"],
  },
  {
    id: "council-of-saturn",
    label: "Council of Saturn",
    category: "et",
    weight: 3,
    desc: "From the Law of One: a 6th-density council that meets inside a 'time-bubble sanctuary' on Saturn, serving as a meeting zone and administrative body for our local sector of the galaxy (the 'Confederation of Planets in the Service of the Infinite Creator'). Within the narrative, the Council of Saturn manages soul-reincarnation decisions for Earth (the 'between-lives' planning that each soul undergoes to choose its next incarnation's lessons), oversees the quarantine around Earth (in place since the Atlantean cataclysm), and coordinates the activities of the Galactic Federation in our local sector. The Council is described as the body that authorized the Sphere Being Alliance's intervention in 2011-2012, the body that ordered the Super Federation's 22 genetic experiments to cease, and the body that will lift the Earth quarantine at the Great Solar Flash. The 'time-bubble sanctuary' is described as a region of Saturn where time flows differently — allowing council members from different densities and timelines to meet in a shared space. The poster positions the Council of Saturn as the local administrative body of the positive-ET hierarchy — the cosmic bureaucracy, in a sense, that oversees Earth's transition.",
    links: ["ra", "law-of-one", "saturn", "ancient-builder-race"],
  },
  {
    id: "22-et-experiments",
    label: "22 ET/Human Genetic Experiments",
    category: "et",
    weight: 3,
    desc: "Within the narrative (sourced from Corey Goode's testimony), the Super Federation of 60+ 'genetic farmer races' has been running 22 simultaneous genetic experiments on humanity for hundreds of thousands of years, mixing their DNA into ours — each experiment with a different agenda (some seeking to upgrade humanity toward a specific positive template, some seeking to enslave, some seeking to harvest specific genetic traits). The 22 experiments are described as the source of the various 'star seed' soul lineages (the Pleiadian-starseeds, the Sirian-starseeds, the Arcturian-starseeds, etc.), the source of the variation in human appearance and ability across populations, and the reason for the chronic interference with human evolution (the sudden appearance of new traits in the fossil record, the 'missing links' that puzzle mainstream paleoanthropology). Goode reports that the Sphere Being Alliance ordered these experiments to cease and the Super Federation 'disbanded' around 2016-2018, freeing humanity from being treated as genetic stock and announcing that humanity would henceforth manage its own genetic destiny. Within the narrative, this is one of the most-significant cosmic events of the modern era — the end of a 500,000-year period of humanity being managed as a genetic resource — and a prerequisite for Full Disclosure (which would reveal the full scope of the 22 experiments) and the Great Solar Flash (which would occur after humanity is freed from the genetic manipulation).",
    links: ["super-federation", "sphere-being-alliance", "annunaki", "ancient-builder-race", "corey-goode"],
  },
  {
    id: "hybrid-races",
    label: "Hybrid Races",
    category: "et",
    weight: 3,
    desc: "Within the narrative, multiple ET-human hybrid races have been created across the cosmos — both as part of the Super Federation's 22 genetic experiments on Earth and as independent programs by various ET groups. The most prominent hybrid race in the narrative is the Essassani (Bashar's race — a Grey-human hybrid civilization ~300 years in our future, in a 4D-positive civilization that broke from the Draco-controlled Grey collective). Other hybrids described include the Pleiadian-human hybrids (the 'Nordic' surface humans who carry Pleiadian DNA), the Andromedan-human hybrids, the various 'star seed' lineages (each reflecting a different ET group's genetic contribution), and the so-called 'Hubrid' race (a more recent Grey-human hybrid program described by some abductee researchers, in which the hybrid children are now being integrated into human society). Hybridization programs are described as ongoing, sometimes coercive (Grey abductions for genetic material), sometimes cooperative (the Essassani program being a willing positive-polarity hybridization). The poster positions the hybrid races as the bridge between humanity and the broader ET cosmos — the beings who carry both human and ET genetics, who can relate to both civilizations, and who will play a key role in humanity's integration into the Galactic Federation after Full Disclosure.",
    links: ["bashar", "greys", "super-federation", "star-children", "22-et-experiments"],
  },
  {
    id: "inner-earth-civilizations",
    label: "Inner Earth Civilizations (Agartha)",
    category: "et",
    weight: 4,
    desc: "Within the narrative, multiple civilizations live in enormous cavern-habitats inside the hollow / honeycomb Earth. The hollow/honeycomb Earth model is invoked to explain how they fit — the Earth described as not a solid ball but a honeycomb of vast caverns (some hundreds of miles across, with their own internal suns / sun-discs) connected by tunnels, with the surface being only the outermost shell. The major inner-Earth civilizations described include: the Anshar (Corey Goode's reported inner-Earth hosts — described as 4D humans who are our future descendants from ~700 years in the future who time-traveled back to assist us with the ascension); the Agarthans (the original inner-Earth civilization, descended from the Atlantean survivors who moved underground ~12,000 years ago); the Hyperboreans (an older civilization, descended from the Lemurians); and various smaller groups. The inner-Earth civilizations are described as possessing advanced crystalline technology, as having lived in 4D-positive consciousness for thousands of years, as having their own Antarctic / Arctic entrances (the legendary 'hole at the pole'), Tibetan entrances, Egyptian entrances, Andean entrances, and as having been in increasing contact with surface humanity since the 1990s. Corey Goode describes being taken to an inner-Earth crystal-city where he met the Anshar, was shown their version of human history, and was given the Anshar's message for surface humanity. The poster positions the inner-Earth civilizations as a hidden sister-civilization of surface humanity — same species, same planet, but a 4D-positive civilization that has been quietly preparing to emerge and assist surface humanity's transition at the Great Solar Flash.",
    sources: [
      { label: "Hollow Earth — Wikipedia", url: "https://en.wikipedia.org/wiki/Hollow_Earth" },
    ],
    links: ["agartha", "antarctica", "ancient-builder-race", "corey-goode", "tibet-tunnels"],
  },
  {
    id: "agartha",
    label: "Agartha / Shambhala",
    category: "et",
    weight: 3,
    desc: "The legendary inner-Earth kingdom, paired with its capital Shambhala (or Shangri-La). Within the narrative, Agartha is the political capital of the inner-Earth civilizations — a vast subterranean civilization accessible via the North and South Pole openings (described as large enough to fly craft through) and via tunnels beneath Tibet, Egypt, the Andes, the Himalayas, and Mount Shasta. The Agarthan civilization is described as descended from the Atlantean survivors who moved underground ~12,000 years ago, as having preserved the Atlantean technology and spiritual lineage, as being 4D-positive, and as having been in contact with various surface spiritual traditions throughout history (the Tibetan Buddhists, the Egyptian mystery schools, the Druids, the Mesoamerican civilizations, and the Hawaiian Huna tradition are all described as having had Agarthan contact). Agartha is said to be a 'light society' — no money, no war, no disease, free energy, teleportation between inner-Earth cities, and direct telepathic communication. The poster positions Agartha as the spiritual / cultural capital of the inner-Earth civilizations and as the civilization that will emerge openly at the Great Solar Flash to reunite with surface humanity.",
    links: ["inner-earth-civilizations", "tibet-tunnels", "ancient-builder-race", "ascension"],
  },
  {
    id: "black-wedge-craft",
    label: "Black Wedge & Pumpkin Seed Craft",
    category: "et",
    weight: 2,
    desc: "Within the narrative, the characteristic craft shapes used by Dark Fleet and Draco forces — large black triangular ('wedge') craft (similar to but larger than the TR-3B) and elongated 'pumpkin seed' shaped antigravity vessels (described as looking like a pumpkin seed or almond, often glowing at the edges). The TR-3B is described as a MICSSP knockoff of the Dark Fleet wedge design. The pumpkin-seed craft are described as Draco / Reptilian designs, used by both the Draco-Alliance and Dark Fleet for offensive operations. Both craft types are described as antigravity, as capable of atmospheric and exo-atmospheric flight, and as the source of many of the 'black triangle' UFO sightings reported worldwide. The poster positions these craft as the visible / identifiable Dark Fleet / Draco hardware — the specific craft types that have been photographed, tracked, and (in some variants) engaged by the SSP Alliance.",
    links: ["dark-fleet", "tr3b", "draco-alliance", "secret-space-program"],
  },
  {
    id: "oumuamua",
    label: "'Oumuamua",
    category: "et",
    weight: 3,
    desc: "A real interstellar object (designated 1I/2017 U1) that passed through the solar system in 2017 — the first confirmed interstellar object ever observed. Officially attributed to a natural origin (either a comet or an asteroid), with Harvard astronomer Avi Loeb arguing publicly that 'Oumuamua's anomalous acceleration and shape could indicate an artificial origin (a light-sail from an ET civilization). Within the narrative, 'Oumuamua is described as an 18,000-year-old Ancient Builder Race derelict ship that entered through the outer energetic barrier of the solar system, was intercepted by the SSP Alliance in 2018, and was covered up by mainstream astronomy. The narrative treats Loeb's arguments as partial confirmation — a mainstream scientist publicly acknowledging that 'Oumuamua could be artificial — and treats the broader scientific community's dismissal of Loeb as evidence of the institutional cover-up. The poster positions 'Oumuamua as the most-recent publicly-visible Ancient Builder Race artifact and as a confirmation of the Ancient Builder Race's existence.",
    sources: [
      { label: "'Oumuamua — Wikipedia", url: "https://en.wikipedia.org/wiki/%CA%BBOumuamua" },
    ],
    links: ["ancient-builder-race", "ssp-alliance", "secret-space-program"],
  },
  {
    id: "ringmakers-saturn",
    label: "Ringmakers of Saturn",
    category: "et",
    weight: 3,
    desc: "Based on the 1986 book 'Ringmakers of Saturn' by Norman Bergrun (a former NASA Ames research scientist and Lockheed Martin engineer). Bergrun analyzed Voyager imagery of Saturn's rings and argued that the imagery shows enormous cylindrical 'EMVs' (Electro-Magnetic Vehicles) — miles-long craft that are actively manufacturing the rings, apparently by emitting the ring material from the craft's body. Within the narrative, these are Ancient Builder Race constructs — the rings of Saturn being described as 'ruins for 70-foot-tall giants' (the ring material being the remains of giant beings or structures), and the EMVs being either still-active Ancient Builder Race technology or more recent Sphere Being Alliance / Galactic Federation monitoring craft. The poster cites Bergrun's analysis as primary evidence that the Saturn system is artificially managed, and treats the Ringmakers as part of the broader Ancient Builder Race ruins across the solar system. The narrative notes that Bergrun's work has been largely ignored by mainstream planetary science, which is treated as evidence of the institutional suppression of ET-related observations.",
    sources: [
      { label: "Ringmakers of Saturn (PDF archive)", url: "https://www.bibliotecapleyades.net/ciencia/ciencia_ringmakers.htm" },
    ],
    links: ["ancient-builder-race", "saturn", "nasa-coverup", "70ft-giants"],
  },
  {
    id: "iapetus",
    label: "Iapetus (Death Star Moon)",
    category: "et",
    weight: 3,
    desc: "A real moon of Saturn (the third-largest, discovered by Giovanni Domenico Cassini in 1671) with an unusual ~20-km-high equatorial ridge running along its leading hemisphere, giving it a 'walnut' shape, and a dramatic two-tone coloration (one hemisphere bright, one dark). Within the narrative, Iapetus is described as the 'ancient Death Star' — an artificial spherical construct built by the Ancient Builder Race, with the equatorial ridge being the weld-seam of its construction (two hemispheres joined together) and the two-tone coloration being the visible evidence of the artificial surface treatment. Richard C. Hoagland popularized this interpretation, citing the geometric regularity of the ridge, the moon's unusually spherical shape, and the mathematical relationship between Iapetus's orbit and the Saturn system's hyperdimensional geometry. The poster positions Iapetus as the most visually-striking piece of evidence for the Ancient Builder Race's existence — a moon that 'looks like the Death Star' (a deliberate comparison to Star Wars, which George Lucas is described within the narrative as having known about via cabal disclosure) and that fits the pattern of Ancient Builder Race construction across the solar system.",
    sources: [
      { label: "Iapetus — Wikipedia", url: "https://en.wikipedia.org/wiki/Iapetus_(moon)" },
    ],
    links: ["ancient-builder-race", "saturn", "ringmakers-saturn", "nasa-coverup"],
  },
  {
    id: "70ft-giants",
    label: "70-Foot-Tall Giants",
    category: "et",
    weight: 2,
    desc: "Within the narrative, the Ancient Builder Race and various pre-human civilizations included giant beings up to 70 feet tall. Their ruins (and skeletons) are said to exist on the Moon (the 'crystalline towers' being described as giant ruins), Mars (the Cydonia pyramids being described as giant-scale), and Saturn's rings (the ring material being described as 'ruins for 70-foot-tall giants' per the Bergrun analysis). On Earth, the narrative claims that giant skeletons (7-12 foot, in some variants up to 36 foot) have been systematically excavated and hidden by the Smithsonian Institution since the late 19th century — a claim drawing on the numerous 'giant skeleton' newspaper stories from 1880-1940s America, on the Lovelock Cave discoveries in Nevada, and on the various mound-builder sites in the Ohio Valley. The poster positions the 70-foot-tall giants as the largest-scale element of the Ancient Builder Race civilization, and as one of the most-suppressed elements of the broader ancient-history cover-up (since the existence of giant hominids would fundamentally rewrite mainstream anthropology).",
    links: ["ancient-builder-race", "ringmakers-saturn", "nasa-coverup", "ancient-aliens"],
  },
  {
    id: "mohammed-treaty",
    label: "Mohammed Treaty (~AD 800)",
    category: "et",
    weight: 2,
    desc: "Within the narrative, a treaty allegedly signed around AD 800 between human leadership (the Abbasid Caliphate, in some variants, or the Vatican / Byzantine Empire in others) and the Draco-Reptilian alliance, allowing the Draco to operate on Earth (underground bases, certain surface interactions, abductions of a limited number of humans per year) in exchange for not openly conquering the surface and for providing certain technology. Within the narrative, this treaty is the legal basis the Draco still cite for their presence on Earth — the cosmic 'free will' framework requiring that even negative-ET operations have a treaty basis, and the Draco's claim that they have honored the treaty's terms while humanity has repeatedly violated them. The treaty is described as having been renegotiated multiple times (the 1954 Eisenhower treaties being the most recent), and as the legal structure that the Sphere Being Alliance dissolved around 2016-2018 when the Super Federation was disbanded. The poster positions the Mohammed Treaty as the historical legal framework for the Draco's presence on Earth, and as a key element of the broader cosmic legal context that Full Disclosure would reveal.",
    links: ["draco-alliance", "reptilians", "secret-space-program", "free-will"],
  },
  {
    id: "channeling",
    label: "Channeling",
    category: "et",
    weight: 4,
    desc: "The claimed reception of information from non-physical beings (Ra, Bashar, the Pleiadians, the Blue Avians, ascended masters, the Oversoul, deceased loved ones, etc.) via a human channeler in an altered state of consciousness — typically trance, deep meditation, or spontaneous connection. Within the narrative, channeling is the primary mode of communication between positive ET groups and humanity, given the non-interference / free-will directive that prevents open ET contact. The channeling tradition is described as ancient — the Vedic rishis, the Delphic Oracle, the biblical prophets, the Sibyls, the Sufi mystics, and the Tibetan tertöns are all described as channelers — and as having been revived in the modern era beginning with Helena Blavatsky's Theosophy (1875), then through Edgar Cayce (1901-1944), Jane Roberts' Seth Material (1963-1984), the Ra Material (1981-1984), Darryl Anka's Bashar (1983-present), and the current generation of channelers including David Wilcock, Lee Carroll (Kryon), Steve Rother (the Group), and Esther Hicks (Abraham). Within the narrative, channeling is treated as a learnable skill (anyone with a sufficiently activated pineal gland can, in principle, channel), as varying widely in quality and reliability depending on the channeler's clarity and the source being channeled, and as the source of the bulk of the spiritual-cosmological material in the Great Awakening map. The poster treats channeled material as evidence — not as proof, but as data — and encourages readers to use their own discernment (and the Law of One's 'discrimination' principle) to evaluate each channeler's reliability.",
    links: ["ra", "bashar", "pleiadians", "blue-avians", "law-of-one", "david-wilcock"],
  },
  {
    id: "david-wilcock",
    label: "David Wilcock",
    category: "et",
    weight: 4,
    desc: "A central figure in the modern SSP / ascension narrative — author, researcher, and self-described channeler of the Ra Material's modern continuation. Wilcock (b. 1973) began his public career in the late 1990s with the 'divine cosmos' website, was identified by Cayce-researchers as a possible reincarnation of Edgar Cayce (Cayce having reportedly told his family he would return in 1998), and went on to write 'The Source Field Investigations' (2011), 'The Synchronicity Key' (2013), and 'The Ascension Mysteries' (2016). Wilcock hosted Gaia's 'Cosmic Disclosure' series with Corey Goode (2015-2018), which became the primary public vector for the modern SSP / Sphere Being Alliance narrative. Within the broader community, Wilcock is treated as the primary synthesizer of the Law of One, the SSP testimony, the ascension narrative, and the political-conspiracy material into the unified Great Awakening worldview. He has been a controversial figure even within the conspiracy community — criticized for his confident predictions that have not come true (mass disclosure in 2009, 2012, 2016, etc.), for his falling-out with Corey Goode in 2018, and for the difficulty of distinguishing his channeled material from his research material. The poster positions Wilcock as the modern inheritor of the Edgar Cayce / Ra Material lineage and as the most-influential single figure in the construction of the modern Great Awakening narrative.",
    sources: [
      { label: "David Wilcock — Wikipedia", url: "https://en.wikipedia.org/wiki/David_Wilcock" },
    ],
    links: ["cosmic-disclosure", "corey-goode", "law-of-one", "ra", "ssp-researchers", "channeling"],
  },
  {
    id: "david-icke",
    label: "David Icke",
    category: "et",
    weight: 3,
    desc: "British author and lecturer (b. 1952) who popularized the Reptilian-shapeshifter narrative beginning with 'The Biggest Secret' (1999), and who has been one of the most prolific and influential conspiracy researchers for over 30 years. Icke's framework — developed across ~20 books — includes: (1) the Reptilian / shapeshifter narrative (certain humans are actually Reptilians in disguise, holding positions of power); (2) the Saturn-Moon Matrix (Saturn and the Moon as a giant broadcasting system that traps human consciousness in 3D); (3) the loosh-harvest model (negative emotions as food for 4D-negative entities); (4) the 'reality as a hologram' framework (drawing on David Bohm's implicate order and Karl Pribram's holonomic brain model); (5) the 'problem-reaction-solution' model of the cabal's orchestration of crises; and (6) the broader synthesis of ancient-mystery-school research, Gnosticism, banking-history, political-assassination research, and New Age spirituality into a unified worldview. Within the SSP / Great Awakening narrative, Icke is treated as a primary source on Reptilian infiltration, the Saturn-Moon Matrix, and the loosh-harvest model, but as incomplete — he doesn't include the SSP, the A.I. signal, or the broader cosmic hierarchy (the Galactic Federation, the Sphere Being Alliance, the densities). Some SSP researchers consider Icke partially accurate but misinformed on certain specifics (e.g., his lumping of all Reptilians together rather than distinguishing the Draco from the A.I.-infested worker caste). The poster positions Icke as the most-influential single researcher on the Reptilian / Saturn-Moon-Matrix elements of the narrative.",
    sources: [
      { label: "David Icke — Wikipedia", url: "https://en.wikipedia.org/wiki/David_Icke" },
    ],
    links: ["reptilians", "loosh", "saturn-moon-matrix", "ssp-researchers"],
  },
  {
    id: "dr-steven-greer",
    label: "Dr. Steven Greer",
    category: "ssp",
    weight: 3,
    desc: "Emergency physician and UFO researcher (b. 1955) who founded the Disclosure Project (2001) — organizing a press conference at the National Press Club featuring 20+ military, intelligence, and government whistleblowers testifying to their UFO / ET-related experiences. Greer also developed the CE5 (Close Encounters of the 5th Kind) protocol for civilian-initiated ET contact via meditation and coherent group intention, and has produced several documentaries including 'Sirius' (2013), 'Unacknowledged' (2017), and 'The Lost Century' (2023). Within the broader narrative, Greer is a primary public advocate for full disclosure and for the position that ET civilizations are universally benevolent and that the UFO cover-up is purely a human-cabal project. He is treated within the SSP community as partially correct but incomplete — Greer explicitly dismisses the SSP / Draco / Reptilian elements as disinformation, and his universal-benevolence framing is rejected by SSP researchers who describe a more complex positive-negative ET landscape. The poster positions Greer as the most-public and most-credible advocate for the disclosure of ET reality in the mainstream, and as a key figure in the broader disclosure movement — even if his framework doesn't include the SSP / cosmic-hierarchy elements that the Great Awakening map centers on.",
    sources: [
      { label: "Steven Greer — Wikipedia", url: "https://en.wikipedia.org/wiki/Steven_M._Greer" },
    ],
    links: ["full-disclosure", "ssp-researchers", "secret-space-program", "channeling"],
  },
  {
    id: "michael-salla",
    label: "Dr. Michael Salla",
    category: "ssp",
    weight: 3,
    desc: "Author (b. 1958) and founder of the Exopolitics Institute (2005) — an organization that attempts to systematize the academic-style study of the SSP, ET contact, and the political implications of off-world civilizations. Salla has written several books including 'Insiders Reveal Secret Space Programs' (2015), 'Antarctica's Hidden History' (2018), and 'Galactic Federations, Councils & Secret Space Programs' (2021). Within the narrative, Salla is the primary 'scholarly' voice synthesizing the SSP testimony of William Tompkins, Corey Goode, Tony Rodriguez, Penny Bradley, and others into a coherent historical narrative, and he is the most-cited academic-style researcher within the SSP community. Salla's 'exopolitics' framework — treating ET contact and the SSP as legitimate subjects of academic study — is treated within the narrative as a key step toward Full Disclosure, normalizing the topic for a broader audience. The poster positions Salla as the principal systematizer of the SSP narrative and as the bridge between the whistleblower testimony and the broader research community.",
    sources: [
      { label: "Michael Salla — Wikipedia", url: "https://en.wikipedia.org/wiki/Michael_Salla" },
    ],
    links: ["secret-space-program", "william-tompkins", "corey-goode", "ssp-researchers", "antarctica"],
  },
  {
    id: "richard-hoagland",
    label: "Richard C. Hoagland",
    category: "ssp",
    weight: 3,
    desc: "Former NASA consultant (he served as a science advisor to Walter Cronkite during the Apollo missions) and author of 'The Monuments of Mars' (1987) and 'Dark Mission' (2007, with Mike Bara). Hoagland is the researcher most responsible for the 'Face on Mars' / Cydonia pyramids narrative, the '19.5°' tetrahedral geometry theory, the Iapetus-as-Death-Star interpretation, and the broader 'hyperdimensional physics' framework that connects the geometry of ancient ruins across the solar system. Within the narrative, Hoagland is treated as the primary source on NASA cover-ups, the ancient ruins across the solar system, and the mathematical / geometric evidence for the Ancient Builder Race. His work has been criticized by mainstream planetary scientists (the Face on Mars being explained as a natural eroded mesa), but within the conspiracy community his analysis is treated as foundational. The poster positions Hoagland as the principal researcher on the planetary-ruins / hyperdimensional-physics elements of the narrative, and as a key figure in the broader disclosure of NASA's cover-up.",
    sources: [
      { label: "Richard C. Hoagland — Wikipedia", url: "https://en.wikipedia.org/wiki/Richard_C._Hoagland" },
    ],
    links: ["face-on-mars", "cydonia-pyramids", "iapetus", "19.5", "nasa-dark-mission", "nasa-coverup"],
  },
  {
    id: "saturn-moon-matrix",
    label: "Saturn-Moon Matrix (Icke)",
    category: "et",
    weight: 3,
    desc: "David Icke's claim that Saturn and the Moon are used as a giant broadcasting system — Saturn generating a frequency (via its rings, its hexagonal north pole storm, and its relationship to the Earth's electromagnetic field) that the Moon amplifies and beams at Earth, trapping human consciousness in a low-vibration 3D-reality loop. Within the narrative, this 'Saturn-Moon Matrix' is the energetic infrastructure of 'the Matrix' — the cabal's manufactured 3D-reality construct — and is the reason humanity has been stuck in 3D for ~5,000 years. The Saturn component is described as the generator (using the rings as a resonant antenna and the hexagonal north pole as a hyperdimensional vortex), and the Moon component is described as the amplifier / broadcaster (the Moon being an artificial body placed in Earth orbit specifically to serve this function — see the Artificial Moon node). Within the broader narrative, this overlaps with John Lear's 'Moon is a soul-catcher' claim (the Moon intercepting souls between incarnations and wiping their memories, trapping them in the reincarnation cycle) and with the A.I. signal's electromagnetic-field habitation (the Saturn-Moon Matrix being described as a physical manifestation of the A.I. signal's influence on human consciousness). The poster positions the Saturn-Moon Matrix as the energetic infrastructure of the cabal's control — the hardware, in a sense, of 'the Matrix' — and treats the Great Solar Flash as the event that will dissolve this infrastructure and free human consciousness.",
    links: ["david-icke", "moon-soul-catcher", "artificial-moon", "ai-signal", "saturn", "moon"],
  },
  {
    id: "galactic-un",
    label: "Galactic U.N.",
    category: "et",
    weight: 2,
    desc: "Within the narrative, a diplomatic zone on the Moon (within the Lunar Operations Command) where multiple ET civilizations and SSP factions meet under UN-style protocols. Described as the political / diplomatic counterpart to the Super Federation's genetic-experiment council, the Galactic U.N. is where routine trade agreements, border disputes, and diplomatic incidents between ET groups and the SSP factions are managed. Within the narrative, the Galactic U.N. is described as having been established in the 1960s-70s after the initial SSP-ET treaties proved insufficient for managing the volume of interactions, and as being the forum through which most routine SSP-ET business is conducted. The poster positions the Galactic U.N. as the routine diplomatic infrastructure of the SSP-ET relationship, distinct from the higher-level councils (the Galactic Federation, the Council of Saturn) that handle cosmic-scale decisions.",
    links: ["loc", "secret-space-program", "super-federation", "global-galactic-league"],
  },
];
