import type { GAMNode } from "./types";

// PLACES — celestial locations in the narrative
export const PLACES_NODES: GAMNode[] = [
  {
    id: "moon",
    label: "The Moon",
    category: "places",
    weight: 5,
    desc: "Within the narrative, the Moon is described as an artificial body placed into Earth orbit ~500,000 years ago by the Draco or Ancient Builder Race, hollow/honeycomb in structure, hosting the Lunar Operations Command (LOC), numerous ET bases on the far side ('heavily populated with ET bases'), crystalline towers, glass domes, and war-ruins from ancient conflicts. Said to function as a soul-catcher (per John Lear) and as a frequency-broadcast tower (per David Icke) to maintain the Saturn-Moon Matrix that traps humanity in 3D. SSP deep-lunar mining operations are described as revealing ancient civilizations and advanced technology.",
    links: ["loc", "artificial-moon", "moon-soul-catcher", "saturn-moon-matrix", "ancient-builder-race", "apollo-coverup", "secret-space-program", "moon-dark-side"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/FullMoon2010.jpg/1280px-FullMoon2010.jpg",
    imageCredit: "NASA / Gregory H. Revera",
  },
  {
    id: "moon-dark-side",
    label: "Dark Side of the Moon (ET Bases)",
    category: "places",
    weight: 3,
    desc: "Within the narrative, the lunar far side is described as heavily populated with ET bases (Draco, Reptilian, ICC, Dark Fleet), connected to the LOC and to ancient ruins. NASA imagery of the far side is said to be deliberately blurred/redacted to hide this. The reason Apollo never returned is described as a quarantine imposed by the ET groups operating there.",
    links: ["moon", "loc", "nasa-coverup", "secret-space-program", "draco-alliance"],
  },
  {
    id: "artificial-moon",
    label: "Artificial Moon (Hollow Honeycomb)",
    category: "places",
    weight: 4,
    desc: "Within the narrative, the Moon is not a natural satellite but a hollow, metallic, honeycomb-structured body brought into Earth orbit ~500,000 years ago. Cited 'evidence': the Moon rings like a bell for hours after impacts (Apollo seismic experiments), the anomalously low density, the 'too-perfect' solar eclipse geometry, and the irregular craters. Said to have been originally a Death Star-style craft that was repurposed. 'The Moon is a spaceship' — per John Lear and others.",
    links: ["moon", "moon-soul-catcher", "saturn-moon-matrix", "ancient-builder-race"],
  },
  {
    id: "moon-soul-catcher",
    label: "Moon = Soul-Catcher (John Lear)",
    category: "places",
    weight: 3,
    desc: "John Lear's claim that the Moon is a 'soul-catcher' — a device that intercepts souls between incarnations, wipes their memories, and reincarnates them back onto Earth, trapping them in the 3D reincarnation cycle. Within the broader narrative, this is fused with David Icke's Saturn-Moon Matrix to explain how humanity has been kept in 3D for thousands of years. The Great Solar Flash is said to break this cycle.",
    links: ["moon", "saturn-moon-matrix", "reincarnation", "artificial-moon", "great-solar-flash"],
  },
  {
    id: "loc",
    label: "Lunar Operations Command (LOC)",
    category: "ssp",
    weight: 4,
    desc: "Described as the SSP's primary base on the Moon, located on the far side. Said to have multiple underground levels (LOC 1, 2, 3), house the Galactic U.N. diplomatic zone, and serve as the staging point for all SSP lunar operations. Corey Goode reports being processed through the LOC on his way to 20-and-back service.",
    links: ["secret-space-program", "moon", "galactic-un", "corey-goode", "underground-bases"],
  },
  {
    id: "mars",
    label: "Mars",
    category: "places",
    weight: 5,
    desc: "Within the narrative, Mars is described as a former Earth-like planet destroyed ~500,000 years ago in an ancient nuclear war (the Mars Catastrophe), now hosting extensive ancient ruins (Cydonia pyramids, the Face, Pharaoh Sarcophagus), underground bases operated by the ICC using human slave labor, a 'slave colony' run via the 20-and-back program, jumpgate portals, inner-Mars civilizations, and a 'red' Mars that is in reality blue-skied (NASA color-manipulation claim). Satellite/rover blackouts are explained as NASA deliberately hiding evidence.",
    links: ["cydonia-pyramids", "face-on-mars", "mars-catastrophe", "icc", "icc-bases-mars", "jumpgate-portals", "ancient-builder-race", "mars-blue-skies", "nasa-coverup"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/OSIRIS_Mars_true_color.jpg/1280px-OSIRIS_Mars_true_color.jpg",
    imageCredit: "ESA / OSIRIS team",
  },
  {
    id: "mars-blue-skies",
    label: "Mars 'Red' / Blue Skies",
    category: "places",
    weight: 2,
    desc: "Within the narrative, NASA deliberately color-shifts Mars imagery to make it appear red and inhospitable, when in reality Mars has blue skies, Earth-like terrain in places, and is partially habitable. Side-by-side comparisons of raw vs. released NASA imagery are circulated as 'proof.' Said to be part of the cover-up to hide Mars' habitability and the ICC's operations there.",
    links: ["mars", "nasa-coverup", "icc-bases-mars"],
  },
  {
    id: "icc-bases-mars",
    label: "ICC Mars Bases (Human Slave Labor)",
    category: "places",
    weight: 3,
    desc: "Within the narrative, the ICC operates extensive underground bases on Mars using human slave labor — workers abducted via MILABs, age-regressed, and placed in 20-and-back service on Mars industrial facilities producing technology for the ICC's trade with 900+ ET races. Tony Rodriguez and other whistleblowers describe the brutal conditions. Said to be the modern continuation of the Mars slave-colony program that has existed for hundreds of thousands of years.",
    links: ["icc", "mars", "20-and-back", "human-slave-labor", "tony-rodriguez", "secret-space-program"],
  },
  {
    id: "saturn",
    label: "Saturn",
    category: "places",
    weight: 4,
    desc: "Within the narrative, Saturn is described as: (a) the home of the Council of Saturn (Law of One) in a time-bubble sanctuary, (b) the site of Dark Fleet bases, (c) the location of the Ringmakers (Bergrun's EMVs manufacturing the rings), (d) the broadcast-source of the Saturn-Moon Matrix frequency (Icke), and (e) the location of the 'Hyperdimensional Hexagon' at the north pole — a stargate / energy vortex. Saturn is described as 'off-limits to the SSP Alliance' due to the Dark Fleet presence.",
    links: ["council-of-saturn", "dark-fleet", "ringmakers-saturn", "saturn-moon-matrix", "saturn-hexagon", "ancient-builder-race"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Saturn_-_August_11_2006_by_Cassini_Spacecraft.jpg/1280px-Saturn_-_August_11_2006_by_Cassini_Spacecraft.jpg",
    imageCredit: "NASA / JPL / Space Science Institute",
  },
  {
    id: "saturn-hexagon",
    label: "Saturn's North Pole Hexagon",
    category: "places",
    weight: 3,
    desc: "A real persistent hexagonal cloud pattern at Saturn's north pole, discovered by Voyager (1981) and imaged in detail by Cassini. Within the narrative, the hexagon is described as a hyperdimensional vortex / stargate / energy conduit — the visible signature of higher-dimensional energy being drawn into 3D at the 19.5°-apex geometry of a tetrahedron inscribed in Saturn. Cited as proof of the hyperdimensional physics model.",
    sources: [
      { label: "Saturn's hexagon — Wikipedia", url: "https://en.wikipedia.org/wiki/Saturn%27s_hexagon" },
    ],
    links: ["saturn", "19.5", "sacred-geometry", "nasa-coverup"],
  },
  {
    id: "venus",
    label: "Venus",
    category: "places",
    weight: 3,
    desc: "Within the narrative, Venus is described as the origin planet of Ra (the Law of One entity), home to 'miles-high towers' and 'sentinels' left by the Ancient Builder Race, and the site of ICC-controlled facilities in the upper atmosphere (above the hostile surface). The 5th–7th-density Sentinels are said to be the custodians of the Ancient Builder Race technology on Venus. Surface conditions are explained as a deliberately engineered hostile environment to keep out lower-density beings.",
    links: ["ra", "ancient-builder-race", "sentinels", "icc", "law-of-one"],
  },
  {
    id: "ceres-base",
    label: "Ceres (Dark Fleet Base)",
    category: "places",
    weight: 3,
    desc: "Within the narrative, the dwarf planet Ceres (in the asteroid belt) hosts a major Dark Fleet underground base — described as a forward operating base beyond the asteroid belt, supplied by the ICC with technology and personnel, and used as a staging point for operations deeper into the solar system. The famous Ceres 'bright spots' (real features imaged by Dawn in 2015) are described as reflective structures on the base.",
    sources: [
      { label: "Ceres (dwarf planet) — Wikipedia", url: "https://en.wikipedia.org/wiki/Ceres_(dwarf_planet)" },
    ],
    links: ["dark-fleet", "icc", "asteroid-belt", "secret-space-program"],
  },
  {
    id: "antarctica",
    label: "Antarctica",
    category: "places",
    weight: 4,
    desc: "Within the narrative, Antarctica is described as: (a) the location of the Nazi breakaway civilization's base (after WWII), (b) the site of pre-Adamite (Atlantean) ruins buried under the ice, (c) the location of Admiral Byrd's 1947 Operation Highjump 'defeat' by Nazi antigravity craft, (d) the off-limits zone guarded by the Antarctic Treaty (signed 1959 to keep the public out), and (e) the recent site of recovered ancient technology that the cabal is using for their breakaway plans.",
    links: ["nazi-breakaway", "operation-highjump", "atlantis", "ancient-builder-race", "deep-state", "michael-salla"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Antarctica_with_research_stations.jpg/1280px-Antarctica_with_research_stations.jpg",
    imageCredit: "CIA / public domain",
  },
  {
    id: "underground-bases",
    label: "Underground Bases (DUMBs)",
    category: "places",
    weight: 4,
    desc: "Within the narrative, an extensive network of Deep Underground Military Bases (DUMBs) exists worldwide — connected by maglev tunnels, used by the SSP, the cabal, the ICC, and various ET groups. Major facilities are described under Dulce (NM), Area 51/S4 (NV), Denver Airport, Pine Gap (Australia), and the Moon/Mars. Phil Schneider's 1995 testimony is cited as a primary source. Said to be the literal underground where the cabal's child trafficking, MILABs, and '20-and-back' processing occur.",
    sources: [
      { label: "Dulce Base — Wikipedia", url: "https://en.wikipedia.org/wiki/Dulce_Base" },
    ],
    links: ["secret-space-program", "milab", "icc-bases-mars", "child-trafficking-tunnels", "loc"],
  },
  {
    id: "tibet",
    label: "Tibet (Inner Earth Entrances)",
    category: "places",
    weight: 2,
    desc: "Within the narrative, Tibet is described as one of the primary surface entrances to the inner-Earth civilizations (Agartha / Shambhala), accessed via secret tunnels beneath the Himalayan monasteries. Said to be the source of the Tibetan rainbow body lineages (Padmasambhava) and a site of Nazi interest (the 1938–39 Ahnenerbe expedition was searching for these entrances and for the inner-Earth civilizations).",
    links: ["tibet-tunnels", "inner-earth-civilizations", "agartha", "padmasambhava", "nazi-breakaway"],
  },
];

// EARTH MYSTERIES
export const EARTH_NODES: GAMNode[] = [
  {
    id: "norway-spiral",
    label: "Norway Spiral (2009)",
    category: "earth",
    weight: 3,
    desc: "A real anomalous spiral light display seen over Norway on December 9, 2009, the day before Obama's Nobel Peace Prize speech. Officially attributed to a failed Russian Bulava missile. Within the narrative, the Norway Spiral is described as a visible wormhole/stargate opening (related to Project Blue Beam HAARP/EISCAT), a message from the Sphere Being Alliance, or a failed cabal Project Blue Beam test-run. Cited as one of the most visible public 'ET/SSP' events of the 21st century.",
    sources: [
      { label: "2009 Norwegian spiral anomaly — Wikipedia", url: "https://en.wikipedia.org/wiki/2009_Norwegian_spiral_anomaly" },
    ],
    links: ["jumpgate-portals", "cosmic-web-portal", "sphere-being-alliance", "blue-beam"],
  },
  {
    id: "soho-satellite",
    label: "SOHO Satellite (Anomalies)",
    category: "earth",
    weight: 2,
    desc: "The real NASA/ESA Solar and Heliospheric Observatory (SOHO) satellite. Within the narrative, SOHO imagery is regularly cited as showing enormous craft ('sun portals,' 'motherships,' 'sun cruisers') near the Sun — refueling, communicating, or using the Sun as a stargate. NASA's occasional image blackouts are described as deliberate cover-ups of these objects.",
    links: ["electric-sun", "cosmic-web-portal", "nasa-coverup", "sun-portal-motherships"],
  },
  {
    id: "sun-portal-motherships",
    label: "Sun Portal Motherships",
    category: "places",
    weight: 2,
    desc: "Within the narrative, the Sun is a stargate / cosmic web portal through which enormous ET motherships enter and exit the solar system. SOHO imagery is cited as evidence. Said to be the mechanism by which the Sphere Being Alliance's blue spheres entered our solar system around 2011–2012.",
    links: ["electric-sun", "cosmic-web-portal", "soho-satellite", "sphere-being-alliance"],
  },
  {
    id: "ebani",
    label: "EBANI (Anomalous Sky Beings)",
    category: "earth",
    weight: 2,
    desc: "EBANI = 'Entidad Biológica Anómala No Identificada' (Anomalous Biological Entity). A term coined by Mexican UFO researcher Rafael Navarro for the luminous, amorphous, often worm-like aerial objects filmed in the skies — distinct from nuts-and-bolts UFOs. Within the narrative, EBANIs are described as atmospheric plasma-beings / 4D creatures that have always lived in Earth's upper atmosphere — a modern name for what folklore called sky-fish, sky-serpents, and atmospheric elementals.",
    links: ["fairies-mermaids", "orbs", "inner-earth-civilizations"],
  },
  {
    id: "global-warming-planets",
    label: "All Planets Warming",
    category: "earth",
    weight: 3,
    desc: "Within the narrative, global warming is not anthropogenic but solar-system-wide — every planet with an atmosphere (Mars, Jupiter, Saturn, Neptune, Pluto) is said to be heating up and brightening, indicating a solar-system-scale energy increase that is the precursor to the Great Solar Flash. Used to argue that the cabal's climate-change narrative is a cover-up of the cosmic energy shift.",
    links: ["great-solar-flash", "schumann-resonance", "electric-sun", "raising-vibration"],
  },
  {
    id: "gaia-earth-consciousness",
    label: "Gaia (Earth as Living Being)",
    category: "earth",
    weight: 3,
    desc: "Within the narrative, Earth (Gaia / Sophia / Terra) is a conscious, sentient being in her own right — a planetary logos with her own Oversoul, her own ascension path, and her own will. Said to be ascending from 3D to 4D herself, and humanity is along for the ride. Environmentalism in this framing is not political but spiritual — cooperation with Gaia's ascension. The Schumann resonance is described as her 'heartbeat.'",
    links: ["schumann-resonance", "ascension", "great-solar-flash", "one-infinite-creator", "5d-earth"],
  },
  {
    id: "masaru-emoto",
    label: "Dr. Masaru Emoto (Water Memory)",
    category: "earth",
    weight: 3,
    desc: "Japanese researcher (1943–2014) who claimed that water exposed to positive words/intentions forms beautiful ice crystals, while water exposed to negative words forms deformed crystals. Within the narrative, Emoto's work is cited as proof that consciousness structures matter (via frequency), that water is the literal medium of consciousness on Earth, and that blessing/curse actually restructures the body's water. The 'water memory' concept is also linked to homeopathy and to Luc Montagnier's DNA-teleportation claims.",
    sources: [
      { label: "Masaru Emoto — Wikipedia", url: "https://en.wikipedia.org/wiki/Masaru_Emoto" },
    ],
    links: ["cymatics", "vibration-frequency", "raising-vibration", "sacred-geometry"],
  },
  {
    id: "dowsing-geomancy",
    label: "Dowsing & Geomancy (Earth Grids)",
    category: "earth",
    weight: 3,
    desc: "Within the narrative, Earth is crisscrossed by energetic ley lines / Hartmann lines / Curry lines / the Earth grid (Bruce Cathie's work), with power-nodes at major ancient sites (Giza, Stonehenge, Machu Picchu, Sedona, Uluru). Dowsing is described as the practical skill of perceiving these lines; geomancy as the practice of building/living in alignment with them. Said to be the surviving practical knowledge of the Atlantean / Ancient Builder Race grid-engineering.",
    links: ["giza-complex", "ancient-aliens", "sacred-geometry", "ancient-builder-race", "19.5"],
  },
  {
    id: "ubuntu",
    label: "Ubuntu (Contributionism)",
    category: "earth",
    weight: 2,
    desc: "Michael Tellinger's 'Ubuntu Contributionism' movement — a proposed post-money, post-bank, community-self-sufficient model based on ancient African (and supposedly Atlantean) principles. Within the narrative, Ubuntu is described as the social structure that will replace the cabal's debt-slavery system after the Event, in which communities use their own resources and skills to provide for everyone without money.",
    sources: [
      { label: "Ubuntu (philosophy) — Wikipedia", url: "https://en.wikipedia.org/wiki/Ubuntu_philosophy" },
    ],
    links: ["end-the-fed", "earth-alliance", "great-awakening", "world-gold-heist"],
  },
];
