import type { GAMNode } from "./types";

// QANON — the political-conspiracy wing of the map
export const QANON_NODES: GAMNode[] = [
  {
    id: "qanon",
    label: "QAnon",
    category: "qanon",
    weight: 5,
    desc: "Within the narrative, QAnon is the public-facing political-military intelligence operation through which the Earth Alliance (white-hat U.S. military + Trump + allied intelligence) communicates with the public — via 'Q drops' (anonymous posts on 4chan, then 8chan, then 8kun, starting October 28, 2017) by an insider claiming Q-clearance access. Q's central claims: (1) Trump was recruited by the military to run for president to dismantle the cabal from within, (2) the cabal is a global satanic pedophile network, (3) 'The Storm' is the mass-arrest event, (4) 'The Plan' is the multi-year operation, and (5) 'Where We Go One We Go All' (WWG1WGA) is the unifying slogan.",
    sources: [
      { label: "QAnon — Wikipedia", url: "https://en.wikipedia.org/wiki/QAnon" },
    ],
    links: ["q-drops", "qmap", "8chan", "wwg1wga", "anons", "the-storm", "trust-the-plan", "trump", "white-hats", "earth-alliance", "great-awakening"],
  },
  {
    id: "q-drops",
    label: "Q Drops",
    category: "qanon",
    weight: 4,
    desc: "The anonymous posts by 'Q' (or whoever is operating Q) — numbering ~5,000 by 2022. Within the narrative, each drop is a coded military-intelligence communication containing: breadcrumbs (clues for the anons to research), predictions (some of which 'come true' and some of which don't), Socratic questions ('Why is X happening now?'), and 'confirmations' (photographs from inside Air Force One, the Oval Office, etc.). Treated by the community as primary-source documents, archived on QMap, QAlerts, and similar sites. The drops themselves are read as both news-foreshadowing and as a 'movie script' that the Earth Alliance is executing.",
    links: ["qanon", "qmap", "anons", "trust-the-plan", "8chan"],
  },
  {
    id: "qmap",
    label: "QMap / QAggregator",
    category: "qanon",
    weight: 2,
    desc: "The websites (QMap.pub, QAlerts, QAnon.pub) that aggregate and search the Q drops. Within the community, QMap.pub (run by 'apprentice' / Jordan Sather's associate) was the most-cited until it was taken offline in September 2020. QAlerts.app became the primary replacement. Treated as the canonical archive of the operation's communications.",
    links: ["q-drops", "qanon", "anons"],
  },
  {
    id: "8chan",
    label: "8chan / 8kun / 4chan",
    category: "qanon",
    weight: 3,
    desc: "The imageboards where Q has posted since October 2017 — initially 4chan, then 8chan (after the 4chan board was 'compromised' in November 2017), then 8kun (after 8chan was deplatformed in August 2019 following the El Paso and Dayton shootings). Within the narrative, Q's move from board to board is described as the operation being protected from cabal-orchestrated deplatforming. 8kun remains the only 'authentic' source of Q drops. The imageboards' anonymous-posting culture is treated as the operational substrate of the operation.",
    sources: [
      { label: "8chan — Wikipedia", url: "https://en.wikipedia.org/wiki/8chan" },
    ],
    links: ["q-drops", "qanon", "anonymous-meme-wars"],
  },
  {
    id: "wwg1wga",
    label: "WWG1WGA",
    category: "qanon",
    weight: 3,
    desc: "'Where We Go One We Go All' — the unifying slogan of QAnon, used as a hashtag (#WWG1WGA), a sign-off, a tattoo, and a rallying cry. Within the narrative, the phrase originated from a NASA Apollo mission patch ('We Go One, We Go All') and signals the collective nature of the awakening: everyone wakes together, or no one does. Treated as the movement's primary identity marker. The poster places it next to the QAnon node as the slogan of the political Great Awakening.",
    links: ["qanon", "anons", "patriots", "great-awakening", "trump"],
  },
  {
    id: "anons",
    label: "Anons",
    category: "qanon",
    weight: 3,
    desc: "The collective term for the anonymous researchers on 4chan / 8chan / 8kun who research and decode the Q drops — drawn from the imageboard culture of 'anonymous' (Anon) posting. Within the narrative, the anons are the citizen-research army that the Earth Alliance is using to surface, research, and disseminate the truth in parallel with the military operations. 'Q+ posts' (Trump himself posting) and 'baker' roles (anons who compile the day's drops into readable threads) are part of the operational jargon.",
    links: ["qanon", "q-drops", "anonymous-meme-wars", "patriots", "8chan"],
  },
  {
    id: "patriots",
    label: "Patriots",
    category: "qanon",
    weight: 3,
    desc: "Within the narrative, 'Patriots' are the broadest category of the awakening — anyone who supports the Constitution, the Republic, and the dismantling of the cabal, including but not limited to the anons. 'Patriots in control' is a recurring Q phrase signaling that the Earth Alliance has the upper hand in a given situation. Treated as the political identity of the awakening community.",
    links: ["qanon", "anons", "wwg1wga", "white-hats", "earth-alliance"],
  },
  {
    id: "white-hats",
    label: "White Hats",
    category: "qanon",
    weight: 4,
    desc: "Within the narrative, the 'white hats' are the good guys inside the system — active-duty and retired military, intelligence, law-enforcement, and government officials who are working (mostly covertly) with the Earth Alliance to dismantle the cabal from within. Said to be embedded in every agency (CIA, FBI, NSA, DOJ, State) and every branch of the military. The 'white-hat vs black-hat' framing is central to QAnon's operational worldview. Trump, Flynn, Powell, Patel, and (variants) JFK Jr. are named as leaders.",
    links: ["qanon", "earth-alliance", "trump", "trust-the-plan", "the-storm"],
  },
  {
    id: "the-storm",
    label: "The Storm",
    category: "qanon",
    weight: 4,
    desc: "Within the narrative, 'The Storm' is the mass-arrest event — the moment when the Earth Alliance moves openly against the cabal: tens of thousands of sealed indictments unsealed, military tribunals convened at Gitmo, FEMA camps activated, emergency broadcast (EBN / EBS) triggered to air the confessions, and the cabal leadership perp-walked. Q himself referenced 'The Storm' in an October 2017 drop, and asked Trump at a photo op about 'the calm before the storm.' The Storm has been repeatedly predicted and repeatedly deferred — the community treats each deferral as part of the operation's strategic timing.",
    links: ["qanon", "sealed-indictments", "tribunals", "trust-the-plan", "white-hats"],
  },
  {
    id: "drain-the-swamp",
    label: "Drain the Swamp",
    category: "qanon",
    weight: 3,
    desc: "Trump's 2016 campaign slogan ('drain the swamp' of Washington corruption), adopted by QAnon as the public-facing name for the Earth Alliance's operation against the Deep State. Within the narrative, the 'swamp' is the institutional infrastructure of the cabal in D.C. — career bureaucrats, intelligence operatives, lobbyists, and the political class that maintains the cabal's control regardless of elections. 'Drain the Swamp' became shorthand for the whole QAnon program.",
    links: ["qanon", "deep-state", "trump", "the-storm", "white-hats"],
  },
  {
    id: "trust-the-plan",
    label: "Trust the Plan",
    category: "qanon",
    weight: 3,
    desc: "Within the narrative, 'Trust the Plan' is QAnon's central coping doctrine — the repeated Q instruction that, no matter how bad things look, the Earth Alliance is in control, the timing is strategic, and the operation will succeed. Critics see it as a 'disappointment-management' mechanism (when predictions fail, the plan is still on track); the community sees it as the correct posture of faith in the operation. Often paired with 'Enjoy the show.'",
    links: ["qanon", "the-storm", "white-hats", "4d-chess"],
  },
  {
    id: "tribunals",
    label: "Military Tribunals (Gitmo)",
    category: "qanon",
    weight: 3,
    desc: "Within the narrative, the Earth Alliance has been conducting sealed-military-tribunal prosecutions of cabal figures at Gitmo (Guantanamo Bay) and (in variants) at newly-built tribunal facilities — using the post-9/11 military-commission framework, the Insurrection Act, and the 2018 Executive Order on foreign interference. Said to have already convicted and (in variants) executed many cabal figures, with body doubles and clones standing in for the public until the EBS broadcast. The McCain, Bush Sr., Ginsburg, and (variants) Queen Elizabeth deaths are cited as tribunal outcomes.",
    links: ["the-storm", "sealed-indictments", "qanon", "white-hats"],
  },
  {
    id: "sealed-indictments",
    label: "Sealed Indictments",
    category: "qanon",
    weight: 3,
    desc: "Within the narrative, the Earth Alliance has filed tens of thousands (variants: 100k+ to 500k+) of sealed federal indictments against cabal figures — visible (per the community) in the public PACER court-filings counts that show sealed-indictment totals far above historical norms. Said to be unsealed en masse at the Storm. Trump's 2018 Executive Order on foreign interference is cited as the legal framework allowing military tribunals for crimes normally tried in civilian courts.",
    links: ["the-storm", "tribunals", "qanon", "white-hats"],
  },
  {
    id: "follow-the-white-rabbit",
    label: "Follow the White Rabbit",
    category: "qanon",
    weight: 2,
    desc: "A QAnon / broader-awakening metaphor (drawn from 'The Matrix' and 'Alice in Wonderland') for following the chain of clues wherever it leads — into the cabal, the SSP, the Draco, the Saturn-Moon Matrix. The 'white rabbit' is the initial anomaly or clue that, once pursued, opens the rabbit hole. Used as a recruitment slogan ('follow the white rabbit down the rabbit hole').",
    links: ["the-rabbit-hole", "red-pill", "escape-the-matrix", "qanon"],
  },
  {
    id: "trump",
    label: "Donald Trump (GEOTUS)",
    category: "qanon",
    weight: 5,
    desc: "Within the narrative, Donald Trump was recruited by U.S. military white hats (specifically Admiral Rogers of the NSA and General Flynn of the DIA) in 2014–15 to run for president as the public-facing leader of the Earth Alliance's operation to dismantle the cabal from within. Said to have been briefed on ET contact, the SSP, and the cabal's child-trafficking network before taking office. 'GEOTUS' = 'God Emperor of the United States' (community honorific). His actions (Space Force, the Fed, Jerusalem embassy, the Abraham Accords, the wall, COVID 'Warp Speed' as a sting) are all read as Earth Alliance operations. The 2020 'loss' is described as a strategic sting operation to expose the cabal's election-rigging apparatus.",
    sources: [
      { label: "Donald Trump — Wikipedia", url: "https://en.wikipedia.org/wiki/Donald_Trump" },
    ],
    links: ["qanon", "white-hats", "earth-alliance", "space-force", "drain-the-swamp", "4d-chess", "the-storm"],
  },
  {
    id: "space-force",
    label: "Space Force",
    category: "qanon",
    weight: 4,
    desc: "Within the narrative, Trump's December 2019 establishment of the U.S. Space Force is described as the public-facing unmasking of the MICSSP — the Earth Alliance's first step toward full disclosure, the legal framework for prosecuting cabal actors for crimes committed in space, and the institutional counter to the cabal-controlled SSP factions. Said to be the vehicle through which classified SSP technology is gradually declassified. The Space Force 'delta' logo (vs. Star Trek's) is treated as symbolic disclosure.",
    sources: [
      { label: "United States Space Force — Wikipedia", url: "https://en.wikipedia.org/wiki/United_States_Space_Force" },
    ],
    links: ["trump", "secret-space-program", "micssp", "full-disclosure", "earth-alliance"],
  },
  {
    id: "4d-chess",
    label: "4D Chess",
    category: "qanon",
    weight: 2,
    desc: "Within the narrative, Trump and the Earth Alliance operate at a level of strategic depth ('4D chess') invisible to the cabal and the media. Apparent setbacks (the 2020 loss, the COVID response, the early staff firings) are read as intentional moves in a multi-year operation. The community treats every Trump statement and action as potentially containing coded meaning for the anons. Closely related to 'Trust the Plan.'",
    links: ["trump", "trust-the-plan", "qanon", "white-hats"],
  },
  {
    id: "anonymous-meme-wars",
    label: "Anonymous Meme Wars",
    category: "qanon",
    weight: 3,
    desc: "Within the narrative, the anons and the broader awakening community are waging an information war against the cabal's Mockingbird media — using memes, viral content, 'psychological thought bombs,' and high-volume social-media posting to break through the cabal's narrative control. Said to be the modern evolution of the original Anonymous movement. Treated as a real, effective form of asymmetric warfare that the cabal cannot counter.",
    links: ["anons", "qanon", "mockingbird", "8chan", "kill-your-tv"],
  },
  {
    id: "pizzagate",
    label: "Pizzagate",
    category: "qanon",
    weight: 4,
    desc: "The November 2016 narrative (precursor to QAnon) that alleged Comet Ping Pong pizzeria in D.C. (and its owner James Alefantis, and the Podesta brothers, and the Clinton campaign) was a front for a child-trafficking ring — based on emails leaked by WikiLeaks from John Podesta's account, decoded using 4chan / Reddit research into coded language ('cheese,' 'pizza,' 'walnut sauce,' 'handkerchief'). The narrative is treated within the broader community as the first mass surfacing of the cabal's child-trafficking element, and as the proto-QAnon moment. Edgar Maddison Welch's December 2016 armed 'investigation' of Comet is described within the community as a false-flag to discredit the narrative.",
    sources: [
      { label: "Pizzagate — Wikipedia", url: "https://en.wikipedia.org/wiki/Pizzagate_conspiracy_theory" },
    ],
    links: ["clinton-elite", "child-trafficking-tunnels", "epstein-island", "qanon", "save-the-children"],
  },
  {
    id: "geotus",
    label: "GEOTUS / Anons Slang",
    category: "qanon",
    weight: 2,
    desc: "The community-slang layer of QAnon: GEOTUS (God Emperor of the United States = Trump), FLOTUS (Melania), KAG (Keep America Great), Kek/Kekistan (the meme 'god' of 4chan), Pepe, the 'Great Awakening,' the 'silence is golden' parables, 'nothing can stop what is coming,' 'enjoy the show.' Treated as the in-group language that marks awakening-community membership and binds the collective.",
    links: ["qanon", "trump", "anons", "wwg1wga"],
  },
];
