import type { GAMNode } from "./types";

// SPIRITUAL / ASCENSION — density shifts, light bodies, consciousness practices
export const SPIRITUAL_NODES: GAMNode[] = [
  {
    id: "age-of-aquarius",
    label: "Age of Aquarius",
    category: "spiritual",
    weight: 3,
    desc: "Within the narrative, the ~2,000-year astrological age Earth is now transitioning into (from Pisces), said to bring collective enlightenment, the exposure of secrets, and the collapse of hierarchical control structures. Described as the astrological counterpart to the Great Awakening and the trigger for the Consciousness Renaissance. The precessional transition itself is the cosmic clock the Great Solar Flash is timed to.",
    links: ["precession-equinoxes", "consciousness-renaissance", "great-awakening", "ascension"],
  },
  {
    id: "precession-equinoxes",
    label: "Precession of the Equinoxes",
    category: "earth",
    weight: 3,
    desc: "A real astronomical phenomenon: Earth's rotational axis wobbles over a ~25,772-year cycle, gradually shifting which stars appear behind the sun at a given time of year. Within the narrative, this 25,920-year cycle is the cosmic clock that triggers the Great Solar Flash and consciousness shift at each transition — every 'Yuga' or 'Age' in the Vedic, Mayan, and Zoroastrian calendars is one twelfth of this precessional cycle.",
    links: ["age-of-aquarius", "consciousness-renaissance", "great-solar-flash", "samvartaka-fire"],
  },
  {
    id: "schumann-resonance",
    label: "Schumann Resonance (Increasing)",
    category: "earth",
    weight: 4,
    desc: "A real set of electromagnetic resonances in Earth's lower atmosphere (~7.83 Hz baseline), caused by global lightning. Within the narrative, the Schumann Resonance is described as 'increasing' — the claim being that Earth's base frequency is rising in the lead-up to the Great Solar Flash, raising human consciousness with it. Charts of anomalous Schumann spikes circulate in the community as 'proof' that ascension is underway. Described as 'Earth's heartbeat.'",
    links: ["great-solar-flash", "ascension", "raising-vibration", "vibration-frequency"],
  },
  {
    id: "pineal-gland",
    label: "Pineal Gland (Decalcify & Activate)",
    category: "consciousness",
    weight: 5,
    desc: "The pineal gland (a small endocrine gland in the brain) is described within the narrative as the physical 'seat of the soul' and the biological antenna for higher-dimensional consciousness — the 'third eye.' Said to be deliberately calcified by fluoride in water, processed food, and chemtrails. Decalcification protocols (Activator X / ratfish liver oil, sun gazing, iodine, fluoride avoidance, fasting) are presented as the foundation of any ascension practice. Activation is described as the literal mechanism by which one accesses the akashic records, astral travel, and remote viewing.",
    links: ["third-eye", "activator-x", "decalcify", "akashi-records", "ascension", "raising-vibration"],
  },
  {
    id: "activator-x",
    label: "Activator X (Ratfish Liver Oil)",
    category: "healing",
    weight: 2,
    desc: "A concept from Dr. Weston A. Price's nutrition research, repurposed within the narrative. 'Activator X' is identified as K2 (specifically the MK-4 form found in ratfish liver oil, skate liver oil, and grass-fed butterfat). Described as the most potent decalcifier of the pineal gland — pulling fluoride and calcium out of the gland and restoring its function.",
    links: ["pineal-gland", "decalcify", "holistic-healing"],
  },
  {
    id: "decalcify",
    label: "Decalcification Protocols",
    category: "healing",
    weight: 3,
    desc: "A category of dietary and lifestyle practices aimed at removing fluoride, calcium deposits, and heavy metals from the pineal gland: avoiding fluoridated water and toothpaste, eating Activator X foods, supplementing with iodine and boron, sungazing, drinking distilled or reverse-osmosis water, and using zeolite or diatomaceous earth for heavy-metal detox. Presented as step one of any awakening practice.",
    links: ["pineal-gland", "activator-x", "holistic-healing", "third-eye"],
  },
  {
    id: "third-eye",
    label: "Third Eye (Ajna)",
    category: "consciousness",
    weight: 4,
    desc: "The sixth chakra, located between the eyebrows. Within the narrative, the third eye is the energetic counterpart of the pineal gland — when activated (via decalcification + meditation + psychedelics + sungazing), it is described as granting access to clairvoyance, akashic records, remote viewing, multidimensional perception, and direct connection to the Oversoul / Higher Self. The 'opening of the third eye' is treated as the central threshold of personal awakening.",
    links: ["pineal-gland", "chakras", "decalcify", "akashi-records"],
  },
  {
    id: "chakras",
    label: "Chakras (Energy Centers)",
    category: "consciousness",
    weight: 4,
    desc: "The seven major energy centers of the body, drawn from Hindu and Buddhist tantric traditions. Within the narrative, chakras are the literal energetic anatomy through which the soul interfaces with the body, and through which vibration is raised. Each chakra is associated with a frequency, color, endocrine gland, and density of consciousness. Blockages in the chakras (from trauma, fluoride, loosh harvest, EMF) are said to be the mechanism by which the cabal keeps humanity in low-vibration 3D. Kundalini awakening opens them all.",
    links: ["kundalini-awakening", "pineal-gland", "third-eye", "aura", "ascension", "raising-vibration"],
  },
  {
    id: "kundalini-awakening",
    label: "Kundalini Awakening",
    category: "consciousness",
    weight: 4,
    desc: "From yogic tradition: the rising of dormant 'serpent' energy from the base of the spine up through each chakra, piercing the crown and activating the full energetic body. Within the narrative, kundalini awakening is described as the biological mechanism of personal ascension — what happens when the vibration of the body rises enough to activate dormant DNA, open the pineal gland, and trigger the light body. Often preceded by a 'dark night of the soul' or trauma.",
    links: ["chakras", "ascension", "dna-upgrade", "light-body-ascension", "raising-vibration", "yoga"],
  },
  {
    id: "light-body-ascension",
    label: "Light Body Ascension",
    category: "spiritual",
    weight: 4,
    desc: "The claimed transformation of the physical body into a higher-vibrational 'light body' (the 'rainbow body' of Dzogchen, the 'merkaba body' of Melchizedek teachings). Within the narrative, this is the goal of every ascension practice — the body becomes less dense, less subject to disease and aging, more multidimensionally accessible, and ultimately capable of dematerializing or transitioning to 5D. Said to be the personal-scale version of what the Great Solar Flash triggers for all of humanity.",
    links: ["ascension", "tibetan-rainbow-body", "star-merkaba", "dna-upgrade", "5d-earth", "drunvalo-melchizedek"],
  },
  {
    id: "dna-upgrade",
    label: "DNA Upgrade (12 Strand)",
    category: "spiritual",
    weight: 4,
    desc: "Within the narrative, human DNA originally had 12 strands but was genetically downgraded to 2 strands by the Annunaki to make humanity a controllable slave race. The 'junk DNA' of mainstream genetics is described as the dormant 10 strands waiting to be reactivated. Said to be reactivating spontaneously in children (Indigos, star children) and in adults through kundalini awakening, light-body work, and energetic upgrades from the Sphere Being Alliance / Schumann resonance increase.",
    links: ["light-body-ascension", "ascension", "annunaki", "star-children", "indigos", "kundalini-awakening"],
  },
  {
    id: "akashi-records",
    label: "Akashic Records",
    category: "consciousness",
    weight: 4,
    desc: "A theosophical concept: a non-physical 'library' or field recording every thought, emotion, and event in the history of the cosmos — accessible via the third eye / pineal gland / deep meditation. Within the narrative, the Akashic Records are described as the literal informational field of the cosmos (the 'hall of records'), accessible to anyone with an activated pineal gland, and the source of all true channeled material. Edgar Cayce's readings are the most famous modern example.",
    sources: [
      { label: "Akashic records — Wikipedia", url: "https://en.wikipedia.org/wiki/Akashic_records" },
    ],
    links: ["pineal-gland", "third-eye", "oversoul", "channeling", "past-life-regression"],
  },
  {
    id: "oversoul",
    label: "The Oversoul (Higher Self)",
    category: "consciousness",
    weight: 4,
    desc: "The 'higher mind' or higher-self aspect of an individual — the part of consciousness that exists in higher density (5D+) and orchestrates incarnations on Earth. Within the narrative, every human has an Oversoul that is a fragment of the One Infinite Creator, and the goal of awakening is to align the ego-personality with the Oversoul. Communication with the Oversoul is described as the source of intuition, divine downloads, and synchronicity.",
    links: ["akashi-records", "higher-self", "one-infinite-creator", "channeling", "light-body-ascension"],
  },
  {
    id: "higher-self",
    label: "Higher Self / Higher Mind",
    category: "consciousness",
    weight: 3,
    desc: "Within the narrative, the Higher Self is the 5D-and-above portion of an individual consciousness that holds the soul's plan for the current incarnation. Said to communicate via the Oversoul through synchronicity, dreams, intuition, and (when the pineal gland is activated) direct telepathic communication. The 'small still voice' of conscience is described as the Higher Self's signal.",
    links: ["oversoul", "akashi-records", "pineal-gland", "ascension"],
  },
  {
    id: "star-merkaba",
    label: "Star Merkaba Vehicle",
    category: "consciousness",
    weight: 3,
    desc: "A geometric 'light body vehicle' (merkaba = 'light-spirit-body' in Hebrew) described in Drunvalo Melchizedek's 'The Ancient Secret of the Flower of Life' teachings. Within the narrative, activating the merkaba (via specific meditation + sacred geometry + breathwork) creates a counter-rotating field of light around the body that enables multidimensional travel, ascension, and protection. Said to be the same vehicle used by ascended masters and ETs.",
    sources: [
      { label: "Merkabah — Wikipedia", url: "https://en.wikipedia.org/wiki/Merkabah_mysticism" },
    ],
    links: ["drunvalo-melchizedek", "light-body-ascension", "ascension", "sacred-geometry"],
  },
  {
    id: "drunvalo-melchizedek",
    label: "Drunvalo Melchizedek",
    category: "consciousness",
    weight: 3,
    desc: "Author and teacher of the 'Flower of Life' workshops and merkaba meditation. Within the narrative, Melchizedek is the primary modern conveyor of the sacred-geometry / merkaba / ascension teachings, which he claims were passed to him by Thoth (Hermes Trismegistus) and the ascended masters. His 'Ancient Secret of the Flower of Life' is a foundational text of the spiritual-ascension wing of the map.",
    sources: [
      { label: "Drunvalo Melchizedek — Wikipedia", url: "https://en.wikipedia.org/wiki/Drunvalo_Melchizedek" },
    ],
    links: ["star-merkaba", "sacred-geometry", "light-body-ascension", "ascension"],
  },
  {
    id: "lucid-dream",
    label: "Lucid Dreaming",
    category: "consciousness",
    weight: 3,
    desc: "The practice of becoming conscious within a dream and directing its content. Within the narrative, lucid dreaming is described as a training ground for astral travel, a gateway to the Tibetan dream yoga practices, and a method of direct communication with the Higher Self and ET groups. Said to be one of the safest ways to begin multidimensional exploration.",
    links: ["astral-travel", "tibetan-dream-yoga", "oversoul", "ascension"],
  },
  {
    id: "astral-travel",
    label: "Astral Travel / Astral Projection",
    category: "consciousness",
    weight: 4,
    desc: "The claimed ability to separate the 'astral body' (a subtle energetic vehicle) from the physical body and travel to other locations on Earth, in the solar system, in higher dimensions, or in the inner-Earth. Within the narrative, astral travel is a learnable skill (via lucid dreaming, plant medicines, breathwork, merkaba practice) used to visit SSP bases, inner-Earth civilizations, and to communicate directly with ET groups outside the constraints of physicality.",
    links: ["lucid-dream", "star-merkaba", "remote-viewing", "oversoul", "star-children"],
  },
  {
    id: "remote-viewing",
    label: "Remote Viewing",
    category: "consciousness",
    weight: 4,
    desc: "A protocol developed by the U.S. military (SRI / DIA's 'Project Stargate,' 1978–1995) for perceiving distant or hidden targets via extrasensory perception. Within the narrative, remote viewing is treated as proven, weaponizable, and suppressed. Practitioners like Ingo Swann, Joseph McMoneagle, and Gerald O'Donnell are cited as having viewed SSP bases, ET civilizations, and inner-Earth civilizations — confirming the broader narrative.",
    sources: [
      { label: "Remote viewing — Wikipedia", url: "https://en.wikipedia.org/wiki/Remote_viewing" },
      { label: "Stargate Project — Wikipedia", url: "https://en.wikipedia.org/wiki/Stargate_Project" },
    ],
    links: ["astral-travel", "pineal-gland", "ssp-researchers", "secret-space-program"],
  },
  {
    id: "gerald-odonnell",
    label: "Gerald O'Donnell",
    category: "consciousness",
    weight: 2,
    desc: "A remote-viewing instructor and founder of the Academy of Remote Viewing and Remote Influencing. Within the narrative, O'Donnell's protocols are cited as a civilian-accessible form of the military remote-viewing training, and his remote-viewing sessions are described as having independently confirmed the SSP / inner-Earth / ET elements of the broader story.",
    links: ["remote-viewing", "astral-travel", "pineal-gland"],
  },
  {
    id: "qhht",
    label: "QHHT (Dolores Cannon)",
    category: "consciousness",
    weight: 4,
    desc: "Quantum Healing Hypnosis Technique — a past-life regression and channeling method developed by Dolores Cannon. Within the narrative, QHHT sessions are a primary channel through which the Higher Self, Oversoul, and positive ET groups communicate with humanity. Cannon's books ('The Convoluted Universe,' 'The Three Waves of Volunteers,' 'Jesus and the Essenes') are foundational to the spiritual-ascension wing of the map.",
    sources: [
      { label: "Dolores Cannon — Wikipedia", url: "https://en.wikipedia.org/wiki/Dolores_Cannon" },
    ],
    links: ["dolores-cannon", "past-life-regression", "channeling", "oversoul", "star-children"],
  },
  {
    id: "dolores-cannon",
    label: "Dolores Cannon",
    category: "consciousness",
    weight: 3,
    desc: "Hypnotherapist and author (1931–2014) who developed QHHT and published extensively on past-life regression, ET contact, and the 'three waves of volunteers' (souls who incarnated on Earth specifically to assist with the ascension). Within the narrative, Cannon is one of the most respected and cited spiritual researchers.",
    links: ["qhht", "past-life-regression", "star-children", "channeling"],
  },
  {
    id: "past-life-regression",
    label: "Past Life Regression",
    category: "consciousness",
    weight: 3,
    desc: "Hypnotic induction to access memories of past incarnations. Within the narrative, past-life regression (especially via QHHT) is the primary evidence for reincarnation, the soul's continuity across incarnations, and the existence of the Oversoul that plans each life. Sessions frequently surface past lives as ET beings, Atlanteans, or inner-Earth civilizations — taken as confirmation of the broader cosmology.",
    links: ["qhht", "dolores-cannon", "oversoul", "reincarnation"],
  },
  {
    id: "reincarnation",
    label: "Reincarnation Cycle",
    category: "consciousness",
    weight: 3,
    desc: "Within the narrative, souls incarnate repeatedly on Earth (and elsewhere) across thousands of lifetimes to polarize (service-to-others vs service-to-self) and graduate to higher densities. The cabal / Draco / Moon-Matrix are said to have hijacked the reincarnation cycle — using the Moon as a soul-catcher (per John Lear) to wipe memories between lives and trap souls in 3D. The Great Solar Flash is described as breaking this cycle.",
    links: ["past-life-regression", "moon-soul-catcher", "saturn-moon-matrix", "oversoul", "ascension"],
  },
  {
    id: "orbs",
    label: "Orbs (Anomalous Light Phenomena)",
    category: "consciousness",
    weight: 2,
    desc: "Within the narrative, the glowing orbs frequently photographed in meditation circles, nature, and haunted locations are described as: (a) non-physical ET / interdimensional beings observing humanity, (b) fragments of consciousness from the astral plane, or (c) the Blue Orb beings of the Sphere Being Alliance. Distinguished from dust-moisture lens artifacts by the community.",
    links: ["sphere-being-alliance", "astral-travel", "channeling", "blue-avians"],
  },
  {
    id: "lightworkers",
    label: "Lightworkers",
    category: "spiritual",
    weight: 4,
    desc: "Within the narrative, souls who have incarnated on Earth specifically to assist with the planetary ascension — raising collective vibration through healing, teaching, art, and energetic work. Said to be 5D-and-above souls who volunteered for difficult Earth incarnations. Lightworkers are described as the human counterparts to the off-world positive ET groups, working in tandem.",
    links: ["star-children", "indigos", "wanderers", "first-wave-volunteers", "ascension"],
  },
  {
    id: "star-children",
    label: "Star Children / Star Seeds",
    category: "spiritual",
    weight: 4,
    desc: "Within the narrative, souls who have incarnated on Earth but whose Oversoul originated in an ET civilization (Pleiadian, Sirian, Arcturian, Andromedan, Essassani, etc.). Star children are said to incarnate to: (a) assist with ascension, (b) bridge ET and human consciousness, (c) bring in new energetic frequencies. Often described as feeling 'alien' in human society, drawn to the stars, and possessing dormant ET abilities.",
    links: ["lightworkers", "indigos", "wanderers", "first-wave-volunteers", "hybrid-races", "pleiadians"],
  },
  {
    id: "wanderers",
    label: "Wanderers",
    category: "spiritual",
    weight: 3,
    desc: "A term from the Law of One: 6th-density souls who voluntarily incarnate into 3rd-density Earth to assist with the harvest / ascension, accepting the risk of getting trapped here themselves. Within the narrative, Wanderers are the most advanced of the volunteer souls — older and more cosmically experienced than the typical star child. Said to number ~65 million on Earth.",
    links: ["lightworkers", "star-children", "law-of-one", "ra", "first-wave-volunteers"],
  },
  {
    id: "indigos",
    label: "Indigo Children",
    category: "spiritual",
    weight: 3,
    desc: "Within the narrative, children incarnating since the 1970s (and especially since 2000) with an 'indigo' aura, advanced intuitive abilities, resistance to authority, and a specific mission to break down the old control systems. Described as the energetic vanguard of the new consciousness. The term comes from Nancy Ann Tappe's aura work and was popularized by Lee Carroll & Jan Tober.",
    sources: [
      { label: "Indigo children — Wikipedia", url: "https://en.wikipedia.org/wiki/Indigo_children" },
    ],
    links: ["star-children", "lightworkers", "dna-upgrade", "crystal-children"],
  },
  {
    id: "crystal-children",
    label: "Crystal Children",
    category: "spiritual",
    weight: 2,
    desc: "Within the narrative, the wave of children incarnating since ~2000 who are described as even more energetically refined than Indigos — operating from a 'crystal' (clear, high-frequency) aura, telepathic from birth, and resistant to the 3D control systems entirely. Said to be the second wave after the Indigos, here to anchor the 5D frequency.",
    links: ["indigos", "star-children", "dna-upgrade", "ascension"],
  },
  {
    id: "first-wave-volunteers",
    label: "1st / 2nd / 3rd Wave Volunteers",
    category: "spiritual",
    weight: 3,
    desc: "Dolores Cannon's framework: three 'waves' of volunteer souls incarnated on Earth to assist with the ascension. The 1st wave (post-WWII) had the hardest time — they found 3D Earth unbearably dense. The 2nd wave (1960s–80s) came to support the 1st wave and begin the awakening. The 3rd wave (1990s–2010s) are the 'wayshowers' — born already-awake, with activated DNA, ready to lead humanity through the Event.",
    links: ["dolores-cannon", "qhht", "star-children", "lightworkers", "wanderers"],
  },
  {
    id: "sungazing",
    label: "Sun Gazing",
    category: "spiritual",
    weight: 3,
    desc: "The practice of staring at the sun during the first/last hour of daylight (when UV is low) to absorb prana and activate the pineal gland. Within the narrative, sungazing is described as a primary method of pineal activation, DNA upgrade, and direct energetic communion with the Sun-being (Sol) — preparing the practitioner for the Great Solar Flash. HRM (Hira Ratan Manek) is the most cited modern proponent.",
    links: ["pineal-gland", "prana", "electric-sun", "great-solar-flash", "decalcify"],
  },
  {
    id: "432hz",
    label: "432 Hz Tuning",
    category: "spiritual",
    weight: 3,
    desc: "Within the narrative, 432 Hz is the natural, mathematically-sacred tuning frequency of the universe (connected to the Schumann Resonance, the precessional cycle, and sacred geometry), suppressed when standard music tuning was moved to 440 Hz (a 'disharmonious' frequency imposed by the cabal, sometimes attributed to the Rockefeller Foundation and the Nazi regime). Music tuned to 432 Hz is described as healing and consciousness-raising.",
    links: ["vibration-frequency", "schumann-resonance", "cymatics", "sacred-geometry", "sound-healing"],
  },
  {
    id: "cymatics",
    label: "Cymatics",
    category: "spiritual",
    weight: 3,
    desc: "The study of visible sound — patterns formed by particles/liquids on a vibrating plate. Within the narrative, cymatics is cited as the experimental proof that frequency structures matter, that 432 Hz / sacred frequencies produce sacred geometry in physical media, and that the cabal's disharmonic frequencies are deliberately chosen to disrupt human bio-fields.",
    sources: [
      { label: "Cymatics — Wikipedia", url: "https://en.wikipedia.org/wiki/Cymatics" },
    ],
    links: ["432hz", "sacred-geometry", "sound-healing", "vibration-frequency"],
  },
  {
    id: "crystals",
    label: "Crystals",
    category: "spiritual",
    weight: 3,
    desc: "Within the narrative, crystals (quartz, amethyst, citrine, etc.) are described as information-storage devices, energy amplifiers, and consciousness interfaces — the literal hardware of the Ancient Builder Race's technology (crystalline towers on the Moon, crystal skulls, Atlantean power crystals). Personal use of crystals for healing, programming intentions, and amplifying meditation is treated as a practical application of the same physics.",
    links: ["cymatics", "sacred-geometry", "ancient-builder-race", "moon", "atlantis"],
  },
  {
    id: "sacred-geometry",
    label: "Sacred Geometry (Amplihedron)",
    category: "spiritual",
    weight: 3,
    desc: "Within the narrative, the universe is structured on geometric templates — the Flower of Life, the Platonic solids, the Fibonacci sequence, the 'amplihedron' (64-tetrahedron grid) — which are the literal blueprints of creation. Nassim Haramein's work is cited as the modern physics formulation. Mastery of sacred geometry is described as the key to merkaba activation, free energy, and conscious manifestation.",
    links: ["star-merkaba", "drunvalo-melchizedek", "19.5", "cymatics", "crystals"],
  },
  {
    id: "yoga",
    label: "Yoga",
    category: "consciousness",
    weight: 3,
    desc: "Within the narrative, yoga is treated not as exercise but as an ascension technology — the asanas open chakras, the breathwork (pranayama) raises vibration, the meditation quiets the ego-mind to receive Higher-Self communication. Said to be one of the surviving 'technologies' from the Vedic / Atlantean civilizations, preserved through the yogic lineages of India.",
    links: ["chakras", "kundalini-awakening", "prana", "ascension"],
  },
  {
    id: "aura",
    label: "Auras",
    category: "consciousness",
    weight: 3,
    desc: "The claimed electromagnetic / subtle-energy field surrounding the body, visible (with practice or with Kirlian photography) as a colored halo corresponding to the state of the chakras. Within the narrative, the aura is the bio-energetic signature of one's vibration — readable by sensitive individuals, by ET groups, and by the cabal's surveillance technology. 'Reading auras' is a learnable skill.",
    links: ["chakras", "pineal-gland", "raising-vibration", "third-eye"],
  },
  {
    id: "psychic-healing",
    label: "Psychic Healing / Hands-On Healing",
    category: "consciousness",
    weight: 3,
    desc: "Within the narrative, healing via the laying-on of hands, Reiki, pranic healing, or directed intention is described as the redirection of universal life-force energy (prana, chi, orgone) through the healer's chakra system into the patient. Said to work by restoring the patient's bio-field, unblocking chakras, and raising their vibration. Reiki, Barbara Brennan's 'Hands of Light,' and Pranic Healing are the most cited schools.",
    links: ["aura", "chakras", "prana", "orgone", "holistic-healing"],
  },
  {
    id: "prana",
    label: "Prana / Chi / Life Force",
    category: "consciousness",
    weight: 3,
    desc: "The universal life-force energy known in Sanskrit as prana, in Chinese as chi/qi, in Hawaiian as mana, in Wilhelm Reich's work as orgone. Within the narrative, prana is the literal substance of consciousness and the energy that animates matter. Breathwork, sungazing, nature exposure, and diet are all framed as methods of accumulating prana. Mastery of prana is described as the foundation of all ascension and healing practices.",
    links: ["orgone", "breatharian", "yoga", "kundalini-awakening", "psychic-healing"],
  },
  {
    id: "breatharian",
    label: "Breatharianism / Fasting",
    category: "consciousness",
    weight: 2,
    desc: "Within the narrative, advanced practitioners can sustain themselves on prana / chi alone (inedia), reducing or eliminating the need for physical food. Cited practitioners include HRM (sun gazer), Jasmuheen, and Wiley Brooks. Fasting is described as both a pineal-decalcification method and a vibration-raising method. Treated as evidence that the body can be sustained by frequency alone — a foretaste of light-body existence.",
    links: ["prana", "sungazing", "pineal-gland", "light-body-ascension"],
  },
  {
    id: "psychedelia",
    label: "Psychedelia (LSD / Ayahuasca / DMT)",
    category: "consciousness",
    weight: 4,
    desc: "Within the narrative, psychedelics — especially DMT, ayahuasca, psilocybin, and LSD — are described as pineal-gland activators and direct portals to higher dimensions. Terence McKenna's 'archaic revival' is cited: psychedelics are the original human sacrament, suppressed by the cabal because they dissolve programming and reconnect the user to nature / ET contact / the Oversoul. DMT is specifically described as the chemical mechanism of natural near-death and astral-travel experiences.",
    sources: [
      { label: "Terence McKenna — Wikipedia", url: "https://en.wikipedia.org/wiki/Terence_McKenna" },
    ],
    links: ["pineal-gland", "third-eye", "astral-travel", "shamans", "david-wilcock"],
  },
  {
    id: "shamans",
    label: "Shamans & Ancestral Spirits",
    category: "consciousness",
    weight: 3,
    desc: "Within the narrative, indigenous shamans (Amazonian ayahuasqueros, Huichol mara'akames, Mongolian shamans, African sangomas) are described as the longest-continuous lineage of multidimensional practitioners — using plant medicines, drumming, and ceremony to access the astral plane, communicate with ET groups, retrieve soul fragments, and heal. Their knowledge is treated as an unbroken line back to Atlantis / pre-catastrophe civilizations.",
    links: ["psychedelia", "ayahuasca", "astral-travel", "ancient-aliens", "channeling"],
  },
  {
    id: "ayahuasca",
    label: "Ayahuasca",
    category: "consciousness",
    weight: 3,
    desc: "A psychoactive brew used by Amazonian shamans (containing DMT and an MAOI). Within the narrative, ayahuasca is described as a 'plant teacher' that opens direct contact with the Oversoul, ET groups, plant spirits, and ancestral beings — and as a powerful healing / trauma-release modality. Said to be one of the most reliable methods of triggering a personal awakening. The 'grandmother' of all plant medicines.",
    links: ["psychedelia", "shamans", "pineal-gland", "third-eye", "ascension"],
  },
  {
    id: "fairies-mermaids",
    label: "Fairies, Mermaids, Elementals",
    category: "consciousness",
    weight: 2,
    desc: "Within the narrative, the 'mythological' beings of folklore — fairies, elves, mermaids, sylphs, gnomes, undines, salamanders — are described as real nature spirits / 4D elementals that humanity has lost the capacity to perceive due to pineal calcification. Said to be re-perceivable once the third eye is activated. Linked to the inner-Earth civilizations and to the Ancient Builder Race's nature-custodian programs.",
    links: ["pineal-gland", "third-eye", "inner-earth-civilizations", "ancient-builder-race"],
  },
  {
    id: "dinosaurs",
    label: "Dinosaurs / Darwinism Critique",
    category: "consciousness",
    weight: 2,
    desc: "Within the narrative, mainstream Darwinian evolution is described as 'stepped evolution propaganda' — a partial truth used to obscure the reality of intelligent design (by the Annunaki / Ancient Builder Race), ET genetic manipulation, and the cyclical-cataclysm model of Earth history. Dinosaurs are described as either an earlier ET terraforming experiment or as coexisting with humanity far more recently than mainstream science admits.",
    links: ["darwinism", "annunaki", "ancient-aliens", "stepped-evolution"],
  },
  {
    id: "darwinism",
    label: "Darwinism / Evolution Propaganda",
    category: "consciousness",
    weight: 2,
    desc: "Within the narrative, the theory of evolution by natural selection is described as a deliberately promoted materialist doctrine that obscures humanity's true origins (genetic engineering by ET groups), consciousness's role in evolution, and the cyclical-cataclysm nature of Earth history. Treated as one of the cabal's core 'programming' doctrines, alongside heliocentrism skepticism in flat-earth variants.",
    links: ["dinosaurs", "annunaki", "ancient-aliens", "kill-your-tv"],
  },
  {
    id: "stepped-evolution",
    label: "Stepped Evolution Critique",
    category: "consciousness",
    weight: 2,
    desc: "Within the narrative, the 'sudden appearance' of new species in the fossil record (the 'Cambrian explosion,' the sudden appearance of Homo sapiens) is cited as evidence that evolution is not gradual but punctuated — by ET genetic intervention. The 'missing links' are described as nonexistent because there are no links — each major species was introduced by an ET terraforming group.",
    links: ["darwinism", "dinosaurs", "annunaki", "22-et-experiments"],
  },
  {
    id: "empty-awareness",
    label: "Empty Awareness / Omnipresence",
    category: "spiritual",
    weight: 3,
    desc: "The 'highest realm' on the spiritual wing of the map — described as the state beyond all densities, polarities, and forms: pure empty awareness, omniscience, omnipotence, omnipresence. Identified with the Tao (Tao Te Ching), Rigpa (Dzogchen), the Dharmakaya (Buddhism), and the 'One Infinite Creator' (Law of One). The state realized by enlightened beings and the destination of the most advanced souls.",
    links: ["one-infinite-creator", "dzogchen-rigpa", "higher-realms", "tao-te-ching", "ascension"],
  },
  {
    id: "higher-realms",
    label: "Higher Realms / Buddhafields",
    category: "spiritual",
    weight: 3,
    desc: "Within the narrative, the higher dimensions (5D and above) are described as 'Buddhafields' — pure lands of consciousness where beings reside in unified awareness, free from the duality and limitation of 3D. Said to be accessible via deep meditation, astral travel, merkaba work, and psychedelics. The destination of ascending souls. Identified with the Buddhist pure lands, the Theosophical 'devachan,' and the Ra Material's higher densities.",
    links: ["empty-awareness", "dzogchen-rigpa", "ascension", "5d-earth", "law-of-one"],
  },
  {
    id: "tao-te-ching",
    label: "Tao Te Ching",
    category: "spiritual",
    weight: 2,
    desc: "Lao Tzu's foundational Taoist text. Within the narrative, the Tao Te Ching is described as 'the gateway to all understanding' — the most accessible surviving text on the Empty Awareness / One Infinite Creator principle. Taoism is treated as one of the unbroken lineages back to the Ancient Builder Race / pre-catastrophe consciousness teachings.",
    links: ["empty-awareness", "higher-realms", "dzogchen-rigpa", "ascension"],
  },
  {
    id: "densities",
    label: "Densities (3D → 7D+ Model)",
    category: "spiritual",
    weight: 4,
    desc: "From the Law of One: eight 'densities' or 'octaves' of consciousness, each ~75,000 years long for 3D, each a graduation of awareness. 1D=elements/minerals, 2D=plants/animals, 3D=humanity (self-aware, choice of polarity), 4D=love/understanding (positive or negative), 5D=light/wisdom, 6D=love-wisdom unified, 7D=the gateway, 8D=the octave restart. Within the narrative, Earth is graduating from 3D to 4D-positive, and the Great Solar Flash is the graduation event.",
    links: ["law-of-one", "ascension", "5d-earth", "ra", "service-to-others", "one-infinite-creator"],
  },
  {
    id: "transcendental-object",
    label: "Transcendental Object at End of Time",
    category: "spiritual",
    weight: 2,
    desc: "Terence McKenna's concept: a hyperdimensional 'attractor' at the end of history that pulls all of evolution toward it — described by him as the eschaton, the concrescence of novelty. Within the narrative, this is identified with the Great Solar Flash, the Event, and the Omega Point of Teilhard de Chardin — the singularity toward which all of cosmic history is converging.",
    links: ["great-solar-flash", "the-event", "ascension", "psychedelia"],
  },
  {
    id: "elastic-time-space",
    label: "Elastic Time/Space",
    category: "spiritual",
    weight: 2,
    desc: "Within the narrative, time and space are not fixed but elastic and multidimensional — accessible via remote viewing, astral travel, jumpgates, and consciousness. Cited as the physics behind the '20-and-back' program, the time-bubble sanctuaries on Saturn, and the ability of higher-density beings to perceive all of time simultaneously. Linked to the multidimensional travel practices of Tibetan dream yoga.",
    links: ["multidimensional-travel", "remote-viewing", "astral-travel", "jumpgate-portals", "law-of-one"],
  },
  {
    id: "multidimensional-travel",
    label: "Multidimensional Travel",
    category: "spiritual",
    weight: 3,
    desc: "Within the narrative, consciousness is not bound to 3D spacetime — through astral travel, merkaba work, psychedelics, remote viewing, and dream yoga, one can visit any density, any location, and any timeline. Described as a birthright ability, suppressed only by pineal calcification and cultural conditioning. Said to be the way higher-density beings communicate with humanity.",
    links: ["astral-travel", "elastic-time-space", "star-merkaba", "remote-viewing", "tibetan-dream-yoga"],
  },
  {
    id: "raising-vibration",
    label: "Raising Your Vibration",
    category: "spiritual",
    weight: 4,
    desc: "Within the narrative, the central practice of personal ascension: raising one's base frequency to match 4D/5D. Methods include meditation, forgiveness, service-to-others, healthy diet, decalcification, sungazing, time in nature, gratitude, breathwork, and detoxification from media / EMF / loosh-harvest cycles. Described as both the goal and the mechanism — you ascend by being more loving, and being more loving raises you.",
    links: ["ascension", "vibration-frequency", "great-solar-flash", "service-to-others", "schumann-resonance"],
  },
  {
    id: "tibetan-dream-yoga",
    label: "Tibetan Dream Yoga",
    category: "spiritual",
    weight: 2,
    desc: "A Vajrayana Buddhist practice of using the dream state for spiritual realization. Within the narrative, dream yoga is described as the most rigorous surviving training for lucid dreaming, astral travel, and conscious death — and as the method by which Tibetan monks prepare for the bardo (the post-death state) and ultimately for the rainbow body. Said to be a key human-accessible ascension technology.",
    links: ["lucid-dream", "astral-travel", "dzogchen-rigpa", "tibetan-rainbow-body", "padmasambhava"],
  },
  {
    id: "tibetan-buddhism",
    label: "Tibetan Buddhism (Secret Teachings)",
    category: "spiritual",
    weight: 3,
    desc: "Within the narrative, Tibetan Buddhism — and especially the Dzogchen / Mahamudra / Vajrayana lineages — is described as the most intact surviving lineage of the ancient ascension teachings. The Tibetan rainbow body realization is treated as documented proof of ascension, the bardo thodol (Tibetan Book of the Dead) as a guidebook to the post-death transition, and the terma tradition as evidence of hidden teachings left by Padmasambhava for our time.",
    links: ["tibetan-rainbow-body", "dzogchen-rigpa", "padmasambhava", "tibetan-dream-yoga", "ascension"],
  },
  {
    id: "divine-downloads",
    label: "Divine Downloads",
    category: "spiritual",
    weight: 2,
    desc: "Within the narrative, sudden bursts of information received telepathically from one's Higher Self, Oversoul, or positive ET groups — described as 'downloads' of insight, technical knowledge, mission briefings, or future-forecasts. Said to occur most readily during meditation, in nature, in the dream state, or after a significant energy upgrade (e.g., a kundalini awakening).",
    links: ["oversoul", "channeling", "higher-self", "raising-vibration"],
  },
];
