import type { GAMNode } from "./types";

// SECRET SPACE PROGRAM — the claimed hidden space infrastructure
export const SSP_NODES: GAMNode[] = [
  {
    id: "secret-space-program",
    label: "Secret Space Program (SSP)",
    category: "ssp",
    weight: 5,
    desc: "The central claim of this whole branch: that since the mid-20th century, a parallel, highly classified space program has existed entirely separate from NASA, using reverse-engineered extraterrestrial technology and antigravity craft. Said to involve multiple factions (Solar Warden, Dark Fleet, ICC, Global Galactic League of Nations, Earth Alliance) operating across the solar system and beyond, with bases on the Moon, Mars, and in outer-atmosphere facilities. Whistleblowers (William Tompkins, Corey Goode, Tony Rodriguez) describe a '20-and-back' service cycle with age-regression and memory wipes.",
    sources: [
      { label: "Gaia: Cosmic Disclosure", url: "https://www.gaia.com/series/cosmic-disclosure" },
    ],
    links: ["micssp", "solar-warden", "dark-fleet", "icc", "earth-alliance", "ssp-alliance", "tr3b", "antigravity", "loc", "20-and-back", "william-tompkins", "corey-goode"],
  },
  {
    id: "micssp",
    label: "MICSSP (Military-Industrial Complex SSP)",
    category: "ssp",
    weight: 4,
    desc: "The lower-level, publicly-denied space program run by the conventional military-industrial complex. Said to be what most people inside classified aerospace believe is 'the' secret space program — limited to low-Earth-orbit operations, the TR-3B, and conventional (non-antigravity) advanced craft. Described as a compartmentalized lower tier that doesn't know about the deeper SSP factions.",
    links: ["secret-space-program", "tr3b", "compartmentalized-programs", "usa-military"],
  },
  {
    id: "solar-warden",
    label: "Solar Warden",
    category: "ssp",
    weight: 4,
    desc: "An alleged secret U.S. Navy space fleet said to patrol the solar system, operating since the 1980s. First publicly surfaced in 2002 when hacker Gary McKinnon claimed to find a 'non-terrestrial officer' roster and 'Solar Warden' fleet listings on U.S. military computers. Described within the narrative as one of the original SSP factions, using antigravity battlecruisers. Later said to have been merged into the SSP Alliance.",
    sources: [
      { label: "Gary McKinnon hacking case (Wikipedia)", url: "https://en.wikipedia.org/wiki/Gary_McKinnon" },
    ],
    links: ["secret-space-program", "ssp-alliance", "gary-mckinnon", "antigravity"],
  },
  {
    id: "dark-fleet",
    label: "Dark Fleet",
    category: "ssp",
    weight: 4,
    desc: "Described as a Nazi-originated offensive space fleet operating beyond the solar system, 'similar to the Empire in Star Wars — conquer and control entire star systems.' Said to operate under a Nazi command structure, use human slave labor, work alongside the Draco & Reptilian Alliance, and be based out of Ceres, Saturn, and Antarctic underground facilities. Whistleblower Tony Rodriguez describes being abducted into 20-and-back service on a Dark Fleet vessel (the '20-and-back program').",
    links: ["secret-space-program", "nazi-breakaway", "draco-alliance", "orion-syndicate", "tony-rodriguez", "ceres-base", "saturn", "human-slave-labor"],
  },
  {
    id: "icc",
    label: "Interplanetary Corporate Conglomerate (ICC)",
    category: "ssp",
    weight: 4,
    desc: "Described as the corporate wing of the SSP — a conglomerate of off-world aerospace corporations that has 'established intergalactic trade with 900+ extraterrestrial races.' Runs ICC bases on Mars (using human slave labor), in the upper atmosphere of Venus, and elsewhere. Within the narrative, the ICC is the faction that monetizes SSP technology and supplies Dark Fleet with hardware and personnel. Tied to Earth-side defense contractors like Northrop Grumman, Douglas Aircraft, TRW.",
    links: ["secret-space-program", "dark-fleet", "mars", "venus", "human-slave-labor", "micssp", "icc-bases-mars"],
  },
  {
    id: "earth-alliance",
    label: "Earth Alliance",
    category: "ssp",
    weight: 4,
    desc: "Described as a positive faction of white-hat military, intelligence, and financial operatives working inside the cabal's own institutions to take it down from within. The Earth Alliance is said to be coordinating mass arrests of the cabal, the financial reset, and Full Disclosure, in alliance with the SSP Alliance and positive ET groups (Pleiadians). Within the narrative, Trump, Space Force, and the Q operation are presented as Earth Alliance projects.",
    links: ["secret-space-program", "ssp-alliance", "full-disclosure", "qanon", "trump", "space-force", "white-hats", "white-dragon-society"],
  },
  {
    id: "ssp-alliance",
    label: "SSP Alliance",
    category: "ssp",
    weight: 4,
    desc: "A faction described as defectors from across the SSP factions (Solar Warden, ICC, Global Galactic League) who joined forces to force Full Disclosure. Within the narrative, the SSP Alliance works with the Sphere Being Alliance (Blue Avians) and the Earth Alliance. Said to have been responsible for leaking SSP data to whistleblowers like Corey Goode.",
    links: ["secret-space-program", "sphere-being-alliance", "earth-alliance", "full-disclosure", "corey-goode"],
  },
  {
    id: "global-galactic-league",
    label: "Global Galactic League of Nations",
    category: "ssp",
    weight: 3,
    desc: "Described as an SSP faction formed in the 1990s as a UN-style 'galactic UN' consortium of Earth nations (beyond the U.S.-led MICSSP). Said to operate smaller craft, be relatively benign, and exist so that non-U.S. nations have a stake in the SSP. Within the narrative, this is the faction that maintains the appearance of international cooperation in space.",
    links: ["secret-space-program", "micssp", "galactic-un"],
  },
  {
    id: "tr3b",
    label: "TR-3B Astra",
    category: "ssp",
    weight: 3,
    desc: "A rumored triangular antigravity craft allegedly developed by the U.S. Air Force under black-project budget lines. Described within the narrative as a 'black wedge and pumpkin seed shape craft' servicing low-Earth-orbit space stations. Frequently cited as the explanation for the black-triangle UFO sightings reported worldwide since the 1990s.",
    sources: [
      { label: "Black triangle (UFO) — Wikipedia", url: "https://en.wikipedia.org/wiki/Black_triangle_(UFO)" },
    ],
    links: ["secret-space-program", "micssp", "antigravity", "black-wedge-craft"],
  },
  {
    id: "antigravity",
    label: "Antigravity",
    category: "tech",
    weight: 4,
    desc: "The foundational suppressed technology of the SSP: the ability to nullify or reverse gravity. Within the narrative, antigravity has been operational since the 1940s (via the Nazi Bell and Vril craft), was reverse-engineered from ET craft, and is the basis of all SSP propulsion. Said to be withheld from humanity by the cabal because it would collapse the petroleum economy and the cabal's control structure.",
    links: ["secret-space-program", "nazi-bell", "free-energy", "tr3b", "reverse-engineering-ufos"],
  },
  {
    id: "compartmentalized-programs",
    label: "Compartmentalized Programs",
    category: "ssp",
    weight: 3,
    desc: "The claim that secret programs are structured so that no single person knows the full picture — each worker knows only their compartment. Used within the narrative to explain why most people inside aerospace and intelligence genuinely don't know the SSP exists, even though they work on pieces of it. 'Need-to-know' is treated as the cabal's primary mechanism of secrecy.",
    links: ["secret-space-program", "micssp", "deep-state"],
  },
  {
    id: "loc",
    label: "Lunar Operations Command (LOC)",
    category: "ssp",
    weight: 4,
    desc: "Described as the primary SSP base on the Moon — a multilevel facility on the far side serving as command, control, and diplomatic hub. Within the narrative, the LOC has three known levels (LOC 1, LOC 2, LOC 3), houses the 'Galactic U.N.' diplomatic zone, and connects via underground shuttles to other lunar bases. Corey Goode describes being processed through the LOC on his way to 20-and-back service.",
    links: ["secret-space-program", "moon", "galactic-un", "underground-bases", "corey-goode"],
  },
  {
    id: "apollo-coverup",
    label: "Apollo Moon Landings (Cover-up Claim)",
    category: "ssp",
    weight: 3,
    desc: "Within the narrative, the Apollo missions are described as a public-facing 'cover story' that occurred alongside a much larger, classified lunar program. The public landings are said to have been permitted only after the SSP had already established the LOC; astronauts were briefed on ET presence and warned not to disclose. Some variants claim parts of the Apollo footage were staged by Stanley Kubrick (see 'Stanley Kubrick / The Shining').",
    links: ["secret-space-program", "loc", "moon", "stanley-kubrick", "nasa-coverup"],
  },
  {
    id: "william-tompkins",
    label: "William Tompkins",
    category: "ssp",
    weight: 3,
    desc: "A self-described aerospace engineer who claimed in a series of interviews (shortly before his 2017 death) to have designed kilometer-long spacecraft for the U.S. Navy in the 1950s–60s under a 'think tank' at Douglas Aircraft, working from data supplied by Nordic (Pleiadian) ET spies embedded in Nazi Germany. Within the narrative, Tompkins is the senior-most insider to confirm the SSP's post-WWII origins.",
    sources: [
      { label: "William Tompkins (Wikipedia)", url: "https://en.wikipedia.org/wiki/William_Mills_Tompkins" },
    ],
    links: ["secret-space-program", "douglas-aircraft", "reverse-engineering-ufos", "ricco-botta", "nordics"],
  },
  {
    id: "corey-goode",
    label: "Corey Goode",
    category: "ssp",
    weight: 4,
    desc: "The most prominent contemporary SSP whistleblower. Claims to have been drafted into a '20-and-back' tour with Solar Warden at age 6 via the MILAB program, served as an 'intuitive empath' in delegations between SSP factions and ET groups, and was later re-contacted by the Blue Avians / Sphere Being Alliance as their 'messenger.' His testimony forms the backbone of Gaia's 'Cosmic Disclosure' series and much of the modern SSP narrative.",
    sources: [
      { label: "Corey Goode — Wikipedia", url: "https://en.wikipedia.org/wiki/Corey_Goode" },
    ],
    links: ["secret-space-program", "solar-warden", "sphere-being-alliance", "blue-avians", "milab", "20-and-back", "david-wilcock", "cosmic-disclosure"],
  },
  {
    id: "tony-rodriguez",
    label: "Tony Rodriguez",
    category: "ssp",
    weight: 3,
    desc: "A Dark Fleet whistleblower who claims to have served a 20-and-back tour aboard a Dark Fleet vessel under Draco command, in human slave labor roles. His testimony, publicized alongside Corey Goode's, describes the brutal conditions inside Dark Fleet and the Draco's treatment of human crew.",
    links: ["dark-fleet", "secret-space-program", "20-and-back", "draco-alliance", "corey-goode"],
  },
  {
    id: "ricco-botta",
    label: "Adm. Rico Botta",
    category: "ssp",
    weight: 2,
    desc: "A real U.S. Navy Vice Admiral (1890–1992) who, in the Tompkins narrative, is described as having overseen the infiltration of Nazi Germany by embedded U.S. spies (1942–1946), the recovery of Nazi ARVs (alien reproduction vehicles), and the seeding of U.S. aerospace companies with reverse-engineered ET designs.",
    links: ["secret-space-program", "william-tompkins", "reverse-engineering-ufos"],
  },
  {
    id: "bobby-ray-inman",
    label: "Bobby Ray Inman",
    category: "ssp",
    weight: 2,
    desc: "A real U.S. Navy Admiral and former NSA/CIA deputy director who, within the SSP narrative, is named as a central figure in the MJ-12 / Majestic control structure that ran the UFO cover-up and managed the SSP from its inception.",
    links: ["secret-space-program", "mj12", "deep-state"],
  },
  {
    id: "gary-mckinnon",
    label: "Gary McKinnon",
    category: "ssp",
    weight: 3,
    desc: "A Scottish hacker who, between 2001 and 2002, infiltrated 97 U.S. military and NASA computers searching for UFO evidence. Claims to have found a 'non-terrestrial officer' roster, lists of Navy ship-to-ship transfers including the Solar Warden, and 'off-world' cargo manifests. His case became a cause célèbre in the SSP community and is treated as primary evidence for Solar Warden's existence.",
    sources: [
      { label: "Gary McKinnon (Wikipedia)", url: "https://en.wikipedia.org/wiki/Gary_McKinnon" },
    ],
    links: ["solar-warden", "secret-space-program", "nasa-coverup"],
  },
  {
    id: "reverse-engineering-ufos",
    label: "Reverse-Engineering UFOs",
    category: "ssp",
    weight: 4,
    desc: "The claim that all advanced aerospace technology since WWII — from stealth to microchips to fiber optics to antigravity — was reverse-engineered from crashed ET craft (Roswell, Kecksburg, etc.). Within the narrative, recovered craft were distributed to defense contractors (Douglas, TRW, North American Aviation, Northrop Grumman) for study, with the results feeding both the MICSSP and the deeper SSP.",
    links: ["secret-space-program", "william-tompkins", "douglas-aircraft", "trw", "north-american-aviation", "northrup-grumman", "antigravity"],
  },
  {
    id: "mj12",
    label: "MJ-12 / Majestic-12",
    category: "ssp",
    weight: 4,
    desc: "An alleged secret committee formed in 1947 by President Truman to manage the UFO/ET issue. The MJ-12 documents (leaked in 1984, of disputed authenticity) name 12 scientists and intelligence officials. Within the narrative, MJ-12 evolved into the controlling body of the SSP, the UFO cover-up, and ET treaties — eventually infiltrated and taken over by the cabal.",
    sources: [
      { label: "Majestic 12 — Wikipedia", url: "https://en.wikipedia.org/wiki/Majestic_12" },
    ],
    links: ["secret-space-program", "deep-state", "bobby-ray-inman", "nasa-coverup", "full-disclosure"],
  },
  {
    id: "battle-of-la",
    label: "Battle of Los Angeles (Feb 1942)",
    category: "ssp",
    weight: 3,
    desc: "A real 1942 incident in which U.S. military fired over 1,400 anti-aircraft shells at an unidentified object over Los Angeles. Within the narrative, this is framed as one of the first major public encounters with ET craft, suppressed by the military, and a catalyst for the formal reverse-engineering program that became the SSP.",
    sources: [
      { label: "Battle of Los Angeles — Wikipedia", url: "https://en.wikipedia.org/wiki/Battle_of_Los_Angeles" },
    ],
    links: ["secret-space-program", "reverse-engineering-ufos", "mj12"],
  },
  {
    id: "operation-highjump",
    label: "Operation Highjump (Adm. Byrd, 1947)",
    category: "ssp",
    weight: 3,
    desc: "A real 1946–47 U.S. Navy expedition to Antarctica led by Admiral Richard Byrd. Within the narrative, Highjump is described as a military invasion of the Nazi breakaway base in Antarctica — described as 'the largest U.S. Naval defeat' — which forced the U.S. to capitulate to the Nazi breakaway civilization and led directly to the creation of the Military-Industrial Complex and the SSP.",
    sources: [
      { label: "Operation Highjump — Wikipedia", url: "https://en.wikipedia.org/wiki/Operation_Highjump" },
    ],
    links: ["nazi-breakaway", "secret-space-program", "dark-fleet", "antarctica"],
  },
  {
    id: "douglas-aircraft",
    label: "Douglas Aircraft Company",
    category: "ssp",
    weight: 2,
    desc: "A real U.S. aerospace company that, within the SSP narrative, hosted William Tompkins' classified think tank in the 1950s–60s where kilometer-long Navy spacecraft were designed. Described as one of the original 'seed' contractors for SSP work, alongside TRW and North American Aviation.",
    links: ["william-tompkins", "reverse-engineering-ufos", "secret-space-program", "trw", "north-american-aviation"],
  },
  {
    id: "trw",
    label: "TRW Inc.",
    category: "ssp",
    weight: 2,
    desc: "A real U.S. aerospace/defense corporation that, within the SSP narrative, was one of the original contractors selected to reverse-engineer ET technology and produce components for the early SSP fleet.",
    links: ["william-tompkins", "reverse-engineering-ufos", "secret-space-program", "douglas-aircraft"],
  },
  {
    id: "north-american-aviation",
    label: "North American Aviation",
    category: "ssp",
    weight: 2,
    desc: "A real U.S. aerospace manufacturer, named within the SSP narrative alongside Douglas and TRW as one of the three original contractors seeded with ET-derived designs in the 1950s.",
    links: ["william-tompkins", "reverse-engineering-ufos", "secret-space-program", "douglas-aircraft"],
  },
  {
    id: "northrup-grumman",
    label: "Northrop Grumman",
    category: "ssp",
    weight: 2,
    desc: "A real U.S. defense contractor named within the SSP narrative as a successor to the original SSP aerospace contractors, continuing to manufacture classified SSP craft and components. Linked to the modern MICSSP and to the development of the TR-3B.",
    links: ["secret-space-program", "tr3b", "micssp", "reverse-engineering-ufos"],
  },
  {
    id: "20-and-back",
    label: "20-and-Back Program",
    category: "ssp",
    weight: 4,
    desc: "A central claim of the Corey Goode / Tony Rodriguez testimony: SSP recruits are abducted (often via MILABs) as children, age-regressed, given 20 years of service in the SSP, then age-regressed again and time-traveled back to within minutes of their original abduction — so no one knows they were gone. The '20-and-back' cycle is said to be the standard service term across Solar Warden, Dark Fleet, and other factions.",
    links: ["secret-space-program", "corey-goode", "tony-rodriguez", "milab", "solar-warden", "dark-fleet"],
  },
  {
    id: "jumpgate-portals",
    label: "Jumpgate Portals",
    category: "ssp",
    weight: 3,
    desc: "Described as artificial wormhole / portal technology used by the SSP to travel instantly between bases (Earth–Moon–Mars–Saturn, etc.). Within the narrative, the 'jump room' program of the 1980s (allegedly used by Barack Obama and others as teens) is one public echo of this technology. Also called 'stargates' or 'portal networks.'",
    links: ["secret-space-program", "cosmic-web-portal", "loc", "mars", "saturn"],
  },
  {
    id: "milab",
    label: "MILAB (Military Abduction)",
    category: "ssp",
    weight: 3,
    desc: "Short for 'military abduction' — the claim that the SSP/MICSSP uses classified military assets to abduct civilians (often children identified as 'intuitive empaths') for induction into SSP programs, training, and 20-and-back service. Said to be distinct from but sometimes confused with ET abduction. Corey Goode and Tony Rodriguez both describe MILAB induction.",
    links: ["secret-space-program", "20-and-back", "corey-goode", "tony-rodriguez"],
  },
  {
    id: "ssp-researchers",
    label: "SSP Researchers & Promoters",
    category: "ssp",
    weight: 3,
    desc: "The network of authors, researchers, and media figures who built and promoted the SSP narrative: David Wilcock, Dr. Michael Salla, Gaia.com, Kerry Cassidy (Project Camelot), Dr. Steven Greer, Richard C. Hoagland, Jay Weidner, Richard Dolan, Linda Moulton Howe, Laura Eisenhower, Jordan Maxwell, Billy Carson, David Icke, Art Bell, George Noory. Within the narrative, these figures collectively form the public-facing research community that brought the SSP into the open.",
    links: ["secret-space-program", "david-wilcock", "cosmic-disclosure", "nasa-dark-mission"],
  },
  {
    id: "cosmic-disclosure",
    label: "Cosmic Disclosure (Gaia Series)",
    category: "ssp",
    weight: 3,
    desc: "A long-form interview series on Gaia.com hosted by David Wilcock featuring Corey Goode's testimony, which became the primary public vector for the modern SSP narrative. Within the community, the series is treated as the canonical text of the SSP / Sphere Being Alliance storyline.",
    sources: [
      { label: "Gaia — Cosmic Disclosure", url: "https://www.gaia.com/series/cosmic-disclosure" },
    ],
    links: ["corey-goode", "david-wilcock", "sphere-being-alliance", "secret-space-program"],
  },
  {
    id: "human-slave-labor",
    label: "Human Slave Labor (Off-World)",
    category: "ssp",
    weight: 3,
    desc: "Within the narrative, the ICC and Dark Fleet operate off-world industrial facilities (on Mars, Ceres, in the upper atmosphere of Venus, in Antarctic underground bases) using abducted human slave labor — civilians taken via MILABs, age-regressed, and placed in 20-and-back service under brutal conditions with no return. Corey Goode and Tony Rodriguez are the primary whistleblowers. Said to be the modern continuation of the ancient Draco/Annunaki practice of treating humanity as a slave/livestock species, and one of the central crimes to be exposed at Full Disclosure.",
    links: ["dark-fleet", "icc", "icc-bases-mars", "20-and-back", "milab", "annunaki", "draco-alliance"],
  },
  {
    id: "usa-military",
    label: "USAF / U.S. Military",
    category: "ssp",
    weight: 3,
    desc: "Within the narrative, the U.S. Air Force is described as the primary operator of the lower-tier MICSSP (TR-3B, low-Earth-orbit operations, conventional classified craft), while the U.S. Navy runs Solar Warden and the deeper SSP. The military-industrial complex is presented as the institutional cover for both.",
    links: ["micssp", "secret-space-program", "tr3b", "compartmentalized-programs"],
  },
];
