import type { GAMNode } from "./types";

// SECRET SPACE PROGRAM — the claimed hidden space infrastructure
export const SSP_NODES: GAMNode[] = [
  {
    id: "secret-space-program",
    label: "Secret Space Program (SSP)",
    category: "ssp",
    weight: 5,
    desc: "The central claim of this whole branch of the narrative: that since the mid-20th century, a parallel, highly classified space program has existed entirely separate from NASA, using reverse-engineered extraterrestrial technology and antigravity craft. The SSP is described as having multiple factions (Solar Warden, the Interplanetary Corporate Conglomerate or ICC, Dark Fleet, the Global Galactic League of Nations, and the SSP Alliance), operating across the solar system and beyond, with bases on the Moon (the Lunar Operations Command, or LOC), on Mars (multiple ICC facilities using human slave labor), in the upper atmosphere of Venus (ICC-controlled), on Ceres (a Dark Fleet forward operating base), in Antarctica (the Nazi breakaway's original base), and in numerous Deep Underground Military Bases (DUMBs) connected by maglev tunnels across Earth. Whistleblowers describe a '20-and-back' service cycle in which recruits — often abducted as children via the MILAB program — are age-regressed, given 20 years of service in the SSP, then age-regressed again and time-traveled back to within minutes of their original abduction, so no one on Earth knows they were ever gone. The SSP is said to have begun with the reverse-engineering of crashed ET craft (Roswell, Kecksburg, Cape Girardeau) in the 1940s, merged with the Nazi breakaway's antigravity technology via Operation Paperclip, and was institutionalized under the Majestic-12 (MJ-12) committee in 1947. The poster claims the SSP has been operational at scale since the late 1950s, that its budget is funded by the cabal's off-the-books drug trafficking, child trafficking, and financial-manipulation operations (estimated in the trillions of dollars), and that the SSP's existence is the single most-classified secret in the world — protected by compartmentalization, the 'read-in' system, NDAs enforced by lethal penalty, and the '20-and-back' / age-regression / memory-wipe infrastructure that ensures no SSP retiree can credibly disclose. The narrative treats the SSP as the operational backbone of the cabal's off-world activities and as the infrastructure that the Earth Alliance and SSP Alliance are now using to dismantle the cabal from within. Full Disclosure, in the narrative's strongest form, would mean the public acknowledgment of the SSP and the release of its technology (antigravity, free-energy, advanced medical, time-travel) to all of humanity.",
    sources: [
      { label: "Gaia: Cosmic Disclosure", url: "https://www.gaia.com/series/cosmic-disclosure" },
    ],
    links: ["micssp", "solar-warden", "dark-fleet", "icc", "earth-alliance", "ssp-alliance", "tr3b", "antigravity", "loc", "20-and-back", "william-tompkins", "corey-goode"],
  },
  {
    id: "micssp",
    label: "MICSSP (Military-Industrial Complex SSP)",
    category: "ssp",
    weight: 4,
    desc: "The lower-level, publicly-denied space program run by the conventional military-industrial complex. Said to be what most people inside classified aerospace believe is 'the' secret space program — limited to low-Earth-orbit operations, the TR-3B antigravity triangular craft, conventional (non-antigravity) advanced aerospace craft (Aurora, the SR-75 Penetrator), and the back-engineered propulsion systems that occasionally surface in public aviation (stealth technology, certain advanced ramjet designs). The MICSSP is described as a compartmentalized lower tier that does NOT know about the deeper SSP factions — Solar Warden, Dark Fleet, the ICC, the 20-and-back program, the LOC, or the Draco alliance. Personnel within the MICSSP (including most generals, most aerospace engineers, most CIA directors) genuinely believe the SSP ends at the TR-3B and a few classified low-Earth-orbit platforms. The narrative uses this compartmentalization to explain why so many credible insiders can credibly deny the SSP's existence — they are denying the MICSSP, which they know about, while being unaware of the deeper programs. The MICSSP is described as the bridge between the public NASA / defense-contractor world and the deeper SSP — it is where the 'leakage' of advanced technology into the public aerospace sector occurs (stealth, fiber optics, integrated circuits, GPS all being described as MICSSP 'leaks'), and it is where the Earth Alliance has its strongest white-hat presence within the conventional military. The poster positions the MICSSP as the tier that will be acknowledged first during the staged Disclosure process, with the deeper SSP factions (Solar Warden, ICC, Dark Fleet) being disclosed in subsequent phases.",
    links: ["secret-space-program", "tr3b", "compartmentalized-programs", "usa-military"],
  },
  {
    id: "solar-warden",
    label: "Solar Warden",
    category: "ssp",
    weight: 4,
    desc: "An alleged secret U.S. Navy space fleet said to patrol the solar system, operating since the 1980s. First publicly surfaced in 2002 when Scottish hacker Gary McKinnon claimed to find a 'non-terrestrial officer' roster, lists of Navy ship-to-ship transfers including ships not publicly known, and 'Solar Warden' fleet listings on U.S. military computers while searching for UFO evidence. Within the narrative, Solar Warden is described as one of the original SSP factions, using antigravity battlecruisers (largely built by Northrop Grumman under classified Navy contracts), operating out of the Lunar Operations Command, and tasked with policing the solar system against unauthorized ET incursions, monitoring the Draco / Dark Fleet presence, and running the '20-and-back' service program. Solar Warden is described as the faction in which Corey Goode served his 20-and-back tour as an 'intuitive empath' — a role in which he was used as a sort of biological lie-detector / empathic translator in SSP-ET diplomatic meetings. The narrative claims Solar Warden was originally a U.S.-only program but eventually expanded to include participation from allied English-speaking nations (the Five Eyes), and that it eventually split — with a defector faction (the SSP Alliance) breaking away from the cabal-aligned leadership to force Full Disclosure. The poster positions Solar Warden as the 'good guy' faction of the original SSP, the one most aligned with the Earth Alliance, and the faction that has been most willing to leak its existence to the public.",
    sources: [
      { label: "Gary McKinnon hacking case (Wikipedia)", url: "https://en.wikipedia.org/wiki/Gary_McKinnon" },
    ],
    links: ["secret-space-program", "ssp-alliance", "gary-mckinnon", "antigravity"],
  },
  {
    id: "dark-fleet",
    label: "Dark Fleet",
    category: "ssp",
    weight: 4,
    desc: "Described as a Nazi-originated offensive space fleet operating beyond the solar system, 'similar to the Empire in Star Wars — conquer and control entire star systems.' According to the narrative, Dark Fleet was formed by the Nazi breakaway civilization that escaped to Antarctica after WWII (see Nazi Breakaway node), allied itself with the Draco & Reptilian Alliance, and expanded its operations outward into the galaxy. Dark Fleet is described as operating under a Nazi command structure, using human slave labor (often abducted via MILABs and placed in 20-and-back service), flying 'black wedge and pumpkin seed' shaped antigravity craft (the Haunebu-derived designs), and being based out of Ceres (a major underground base), Saturn (the 'off-limits' zone for the SSP Alliance), and Antarctic underground facilities. Whistleblower Tony Rodriguez describes being abducted into 20-and-back service on a Dark Fleet vessel — serving under Draco command, in brutal conditions, with the human crew treated as barely-above-slave labor. Dark Fleet is described as the most hostile of the SSP factions — actively conquering and enslaving other civilizations beyond the solar system, allied with the Orion Syndicate, and operating as the Draco's enforcement arm. Within the narrative, Dark Fleet is currently being dismantled by the combined efforts of the SSP Alliance, the Earth Alliance, and the Sphere Being Alliance — the Saturn 'off-limits' status is described as a temporary Dark Fleet defensive position that will be broken when the time is right. The poster positions Dark Fleet as the clearest single example of why Full Disclosure matters — a literal Nazi space fleet using human slaves, allied with Reptilians, conquering other planets, all hidden from the public for 80 years.",
    links: ["secret-space-program", "nazi-breakaway", "draco-alliance", "orion-syndicate", "tony-rodriguez", "ceres-base", "saturn", "human-slave-labor"],
  },
  {
    id: "icc",
    label: "Interplanetary Corporate Conglomerate (ICC)",
    category: "ssp",
    weight: 4,
    desc: "Described as the corporate wing of the SSP — a conglomerate of off-world aerospace corporations that has 'established intergalactic trade with 900+ extraterrestrial races.' According to the narrative, the ICC was spun out of the original SSP in the 1960s-70s as a way to monetize SSP technology and create a self-sustaining off-world corporate infrastructure. The ICC is said to operate extensive underground bases on Mars (using human slave labor — abducted via MILABs, age-regressed, and placed in 20-and-back service in Mars industrial facilities producing technology for the ICC's trade with 900+ ET races), facilities in the upper atmosphere of Venus (above the hostile surface), mining operations across the asteroid belt (especially Ceres), and research facilities on the Moon (alongside the Lunar Operations Command). Within the narrative, the ICC is the faction that supplies Dark Fleet with hardware and personnel, that runs the Mars slave-labor program, and that has the most direct ties to Earth-side defense contractors (Northrop Grumman, Douglas Aircraft, TRW, Lockheed Martin, Boeing) — with the Earth-side corporations providing the workforce recruitment, the cover stories, and the financial infrastructure. The ICC is described as the most profit-driven and most cabal-aligned of the SSP factions, having essentially become a trans-stellar corporation that views Earth as a resource-extraction colony (human labor, biological material, gold, and rare elements) rather than as its home planet. Whistleblowers (Corey Goode, Penny Bradley, Tony Rodriguez) describe the ICC's Mars facilities in detail — the brutal conditions, the age-regression of the workforce, the absence of any way home, the execution of 'problem' workers. The poster positions the ICC as the most-economically-powerful of the SSP factions, the one most resistant to Full Disclosure (because disclosure would destroy its business model), and the faction whose dismantling will be the most complex part of the Earth Alliance's post-Disclosure work.",
    links: ["secret-space-program", "dark-fleet", "mars", "venus", "human-slave-labor", "micssp", "icc-bases-mars"],
  },
  {
    id: "earth-alliance",
    label: "Earth Alliance",
    category: "ssp",
    weight: 4,
    desc: "Described as a positive faction of white-hat military, intelligence, financial, and political operatives working inside the cabal's own institutions to take it down from within. According to the narrative, the Earth Alliance was formally organized in the early 2000s (some variants say 2012) as a coalition of: white-hat factions within the U.S. military (especially the DIA, the NSA under Admiral Rogers, and Military Intelligence), the BRICS nations (Russia, China, India, Brazil, South Africa — described as having broken from the cabal's central-bank system), the White Dragon Society and Asian gold-owning families (described as controlling vast gold reserves that back the QFS), elements of the Catholic Church (specifically the traditionalist wing that opposes the cabal-infiltrated Vatican), and certain European nobility who have broken from the Black Nobility. The Earth Alliance is said to be coordinating: (1) the mass arrests of the cabal ('the Storm'), via sealed indictments and military tribunals at Gitmo and (variants) at newly-built tribunal facilities; (2) the financial reset (the Quantum Financial System, or QFS, replacing the Federal Reserve and the central-bank fiat system); (3) Full Disclosure of the SSP and ET contact; (4) the dismantling of the cabal's child-trafficking network (the underground tunnels, the DUMBs, the ritual abuse infrastructure); (5) the rollout of free-energy and suppressed medical technology; and (6) the political liberation of nations from cabal-controlled governance. Within the narrative, Trump, the Q operation, Space Force, and the 'devolution' theory of continuous military government are all presented as Earth Alliance projects. The Earth Alliance is described as working in alliance with the SSP Alliance (the defector faction from the SSP factions) and with positive ET groups (the Pleiadians, the Sphere Being Alliance) — but always within the constraints of human free will and existing legal frameworks (the Insurrection Act, the 2018 Executive Order on foreign interference, the continuously-renewed national emergency declarations). The poster positions the Earth Alliance as the human-scale operational arm of the Great Awakening — the ones doing the day-to-day work of dismantling the cabal while the cosmic-scale events (the Solar Flash, the ascension) unfold in parallel.",
    links: ["secret-space-program", "ssp-alliance", "full-disclosure", "qanon", "trump", "space-force", "white-hats", "white-dragon-society"],
  },
  {
    id: "ssp-alliance",
    label: "SSP Alliance",
    category: "ssp",
    weight: 4,
    desc: "A faction described as defectors from across the SSP factions (Solar Warden, ICC, Global Galactic League of Nations) who joined forces to force Full Disclosure. According to the narrative, the SSP Alliance was formally organized in the early 2010s, when a critical mass of SSP personnel — disillusioned by the ICC's Mars slave-labor program, the Dark Fleet's alliance with the Draco, and the 20-and-back abductions of children — broke from their respective factions and formed a coalition dedicated to exposing the SSP's existence to the public. The SSP Alliance is described as the faction that approached the Sphere Being Alliance (the Blue Avians) for assistance when the Blue Avians arrived in the solar system in 2011-2012, and that now works in alliance with the Earth Alliance and the Sphere Being Alliance to coordinate Full Disclosure. Within the narrative, the SSP Alliance has been responsible for: leaking SSP data to whistleblowers like Corey Goode (the Cosmic Disclosure series on Gaia is described as an SSP Alliance disclosure operation); providing intelligence on Dark Fleet, ICC, and Draco operations to the Earth Alliance; conducting targeted operations against the cabal's off-world infrastructure (the 'data dump' that will be released at Full Disclosure is said to be in SSP Alliance custody); and negotiating with positive ET groups on humanity's behalf. The poster positions the SSP Alliance as the most heroic of the SSP factions — the one that chose humanity over self-interest, that risked everything to expose the truth, and that will be vindicated at Full Disclosure.",
    links: ["secret-space-program", "sphere-being-alliance", "earth-alliance", "full-disclosure", "corey-goode"],
  },
  {
    id: "global-galactic-league",
    label: "Global Galactic League of Nations",
    category: "ssp",
    weight: 3,
    desc: "Described as an SSP faction formed in the 1990s as a UN-style 'galactic UN' consortium of Earth nations (beyond the U.S.-led MICSSP). According to the narrative, the Global Galactic League of Nations (GGLN) was created when the cabal — under pressure from other nations demanding access to SSP technology — agreed to a limited disclosure of the SSP to a select group of non-U.S. nations, who then formed their own SSP faction operating smaller, less-advanced craft out of Earth-orbit facilities. The GGLN is described as relatively benign, as existing primarily to give non-U.S. nations a stake in the SSP (and thus keep them compliant with the cabal's overall management), and as being largely unaware of the deeper SSP factions (Dark Fleet, the ICC's slave-labor operations, the Draco alliance). Within the narrative, the GGLN is the SSP faction most likely to defect to the SSP Alliance when Full Disclosure occurs, and its existence is offered as evidence that the SSP is not a purely U.S. operation but a global one. The poster positions the GGLN as the 'soft disclosure' vehicle — the faction that, when acknowledged publicly, will be presented as the totality of the SSP (the limited hangout), with the deeper factions being disclosed only later.",
    links: ["secret-space-program", "micssp", "galactic-un"],
  },
  {
    id: "tr3b",
    label: "TR-3B Astra",
    category: "ssp",
    weight: 3,
    desc: "A rumored triangular antigravity craft allegedly developed by the U.S. Air Force under black-project budget lines, the most well-known of the 'black triangle' UFO sightings reported worldwide since the 1990s. Within the narrative, the TR-3B (also called 'Astra' or 'Black Manta') is described as a 'black wedge and pumpkin seed shape craft' servicing low-Earth-orbit space stations, with a mercury-based plasma accelerator (a derivative of the Nazi Bell / Die Glocke technology) at its center that creates the antigravity field. The TR-3B is described as the most 'leaked' SSP craft — the one most often seen by civilians, the one whose existence is most-rumored in aviation circles, and the one most likely to be acknowledged first during staged Disclosure. The poster positions the TR-3B as the upper tier of the MICSSP — a real, operational, classified craft that the cabal has been forced to deploy more often as the Earth Alliance's pressure on them has increased, leading to more frequent sightings. The narrative claims the TR-3B is involved in the targeted operations against cabal DUMBs (Deep Underground Military Bases), in the transport of tribunaled cabal figures to Gitmo, and in the suppression of certain cabal-aligned ET craft in Earth's atmosphere. The TR-3B's existence is offered as the most-accessible 'proof' of the SSP — anyone who has seen a black triangle UFO (a common report) has, within the narrative, seen SSP technology.",
    sources: [
      { label: "Black triangle (UFO) — Wikipedia", url: "https://en.wikipedia.org/wiki/Black_triangle_(UFO)" },
    ],
    links: ["secret-space-program", "micssp", "antigravity", "black-wedge-craft"],
  },
  {
    id: "antigravity",
    label: "Antigravity",
    category: "tech",
    weight: 4,
    desc: "The foundational suppressed technology of the SSP: the ability to nullify or reverse gravity. Within the narrative, antigravity has been operational since the 1940s — first via the Nazi Bell (Die Glocke) and the Vril / Haunebu saucer programs, then via the post-war American reverse-engineering of crashed ET craft (Roswell, Kecksburg, etc.) and the Operation Paperclip absorption of the Nazi scientists who had built the original antigravity prototypes. Antigravity is described as the basis of all SSP propulsion — used in the TR-3B, the Solar Warden battlecruisers, the Dark Fleet's black-wedge craft, the ICC's interstellar trade vessels, and the Lunar Operations Command's shuttle fleet. The mechanism described across the various whistleblower accounts involves: a mercury-based plasma accelerator (spinning mercury vapor at high speed in a magnetic field, creating a 'torsion field' that decouples the craft from the local gravitational field); a 'zero-point energy' tap (extracting energy from the quantum vacuum to power the field generator); and a 'frequency shield' that protects the crew from the inertial effects of extreme acceleration. Within the narrative, antigravity is the single most-suppressed technology on Earth — withheld from humanity by the cabal because its release would collapse the petroleum economy, the aerospace industry's profit model, the geopolitical control structure (no more need for pipelines, oil wars, or the petrodollar), and the cabal's ability to control human movement. The poster claims the release of antigravity to civilian use is one of the Earth Alliance's primary post-Disclosure goals, and that antigravity passenger craft will be a routine part of life within 10 years of Full Disclosure.",
    links: ["secret-space-program", "nazi-bell", "free-energy", "tr3b", "reverse-engineering-ufos"],
  },
  {
    id: "compartmentalized-programs",
    label: "Compartmentalized Programs",
    category: "ssp",
    weight: 3,
    desc: "The claim that secret programs are structured so that no single person knows the full picture — each worker, scientist, engineer, or general knows only their compartment, and is denied access to any other compartment without explicit 'read-in' authorization. Used within the narrative to explain why most people inside aerospace, intelligence, and the military genuinely don't know the SSP exists, even though they may work on pieces of it. 'Need-to-know' is treated as the cabal's primary mechanism of secrecy — a worker at Lockheed's Skunk Works might spend their entire career on a single component of a TR-3B without ever knowing what the assembled craft looks like, what its mission is, or even that it's a spacecraft. The narrative describes a hierarchy of read-ins: most aerospace workers are 'compartmented' at the level of their specific component; a smaller group of program managers is read into the program as a whole (e.g., the TR-3B program); a smaller group still is read into the SSP as a whole (Solar Warden, ICC, etc.); and only the top tier — MJ-12 / Majestic, the cabal's council of 200, and the Draco / Orion liaisons — is read into the full picture (the SSP, the Draco alliance, the A.I. signal, the cosmic context). The poster uses this compartmentalization model to explain why 'official' denials of the SSP from generals, CIA directors, and even presidents can be sincere — they are often denying the existence of programs they genuinely don't know about. The Earth Alliance's challenge, within the narrative, is that even most white-hat military officers don't know the full SSP picture and must be carefully read-in one at a time as the Alliance's operations unfold.",
    links: ["secret-space-program", "micssp", "deep-state"],
  },
  {
    id: "loc",
    label: "Lunar Operations Command (LOC)",
    category: "ssp",
    weight: 4,
    desc: "Described as the primary SSP base on the Moon — a multilevel facility on the far side serving as command, control, and diplomatic hub for the entire SSP. According to the narrative (primarily sourced from Corey Goode's testimony), the LOC has three known levels (LOC 1, LOC 2, LOC 3), each deeper and more classified than the one above. LOC 1 is described as the 'public' SSP level — where MILAB abductees are processed, where the 20-and-back recruits are age-regressed and assigned to their factions, and where routine SSP traffic is coordinated. LOC 2 is described as the diplomatic level — housing the 'Galactic U.N.' zone where multiple ET civilizations and SSP factions meet under UN-style protocols, and where the ICC conducts some of its trade negotiations. LOC 3 is described as the deepest level — restricted to MJ-12 / Majestic, the cabal's leadership, the Draco liaisons, and (since 2011-2012) the Sphere Being Alliance representatives. The LOC is said to connect via underground shuttle tunnels to other lunar bases (ICC facilities, Dark Fleet outposts, ancient ruins), to be accessible from Earth via the jumpgate portal network, and to have been the primary processing point for SSP personnel since the 1960s. Corey Goode describes being processed through the LOC on his way to 20-and-back service — being age-regressed from age 6 to age 18, given his intuitive-empath training, and assigned to Solar Warden. The poster positions the LOC as the SSP's equivalent of the Pentagon — the administrative heart of the entire off-world infrastructure, and the facility whose public disclosure will be the centerpiece of Full Disclosure.",
    links: ["secret-space-program", "moon", "galactic-un", "underground-bases", "corey-goode"],
  },
  {
    id: "apollo-coverup",
    label: "Apollo Moon Landings (Cover-up Claim)",
    category: "ssp",
    weight: 3,
    desc: "Within the narrative, the Apollo missions are described as a public-facing 'cover story' that occurred alongside a much larger, classified lunar program. According to the narrative, the public Apollo landings (1969-1972) were permitted only after the SSP had already established the Lunar Operations Command and a network of smaller lunar bases — Apollo was the public theater, the SSP was the real program. The astronauts were said to have been briefed on ET presence and on the ancient ruins on the Moon (the glass domes, the crystalline towers, the Ancient Builder Race structures), warned not to disclose, and monitored for the rest of their lives. Neil Armstrong and Buzz Aldrin are both described as having been deeply affected by what they saw and as having made veiled references to it in subsequent interviews (Armstrong's cryptic comments to a teacher, Aldrin's 'there's a monolith on Phobos' comment, Aldrin's televised reaction upon returning from the Moon). Some variants of the narrative claim parts of the Apollo footage were staged by Stanley Kubrick (see the Stanley Kubrick node) — not because Apollo didn't go to the Moon (it did), but because the raw footage showed things NASA couldn't release (ET craft, ruins, structures), and so a sanitized version had to be filmed in a studio and substituted. The Apollo program's abrupt cancellation in 1972 is described as the result of the SSP leadership deciding the public program was too risky (too many near-disclosures) and pulling the plug — the real lunar program continued under the SSP, but no public missions were flown again.",
    links: ["secret-space-program", "loc", "moon", "stanley-kubrick", "nasa-coverup"],
  },
  {
    id: "william-tompkins",
    label: "William Tompkins",
    category: "ssp",
    weight: 3,
    desc: "A self-described aerospace engineer (1923-2017) who claimed in a series of interviews shortly before his death to have designed kilometer-long spacecraft for the U.S. Navy in the 1950s-60s under a classified 'think tank' at Douglas Aircraft. According to Tompkins, he was drafted into the Navy in 1942 at age 19, served as a typist in Admiral Rico Botta's office, and was tasked with disseminating classified packages containing Nazi antigravity research and ET contact data to a network of U.S. aerospace companies. After the war, Tompkins claimed he was recruited into a Douglas Aircraft think tank where he designed 19 types of kilometer-long Navy spacecraft (battlecruisers, carriers, exploration vessels), all based on Pleiadian (Nordic) ET technical data supplied by embedded Pleiadian operatives. Tompkins claimed the design packages were delivered to North American Aviation, TRW, and other defense contractors, who then built the craft for the SSP beginning in the late 1950s — this was, in his account, the origin of Solar Warden. Tompkins' testimony, published in his 2015 book 'Selected by Extraterrestrials' and in a series of interviews with Dr. Michael Salla, is treated within the narrative as the most senior and detailed insider confirmation of the SSP's post-WWII origins, the Pleiadian role in the SSP, and the existence of the design think tanks that bridge the ET-recovered technology and the built SSP fleet. Critics within the broader UFO community have questioned Tompkins' credentials and the verifiability of his claims, but the narrative treats him as a primary source.",
    sources: [
      { label: "William Tompkins (Wikipedia)", url: "https://en.wikipedia.org/wiki/William_Mills_Tompkins" },
    ],
    links: ["secret-space-program", "douglas-aircraft", "reverse-engineering-ufos", "ricco-botta", "nordics"],
  },
  {
    id: "corey-goode",
    label: "Corey Goode",
    category: "ssp",
    weight: 4,
    desc: "The most prominent contemporary SSP whistleblower (b. 1970). Goode claims to have been identified as an 'intuitive empath' as a child in Texas, abducted via the MILAB program at age 6, age-regressed, trained at a SOLARIS program, and given a 20-and-back tour of duty with Solar Warden from age 13 to 6 (via age-regression and time-travel back to his original timeline). During his 20-and-back, Goode claims to have served as an 'intuitive empath' — a biological lie-detector / empathic translator — in SSP-ET diplomatic meetings, to have been stationed on a Solar Warden research vessel, to have visited the Lunar Operations Command, to have witnessed Mars slave-labor facilities, and to have had contact with multiple ET groups (Draco, Pleiadians, inner-Earth civilizations). In 2014-2015, Goode claims to have been re-contacted by the Sphere Being Alliance (the Blue Avians), who chose him as their 'messenger' to humanity — delivering their messages about the upcoming Great Solar Flash, the need to raise personal vibration, and the importance of forgiveness and service-to-others. Goode's testimony, publicized through David Wilcock's Gaiam TV series 'Cosmic Disclosure' (2015-2018) and through his own books and interviews, forms the backbone of the modern SSP / Sphere Being Alliance narrative. Within the broader community, Goode is a polarizing figure — some treat him as the most important whistleblower of the modern era; others accuse him of embellishing or fabricating his experiences. The poster positions Goode as the central SSP whistleblower of the current era, the primary source on the Sphere Being Alliance and the inner-Earth civilizations (the Anshar), and a key node in the Earth Alliance / SSP Alliance disclosure operation.",
    sources: [
      { label: "Corey Goode — Wikipedia", url: "https://en.wikipedia.org/wiki/Corey_Goode" },
    ],
    links: ["secret-space-program", "solar-warden", "sphere-being-alliance", "blue-avians", "milab", "20-and-back", "david-wilcock", "cosmic-disclosure"],
  },
  {
    id: "tony-rodriguez",
    label: "Tony Rodriguez",
    category: "ssp",
    weight: 3,
    desc: "A Dark Fleet whistleblower who claims to have served a 20-and-back tour aboard a Dark Fleet vessel under Draco command. According to Rodriguez's testimony (publicized alongside Corey Goode's through Gaia and Dr. Michael Salla's research), he was abducted via MILAB at age 6 in California, age-regressed, trained, and assigned to a Dark Fleet vessel that operated in the solar system and beyond, working alongside the Draco and Reptilians in human slave-labor roles. Rodriguez describes in detail the brutal conditions inside Dark Fleet — the Draco's treatment of human crew as barely-above-slave labor, the systematic abuse, the absence of any way home, the execution of 'problem' workers, and the occasional SSP Alliance rescue operations that would spirit individuals out. His testimony is the most-detailed first-hand account of Dark Fleet operations available in the public record, and is treated within the narrative as primary evidence for the existence of the 20-and-back program, the ICC/Dark Fleet slave-labor infrastructure, and the Draco's direct operational control over Dark Fleet. Rodriguez's account is also offered as evidence that the SSP is not a unified program but a collection of competing factions with very different cultures, conditions, and allegiances.",
    links: ["dark-fleet", "secret-space-program", "20-and-back", "draco-alliance", "corey-goode"],
  },
  {
    id: "ricco-botta",
    label: "Adm. Rico Botta",
    category: "ssp",
    weight: 2,
    desc: "A real U.S. Navy Vice Admiral (1890-1992) who, in the Tompkins narrative, is described as having overseen the infiltration of Nazi Germany by embedded U.S. spies (1942-1946), the recovery of Nazi ARVs (alien reproduction vehicles), and the dissemination of the recovered Nazi antigravity research and ET contact data to a network of U.S. aerospace companies via a young William Tompkins as his typist / courier. Botta is described as a 'read-in' insider who understood the SSP from its earliest days, who was responsible for the Navy's role in the post-war UFO reverse-engineering program, and who was instrumental in the decision to spin Solar Warden out as a Navy-led (rather than Air Force-led) program — a decision that, within the narrative, explains why Solar Warden is described as the more 'white hat' SSP faction while the Air Force's MICSSP is described as more cabal-aligned. Botta's role in the Tompkins narrative positions him as one of the original architects of the modern SSP.",
    links: ["secret-space-program", "william-tompkins", "reverse-engineering-ufos"],
  },
  {
    id: "bobby-ray-inman",
    label: "Bobby Ray Inman",
    category: "ssp",
    weight: 2,
    desc: "A real U.S. Navy Admiral (b. 1931) and former Director of the National Security Agency (NSA, 1977-1981) and Deputy Director of Central Intelligence (1981-1982). Within the SSP narrative, Inman is named as a central figure in the MJ-12 / Majestic control structure that ran the UFO cover-up and managed the SSP from its inception. Inman is described as having been the 'gatekeeper' for the SSP for decades, the figure who managed the transition from the original MJ-12 group to the modern cabal-controlled UFO management structure, and as one of the key decision-makers in the SSP's evolution from a 1950s reverse-engineering program to a multi-faction interstellar operation. The narrative positions Inman as a complex figure — a longtime insider who, in some variants, has cooperated with the Earth Alliance's disclosure efforts in exchange for protection, and in other variants is treated as a cabal loyalist who must be tribunaled.",
    links: ["secret-space-program", "mj12", "deep-state"],
  },
  {
    id: "gary-mckinnon",
    label: "Gary McKinnon",
    category: "ssp",
    weight: 3,
    desc: "A Scottish systems administrator (b. 1966) who, between February 2001 and March 2002, infiltrated 97 U.S. military and NASA computers searching for UFO evidence. McKinnon, operating under the handle 'Solo' from his girlfriend's aunt's London apartment, claimed to have found: (1) a spreadsheet titled 'non-terrestrial officers' listing names and ranks of personnel not assigned to any known Earth-based command; (2) lists of Navy ship-to-ship transfers including two ships not publicly known; (3) 'Solar Warden' fleet listings and mission logs; (4) 'off-world' cargo manifests; and (5) high-resolution satellite imagery of UFOs, stored in a NASA building's unsecured folder under filenames like 'spacecraft.' McKinnon was caught, indicted by U.S. prosecutors, and faced up to 70 years in U.S. prison. His extradition fight became a decade-long cause célèbre in the UFO community and in UK civil-liberties politics, ending in 2012 with UK Home Secretary Theresa May blocking the extradition on human-rights grounds. Within the SSP narrative, McKinnon's case is treated as the single most-publicly-documented piece of evidence for Solar Warden's existence — a civilian hacker who, by his own account, found the SSP's personnel and logistics files on unclassified U.S. military systems. The narrative treats McKinnon as an accidental whistleblower and as a hero of the disclosure movement, even though he never released the data he claims to have found (it was, he said, deleted by U.S. authorities before he could copy it).",
    sources: [
      { label: "Gary McKinnon (Wikipedia)", url: "https://en.wikipedia.org/wiki/Gary_McKinnon" },
    ],
    links: ["solar-warden", "secret-space-program", "nasa-coverup"],
  },
  {
    id: "reverse-engineering-ufos",
    label: "Reverse-Engineering UFOs",
    category: "ssp",
    weight: 4,
    desc: "The claim that all advanced aerospace technology since WWII — from stealth to microchips to fiber optics to night vision to kevlar to integrated circuits to antigravity — was reverse-engineered from crashed ET craft (Roswell in 1947, Kecksburg in 1965, Cape Girardeau in 1941, the Aztec crash in 1948, the Kingman crash in 1953, the Dalnegorsk crash in 1986, and others). According to the narrative, recovered craft were distributed to defense contractors (Douglas Aircraft, TRW, North American Aviation, Northrop Grumman, Lockheed Martin, Bell Labs) for study under classified 'reverse-engineering' programs beginning in the late 1940s, with the results feeding both the MICSSP (stealth, integrated circuits, fiber optics — technologies the narrative claims were 'leaked' into the public sector in the 1960s-80s) and the deeper SSP (antigravity, free-energy, faster-than-light communication — technologies that remain fully classified). The poster treats this as the foundational industrial reality of the post-WWII American aerospace and technology sectors — that the U.S. tech boom was substantially driven by ET-derived technology, that the cabal's primary motive for the UFO cover-up is to protect this technology pipeline, and that the cabal has used the leverage of suppressed technology to maintain control over the major defense contractors and tech companies. The narrative claims that at Full Disclosure, the full list of recovered craft, the reverse-engineering programs, and the technologies derived from each will be released — and that the Earth Alliance has already prepared the patent releases, the manufacturing blueprints, and the technology-transfer plans to make the suppressed technology available to all of humanity within 10-15 years.",
    links: ["secret-space-program", "william-tompkins", "douglas-aircraft", "trw", "north-american-aviation", "northrup-grumman", "antigravity"],
  },
  {
    id: "mj12",
    label: "MJ-12 / Majestic-12",
    category: "ssp",
    weight: 4,
    desc: "An alleged secret committee formed in 1947 by President Truman to manage the UFO/ET issue in the wake of the Roswell crash. The MJ-12 documents (leaked in 1984 by an unknown sender, of disputed authenticity) name 12 scientists, military officers, and intelligence officials as the original members: Vannevar Bush, James Forrestal, Nathan Twining, Hoyt Vandenberg, Detlev Bronk, Jerome Hunsaker, Sidney Souers, Gordon Gray, Donald Menzel, Lloyd Berkner, Robert Montague, and Albert Einstein (variants exist). Within the narrative, MJ-12 was the controlling body of the UFO cover-up, the SSP, ET treaties (the 1954 Eisenhower-Grey treaties at Holloman AFB and Edwards AFB), and the reverse-engineering programs. MJ-12 is said to have evolved over the decades — the original 12 members died or were replaced, the structure was reorganized multiple times, and by the 1980s it had been infiltrated and taken over by the cabal, becoming the operational arm of the cabal's UFO management rather than the independent presidential committee Truman had intended. Within the narrative, MJ-12 (also called 'Majestic,' 'the Group,' 'the Majority Twelve,' or 'PI-40') was the body that signed the treaties with the Draco (the 1954 Greada Treaty, the 1958 Tau IX Treaty) that allowed the Draco to operate on Earth in exchange for technology; that authorized the MILAB program; that approved the 20-and-back age-regression technology; and that managed the relationship between the SSP factions. The narrative claims that the Earth Alliance has now largely dismantled MJ-12 / Majestic, that the Trump-era Space Force is the public-facing successor structure, and that the full MJ-12 archives (treaties, meeting minutes, technology transfer agreements) will be released at Full Disclosure.",
    sources: [
      { label: "Majestic 12 — Wikipedia", url: "https://en.wikipedia.org/wiki/Majestic_12" },
    ],
    links: ["secret-space-program", "deep-state", "bobby-ray-inman", "nasa-coverup", "full-disclosure"],
  },
  {
    id: "battle-of-la",
    label: "Battle of Los Angeles (Feb 1942)",
    category: "ssp",
    weight: 3,
    desc: "A real 1942 incident in which U.S. military fired over 1,400 anti-aircraft shells at an unidentified object (or objects) over Los Angeles in the early morning of February 25, 1942, less than three months after Pearl Harbor. The object moved slowly over the city for over an hour, taking direct hits without being damaged, while shells fell back to Earth killing several civilians. The official explanation (a weather balloon, or war nerves) has never been widely accepted. Within the narrative, the Battle of LA is framed as one of the first major public encounters with ET craft — the object was either a Draco reconnaissance vehicle, a Nazi Haunebu test craft (the Nazi breakaway having already developed antigravity by 1942), or an Ancient Builder Race sentinel. The narrative treats the Battle of LA as the catalyst for the formal UFO reverse-engineering program — the event that convinced the U.S. military that ET / advanced craft were real, recoverable, and a matter of national security, leading directly to the post-war MJ-12 / Majestic structure. The poster positions the Battle of LA alongside the 1941 Cape Girardeau crash, the 1947 Roswell crash, and the 1948 Aztec crash as the foundational UFO events that triggered the SSP's creation.",
    sources: [
      { label: "Battle of Los Angeles — Wikipedia", url: "https://en.wikipedia.org/wiki/Battle_of_Los_Angeles" },
    ],
    links: ["secret-space-program", "reverse-engineering-ufos", "mj12"],
  },
  {
    id: "operation-highjump",
    label: "Operation Highjump (Adm. Byrd, 1947)",
    category: "ssp",
    weight: 3,
    desc: "A real 1946-47 U.S. Navy expedition to Antarctica led by Admiral Richard Byrd — officially a 'training and research' mission, but actually (within the narrative) a military invasion of the Nazi breakaway civilization's Antarctic base. According to the narrative, after WWII the U.S. learned that elements of the Nazi SS, the Vril Society, and the Ahnenerbe had escaped to Antarctica (specifically to Queen Maud Land, the area the 1938-39 German Antarctic Expedition had claimed as 'Neu Schwabenland') with their antigravity technology (the Haunebu and Vril saucers, the Nazi Bell). The U.S. assembled the largest Antarctic expedition in history (4,700 men, 13 ships, 23 aircraft, an aircraft carrier) under Admiral Byrd to destroy the Nazi base. The narrative claims the expedition was defeated — Byrd's fleet was attacked by Nazi saucer craft that emerged from the ice, several U.S. ships were destroyed, and Byrd was forced to retreat after a few weeks rather than the planned 8-month operation. Byrd's subsequent debriefing of the U.S. government (the 'El Mercurio' interview of 1947, in which Byrd reportedly warned of flying craft that could fly pole-to-pole 'with incredible speed') is cited as primary evidence. The narrative claims that Operation Highjump's defeat forced the U.S. to negotiate with the Nazi breakaway — leading to the 1952 Antarctic Treaty (which militarized Antarctica and kept the public out), the secret arrangement that allowed the Nazi breakaway to operate independently in exchange for sharing some technology, and the eventual creation of the Military-Industrial Complex as a permanent classified infrastructure to manage the SSP / Nazi breakaway problem.",
    sources: [
      { label: "Operation Highjump — Wikipedia", url: "https://en.wikipedia.org/wiki/Operation_Highjump" },
    ],
    links: ["nazi-breakaway", "secret-space-program", "dark-fleet", "antarctica"],
  },
  {
    id: "douglas-aircraft",
    label: "Douglas Aircraft Company",
    category: "ssp",
    weight: 2,
    desc: "A real U.S. aerospace company (founded 1921, merged into McDonnell Douglas in 1967) that, within the SSP narrative, hosted William Tompkins' classified 'think tank' in the 1950s-60s where kilometer-long Navy spacecraft were designed. According to Tompkins, the Douglas think tank received ET-derived technical data packages via the Navy and from embedded Pleiadian operatives, and produced the design specifications for what became Solar Warden's battlecruisers. Douglas is described as one of the original 'seed' contractors for SSP work, alongside TRW and North American Aviation — the three companies that were read into the deepest level of the SSP design work in the 1950s. The narrative positions Douglas as a primary example of how the SSP was distributed across the conventional U.S. aerospace industry from its earliest days, and as one of the channels through which Pleiadian / Nordic ET technical assistance entered the SSP.",
    links: ["william-tompkins", "reverse-engineering-ufos", "secret-space-program", "trw", "north-american-aviation"],
  },
  {
    id: "trw",
    label: "TRW Inc.",
    category: "ssp",
    weight: 2,
    desc: "A real U.S. aerospace / defense / automotive corporation (1901-2002, acquired by Northrop Grumman) that, within the SSP narrative, was one of the original contractors selected to reverse-engineer ET technology and produce components for the early SSP fleet. TRW is described as having specialized in the SSP's electronics, sensors, and command-and-control systems — the 'brains' of the SSP craft rather than the airframes. The narrative positions TRW as one of the three original 'seed' contractors (alongside Douglas Aircraft and North American Aviation) and as a primary example of how deeply the SSP was embedded in the conventional U.S. defense-industrial base from its earliest days.",
    links: ["william-tompkins", "reverse-engineering-ufos", "secret-space-program", "douglas-aircraft"],
  },
  {
    id: "north-american-aviation",
    label: "North American Aviation",
    category: "ssp",
    weight: 2,
    desc: "A real U.S. aerospace manufacturer (1928-1967, merged into Rockwell International) that, within the SSP narrative, was one of the original three SSP 'seed' contractors (alongside Douglas and TRW), responsible for the airframe and structural work on the early SSP craft. North American is described as having leveraged its experience building the P-51 Mustang, the B-25 Mitchell, the F-86 Sabre, the X-15, and the Apollo command module into classified SSP work beginning in the 1950s, and as having been the source of much of the early SSP 'leakage' into the public aerospace sector (the X-15 program in particular is described as a partial cover for SSP test flights). The narrative positions North American as the third leg of the original SSP industrial triangle.",
    links: ["william-tompkins", "reverse-engineering-ufos", "secret-space-program", "douglas-aircraft"],
  },
  {
    id: "northrup-grumman",
    label: "Northrop Grumman",
    category: "ssp",
    weight: 2,
    desc: "A real U.S. defense contractor (formed 1994 from the merger of Northrop and Grumman, both with deep WWII and Cold War aerospace heritage) that, within the SSP narrative, is named as a successor to the original SSP aerospace contractors and as a continuing manufacturer of classified SSP craft and components. Specifically, the narrative claims Northrop Grumman built the Solar Warden battlecruisers under classified Navy contracts, developed the TR-3B under classified Air Force contracts, and remains a primary SSP contractor to this day — with much of its 'black' work hidden inside publicly-known programs like the B-2 Spirit, the RQ-180, and various classified stealth programs. The narrative positions Northrop Grumman as the modern hub of the MICSSP and as a likely primary contractor for the post-Disclosure release of antigravity passenger craft.",
    links: ["secret-space-program", "tr3b", "micssp", "reverse-engineering-ufos"],
  },
  {
    id: "20-and-back",
    label: "20-and-Back Program",
    category: "ssp",
    weight: 4,
    desc: "A central claim of the Corey Goode / Tony Rodriguez / Penny Bradley testimony: SSP recruits are abducted (often via MILABs as children, sometimes as young as 6), age-regressed to their early 20s, given 20 years of service in the SSP, then age-regressed again back to their original age and time-traveled back to within minutes of their original abduction — so no one on Earth knows they were ever gone. According to the narrative, the 20-and-back cycle is the standard service term across Solar Warden, Dark Fleet, the ICC, and the Global Galactic League of Nations, and is the primary mechanism by which the SSP maintains a workforce without depleting Earth's population or raising public suspicion. The age-regression technology is described as plasma-based, painful, and not always fully effective — some 20-and-back veterans retain fragmentary 'screen memories' that surface decades later in dreams, flashbacks, or psychedelic experiences. The time-travel component is described as the SSP's most closely-guarded secret — the ability to return a person to within minutes of their original abduction, ensuring no temporal anomaly is detected. Within the narrative, the 20-and-back program is one of the central crimes of the SSP — it is the abduction and enslavement of children and adults, the violation of free will, the erasure of consent, and the deliberate concealment of the abductee's experience. Full Disclosure, in the narrative's strongest form, would include the release of the 20-and-back records, the reunification of abductees with their (often forgotten) off-world experiences, and the dismantling of the MILAB infrastructure that feeds the program. The poster treats the 20-and-back as the most-personally-tragic element of the SSP narrative and as a primary motivator for the SSP Alliance's defection.",
    links: ["secret-space-program", "corey-goode", "tony-rodriguez", "milab", "solar-warden", "dark-fleet"],
  },
  {
    id: "jumpgate-portals",
    label: "Jumpgate Portals",
    category: "ssp",
    weight: 3,
    desc: "Described as artificial wormhole / portal technology used by the SSP to travel instantly between bases (Earth–Moon–Mars–Saturn, etc.) without traversing the physical distance. Within the narrative, jumpgates are described as: (1) the SSP's primary mode of inter-base transport (much faster than conventional antigravity flight); (2) the technology behind the alleged 1980s 'jump room' program that took civilians (including, in variants, a teenage Barack Obama, Andrew Basiago, and William Tompkins) between Earth and Mars via a portal located at a CIA facility in El Segundo, California; (3) the technology that allows the 20-and-back program to return abductees to their original timeline; and (4) the public-facing version of the same technology used by ET groups to traverse interstellar distances via the Sun-as-stargate cosmic web portal. The narrative treats jumpgates as derived from the Ancient Builder Race ruins (the SSP discovered and reactivated the Ancient Builder Race portal network) and as the SSP's most strategically important technology — the ability to move personnel, technology, and resources instantly across the solar system is what makes the SSP's logistics possible. Jumpgate portals are also described as the mechanism for the 'time-bubble sanctuaries' on Saturn (where the Council of Saturn meets) and for certain alleged Earth-based time-travel events (the Philadelphia Experiment, the Montauk Project).",
    links: ["secret-space-program", "cosmic-web-portal", "loc", "mars", "saturn"],
  },
  {
    id: "milab",
    label: "MILAB (Military Abduction)",
    category: "ssp",
    weight: 3,
    desc: "Short for 'military abduction' — the claim that the SSP / MICSSP uses classified military assets to abduct civilians (often children identified as 'intuitive empaths' or with specific genetic profiles) for induction into SSP programs, training, and 20-and-back service. Said to be distinct from but sometimes confused with ET abduction — many 'ET abduction' experiences, within the narrative, are actually MILAB operations using ET-looking craft and ET-looking 'screen memories' to conceal the human military origin. Corey Goode and Tony Rodriguez both describe MILAB induction as children (Goode at age 6 in Texas, Rodriguez at age 6 in California), and the broader MILAB literature (Helmut Lammer, Eve Lorgen, James Bartley) documents hundreds of similar claims. MILAB is described as the primary recruitment mechanism for the 20-and-back program, as a tool for the cabal's mind-control programming (the abducted children being programmed via MKUltra-derived techniques), and as a source of biological material for the ICC's genetic-experiment programs. Within the narrative, the dismantling of the MILAB infrastructure is one of the Earth Alliance's primary operations — many of the 'sealed indictments' are said to be for MILAB participants, and many of the 'children rescued from DUMBs' narratives (a recurring element of the QAnon-adjacent community) are described as Earth Alliance operations against the MILAB network.",
    links: ["secret-space-program", "20-and-back", "corey-goode", "tony-rodriguez"],
  },
  {
    id: "ssp-researchers",
    label: "SSP Researchers & Promoters",
    category: "ssp",
    weight: 3,
    desc: "The network of authors, researchers, and media figures who built and promoted the SSP narrative in the public sphere: David Wilcock (who first synthesized the SSP / ascension / Law of One material for a mass audience through his books and Gaia series), Dr. Michael Salla (who systematized the 'exopolitics' academic framework and published the first book-length SSP studies), Gaia.com (the streaming platform that hosted Cosmic Disclosure and other SSP content), Kerry Cassidy (Project Camelot, the longest-running SSP whistleblower interview channel), Dr. Steven Greer (the Disclosure Project founder, who approaches the SSP from a civilian-CE5 angle), Richard C. Hoagland (the NASA-anomalies researcher), Jay Weidner (alchemical filmmaker and Kubrick analyst), Richard Dolan (UFO historian), Linda Moulton Howe (animal mutilations and ET biology researcher), Laura Eisenhower (great-granddaughter of Dwight, who claims to have been recruited into a Mars colony project), Jordan Maxwell (symbologist and ancient-mystery-school researcher), Billy Carson (author and 4biddenknowledge platform founder), David Icke (the Reptilian narrative's primary promoter), Art Bell (the original Coast to Coast AM host who mainstreamed paranormal/UFO radio), and George Noory (Art Bell's successor). Within the narrative, these figures collectively form the public-facing research community that brought the SSP into the open over the past three decades. They are not always in agreement with each other (Greer dismisses the SSP / Draco aspects, Icke doesn't include the SSP, Salla and Goode have had public disputes), but the narrative treats them as complementary pieces of a larger research movement that has been preparing the public for Full Disclosure.",
    links: ["secret-space-program", "david-wilcock", "cosmic-disclosure", "nasa-dark-mission"],
  },
  {
    id: "cosmic-disclosure",
    label: "Cosmic Disclosure (Gaia Series)",
    category: "ssp",
    weight: 3,
    desc: "A long-form interview series on Gaia.com (2015-2018) hosted by David Wilcock featuring Corey Goode's testimony, which became the primary public vector for the modern SSP / Sphere Being Alliance narrative. Across ~150 episodes, Goode detailed his 20-and-back service with Solar Warden, his re-contact with the Blue Avians / Sphere Being Alliance, his visits to the LOC and Mars, his encounters with the inner-Earth Anshar civilization, his observation of the Super Federation's genetic-experiment program, and his view of the broader cosmic context of the Great Awakening. The series also featured Tony Rodriguez, Pete Peterson, William Tompkins, and other SSP whistleblowers. Within the community, 'Cosmic Disclosure' is treated as the canonical text of the modern SSP narrative — the equivalent of what the Law of One was for the 1980s channeled-material community. The series' abrupt end in 2018 (Goode and Wilcock split, both left Gaia, both have continued their work independently) is treated within the narrative as a cabal-orchestrated disruption aimed at slowing the disclosure of the SSP / Sphere Being Alliance narrative, but also as having 'done its work' — the testimony is in the public record.",
    sources: [
      { label: "Gaia — Cosmic Disclosure", url: "https://www.gaia.com/series/cosmic-disclosure" },
    ],
    links: ["corey-goode", "david-wilcock", "sphere-being-alliance", "secret-space-program"],
  },
  {
    id: "usa-military",
    label: "USAF / U.S. Military",
    category: "ssp",
    weight: 3,
    desc: "Within the narrative, the U.S. military is split into different SSP-related factions: the U.S. Air Force is described as the primary operator of the lower-tier MICSSP (the TR-3B, low-Earth-orbit operations, conventional classified craft, the Area 51 / S4 reverse-engineering work, and the development of the next-generation stealth and hypersonic platforms that occasionally surface in public); while the U.S. Navy runs Solar Warden and the deeper SSP (the kilometer-long battlecruisers, the LOC operations, the 20-and-back program). The narrative explains this Navy-vs-Air-Force split as a legacy of the post-WWII interservice rivalry over the UFO file — the Navy got there first (Admiral Rico Botta, William Tompkins' design work, Admiral Byrd's Operation Highjump), and the Air Force (created as a separate service in 1947) was given the public-facing UFO investigation (Project Sign, Project Grudge, Project Blue Book) and the lower-tier reverse-engineering work as a consolation prize. Within the narrative, this split has continued to the present day — the Navy is more white-hat, the Air Force is more cabal-aligned, and the rivalry between them is one of the underlying dynamics of the Earth Alliance vs cabal struggle. The U.S. Army is described as a minor SSP participant (primarily the ground-side DUMB infrastructure and the military-police role in the tribunals), and the U.S. Marine Corps as a wildcard that has, within the narrative, sided increasingly with the Earth Alliance.",
    links: ["micssp", "secret-space-program", "tr3b", "compartmentalized-programs"],
  },
  {
    id: "human-slave-labor",
    label: "Human Slave Labor (Off-World)",
    category: "ssp",
    weight: 3,
    desc: "Within the narrative, the ICC and Dark Fleet operate off-world industrial facilities (on Mars, Ceres, in the upper atmosphere of Venus, in Antarctic underground bases) using abducted human slave labor — civilians taken via MILABs, age-regressed, and placed in 20-and-back service under brutal conditions with no return. According to whistleblower testimony (Corey Goode, Tony Rodriguez, Penny Bradley), the ICC's Mars facilities are the largest — vast underground industrial complexes producing technology for the ICC's trade with 900+ ET races, staffed entirely by abducted humans working in conditions that range from harsh-but-survivable (for skilled technicians) to literal slave-labor (for the bulk of the workforce). The Dark Fleet's slave-labor is described as even worse — humans working alongside the Draco and Reptilians in conditions where they are treated as biological assets, not personnel, and where 'problem' workers are routinely executed. Within the narrative, the off-world human slave-labor program is the most-suppressed element of the SSP — it is the crime that, more than any other, justifies Full Disclosure and the tribunals. The poster positions the off-world slave-labor as the modern continuation of the ancient Draco / Annunaki practice of treating humanity as a slave / livestock species (going back to the Annunaki gold-mining operations ~450,000 years ago per Sitchin), and as one of the central crimes to be exposed at Full Disclosure. The narrative claims that the SSP Alliance has been quietly evacuating slave-labor personnel from the most-brutal facilities for years, and that the full scope of the off-world slave-labor program — the numbers, the facilities, the responsible parties — will be disclosed at the Event.",
    links: ["dark-fleet", "icc", "icc-bases-mars", "20-and-back", "milab", "annunaki", "draco-alliance"],
  },
];
