import type { GAMNode } from "./types";

// TECH / SUPPRESSED TECHNOLOGY
export const TECH_NODES: GAMNode[] = [
  {
    id: "nikola-tesla",
    label: "Nikola Tesla",
    category: "tech",
    weight: 5,
    desc: "Within the narrative, Nikola Tesla (1856–1943) is described as the most important scientist of the modern era, who discovered free energy, wireless power transmission, antigravity, scalar weapons, and the electrical nature of reality — all of which were suppressed by J.P. Morgan and the cabal. His Wardenclyffe Tower is described as a working free-energy device that was deliberately shut down. His missing papers (seized by the Office of Alien Property in 1943) are said to be the foundation of the SSP's classified technology.",
    sources: [
      { label: "Nikola Tesla — Wikipedia", url: "https://en.wikipedia.org/wiki/Nikola_Tesla" },
    ],
    links: ["wireless-energy", "free-energy", "antigravity", "vibration-frequency", "electric-sun"],
  },
  {
    id: "wireless-energy",
    label: "Wireless Energy (Wardenclyffe)",
    category: "tech",
    weight: 4,
    desc: "Tesla's real 1901–1917 Wardenclyffe Tower project — wireless power transmission via the Earth-ionosphere cavity. Within the narrative, Wardenclyffe was a working prototype that J.P. Morgan defunded because there was no way to meter and charge for wireless power. The technology is said to have been seized, classified, and used by the SSP, while being suppressed for civilian use ever since.",
    sources: [
      { label: "Wardenclyffe Tower — Wikipedia", url: "https://en.wikipedia.org/wiki/Wardenclyffe_Tower" },
    ],
    links: ["nikola-tesla", "free-energy", "antigravity", "secret-space-program"],
  },
  {
    id: "free-energy",
    label: "Free Energy (Zero-Point)",
    category: "tech",
    weight: 5,
    desc: "Within the narrative, limitless free-energy technology has existed for over a century — based on zero-point energy (the quantum vacuum), the aether, or the Earth-ionosphere cavity — and has been systematically suppressed by the cabal to maintain the petroleum/nuclear economy and their control structure. Inventors who tried to commercialize free-energy devices (Stanley Meyer, Eugene Mallove, John Bedini, Tom Bearden's MEG) are described as murdered or silenced. The release of free-energy technology is said to be one of the Earth Alliance's goals after the Event.",
    sources: [
      { label: "Free energy suppression — Wikipedia", url: "https://en.wikipedia.org/wiki/Free_energy_suppression_conspiracy_theory" },
    ],
    links: ["nikola-tesla", "wireless-energy", "antigravity", "end-the-fed", "earth-alliance", "full-disclosure"],
  },
  {
    id: "orgone",
    label: "Orgone (Wilhelm Reich)",
    category: "tech",
    weight: 4,
    desc: "Wilhelm Reich's concept of 'orgone' — a cosmic life-force energy (analogous to prana/chi) that he claimed to have measured and concentrated in 'orgone accumulators.' The FDA destroyed his work and imprisoned him (1957), where he died. Within the narrative, Reich was destroyed by the cabal because orgone is the real physics of consciousness-as-energy. Modern 'orgonite' (resin + metal shavings + quartz) is described as a personal-use device that transmutes deadlier EMF (DOR — Deadly Orgone Radiation) into positive orgone, breaking chemtrails and healing the local atmosphere.",
    sources: [
      { label: "Wilhelm Reich — Wikipedia", url: "https://en.wikipedia.org/wiki/Wilhelm_Reich" },
      { label: "Orgone — Wikipedia", url: "https://en.wikipedia.org/wiki/Orgone" },
    ],
    links: ["prana", "vibration-frequency", "chemtrails", "raising-vibration"],
  },
  {
    id: "rife-machine",
    label: "Rife Machine (Cancer Cure)",
    category: "tech",
    weight: 4,
    desc: "Royal Rife's 1930s invention: a beam-ray device that used specific radio frequencies to shatter cancer cells and pathogens (the 'Mortal Oscillatory Rate'). Within the narrative, Rife's technology was a working cancer cure that was suppressed by the AMA and the pharmaceutical industry, his lab burned, his partners prosecuted. Modern 'Rife machines' are sold as alternative healing devices. Treated as the foundational case of medical-suppression conspiracy.",
    sources: [
      { label: "Royal Rife — Wikipedia", url: "https://en.wikipedia.org/wiki/Royal_Rife" },
    ],
    links: ["holistic-healing", "cancer-cured", "sound-healing", "432hz", "vibration-frequency"],
  },
  {
    id: "sound-healing",
    label: "Sound Healing",
    category: "tech",
    weight: 3,
    desc: "Within the narrative, specific frequencies (432 Hz, 528 Hz 'DNA repair,' solfeggio frequencies, binaural beats) can heal the body, repair DNA, decalcify the pineal gland, and raise consciousness — based on cymatics (visible frequency structuring matter). Said to be a real, suppressed technology (Rife machines are the medical application), and one of the most accessible civilian ascension tools.",
    links: ["rife-machine", "432hz", "cymatics", "vibration-frequency", "holistic-healing"],
  },
  {
    id: "holistic-healing",
    label: "Holistic Healing",
    category: "healing",
    weight: 4,
    desc: "Within the narrative, the cabal's allopathic medical system (Rockefeller medicine, big pharma, the AMA) is described as a deliberate depopulation and profit-extraction machine — curing symptoms while suppressing the real causes (toxins, low vibration, pineal calcification) and the real cures (Rife, ozone, cannabis, Gerson, laetrile, frequency healing). Holistic healing — using diet, herbs, frequency, energy work, and detox — is presented as the path back to real health.",
    links: ["rife-machine", "cancer-cured", "decalcify", "activator-x", "orgone", "weaponized-food"],
  },
  {
    id: "cancer-cured",
    label: "Cancer Cures (Suppressed)",
    category: "healing",
    weight: 4,
    desc: "Within the narrative, multiple working cancer cures have been suppressed by the medical establishment: Rife's frequency therapy, Rene Caisse's Essiac tea, Harry Hoxsey's herbal formula, the Gerson therapy, laetrile (B17), antineoplastons (Burzynski), DCA, and high-dose vitamin C. The Rockefellers and the AMA are described as having orchestrated the suppression to protect the chemotherapy/radiation profit machine and the depopulation agenda. Said to be one of the most provable suppression cases, post-Event.",
    links: ["rife-machine", "holistic-healing", "engineered-diseases", "weaponized-food"],
  },
  {
    id: "weaponized-food",
    label: "Weaponized Food",
    category: "healing",
    weight: 3,
    desc: "Within the narrative, the modern food supply is deliberately weaponized: GMOs (Monsanto), glyphosate, high-fructose corn syrup, aspartame, MSG, processed seed oils, fluoridated water, and chemtrail-aluminum-contaminated organic produce — all designed to calcify the pineal gland, lower vibration, cause chronic disease, and shorten lifespan. 'Organic / non-GMO' is treated as a baseline necessity, not a preference. Linked to the depopulation agenda.",
    links: ["decalcify", "holistic-healing", "engineered-diseases", "kill-your-tv", "hfcs"],
  },
  {
    id: "hfcs",
    label: "High Fructose Corn Syrup",
    category: "healing",
    weight: 2,
    desc: "Within the narrative, HFCS is described as a deliberately engineered metabolic poison — promoted into the U.S. food supply via corn subsidies (the cabal's farm policy) to drive obesity, diabetes, fatty liver, and cognitive decline. Said to be one of the most direct 'soft-kill' weapons in the food supply. Linked to the depopulation agenda and to keeping the population docile and dependent on the medical system.",
    links: ["weaponized-food", "engineered-diseases", "decalcify", "holistic-healing"],
  },
  {
    id: "engineered-diseases",
    label: "Engineered Diseases",
    category: "healing",
    weight: 3,
    desc: "Within the narrative, major disease outbreaks (1918 flu, HIV/AIDS, SARS, H1N1, Ebola, COVID-19) are described as engineered bioweapons released by the cabal — for depopulation, profit (vaccine sales), fear-based control, and the rollout of medical-martial-law infrastructure. Said to be developed at Fort Detrick, Porton Down, the CDC, and Wuhan. The 'pandemic' framing is treated as cover for the cabal's agenda.",
    links: ["cancer-cured", "weaponized-food", "deep-state", "cabal", "rods-of-god"],
  },
  {
    id: "chemtrails",
    label: "Chemtrails (Geoengineering)",
    category: "tech",
    weight: 3,
    desc: "Within the narrative, the persistent white trails left by high-altitude aircraft are not contrails but 'chemtrails' — deliberate aerosol spraying of aluminum, barium, strontium, and (in variants) graphene and nanobots, for purposes including weather manipulation (geoengineering), pineal calcification, HAARP-compatible atmospheric conductivity, depopulation, and (in the most extreme variants) mind control. Linked to the Agenda 21 / climate-engineering programs.",
    sources: [
      { label: "Chemtrail conspiracy theory — Wikipedia", url: "https://en.wikipedia.org/wiki/Chemtrail_conspiracy_theory" },
    ],
    links: ["weaponized-food", "decalcify", "orgone", "engineered-diseases", "global-warming-planets"],
  },
  {
    id: "haarp",
    label: "HAARP (Weather/Earthquake Weapon)",
    category: "tech",
    weight: 3,
    desc: "The real High-frequency Active Auroral Research Program (HAARP) in Alaska — an ionospheric heater. Within the narrative, HAARP is described as a weapon capable of weather manipulation, earthquake triggering (via the Earth grid), mind control (via frequency broadcasts in the 6–11 Hz range), and the projection of holograms (Blue Beam). Major earthquakes and hurricanes since the 1990s are cited as HAARP operations. Linked to EISCAT and the Norway Spiral.",
    sources: [
      { label: "HAARP — Wikipedia", url: "https://en.wikipedia.org/wiki/High-frequency_Active_Auroral_Research_Program" },
    ],
    links: ["norway-spiral", "blue-beam", "chemtrails", "deep-state"],
  },
  {
    id: "blue-beam",
    label: "Project Blue Beam (Fake Alien Invasion)",
    category: "tech",
    weight: 4,
    desc: "Serge Monast's 1994 claim that NASA and the UN were planning a fake 'alien invasion' / 'second coming' using holographic projection, voice-to-skull technology, and staged 'ET' attacks — to terrify humanity into accepting a one-world government and a one-world religion. Within the broader narrative, Blue Beam is described as the cabal's planned 'end-game' card, and the genuine positive ET contact (Great Awakening) is described as the real event Blue Beam is designed to pre-empt and discredit.",
    sources: [
      { label: "Project Blue Beam — Wikipedia", url: "https://en.wikipedia.org/wiki/Project_Blue_Beam" },
    ],
    links: ["haarp", "norway-spiral", "great-awakening", "full-disclosure", "deep-state"],
  },
  {
    id: "rods-of-god",
    label: "Rods from God (Kinetic Bombardment)",
    category: "tech",
    weight: 3,
    desc: "A real proposed USAF weapon: telephone-pole-sized tungsten rods dropped from orbit, reaching the impact speed of a tactical nuke without the radiation. Within the narrative, 'Rods of God' have been operational for decades and are used selectively by the Earth Alliance against DUMBs (Deep Underground Military Bases) — e.g., the 2019 'earthquake' off Alaska that destroyed a cabal DUMB. Cited as part of the SSP / Space Force arsenal.",
    sources: [
      { label: "Kinetic bombardment — Wikipedia", url: "https://en.wikipedia.org/wiki/Kinetic_bombardment" },
    ],
    links: ["star-wars-sdi", "space-force", "earth-alliance", "secret-space-program"],
  },
  {
    id: "star-wars-sdi",
    label: "Star Wars / SDI (Reagan, 1983)",
    category: "tech",
    weight: 3,
    desc: "Reagan's real 1983 Strategic Defense Initiative — space-based missile defense. Within the narrative, SDI was the public cover for the SSP's weaponization of space — the actual program included directed-energy weapons, kinetic bombardment (Rods from God), and antigravity interceptors. Reagan himself is described as having been briefed on ET presence (per his 1985 Camp David meeting with Gorbachev and his UN 'alien threat' speech) and as a white-hat ally.",
    sources: [
      { label: "Strategic Defense Initiative — Wikipedia", url: "https://en.wikipedia.org/wiki/Strategic_Defense_Initiative" },
    ],
    links: ["rods-of-god", "space-force", "secret-space-program", "dew-weapons"],
  },
  {
    id: "dew-weapons",
    label: "Directed Energy Weapons (DEW)",
    category: "tech",
    weight: 3,
    desc: "Within the narrative, directed-energy weapons (lasers, microwaves, scalar weapons) have been operational for decades and used by both the cabal and the Earth Alliance. The 2018 California 'wildfires' (Paradise, Santa Rosa), the 2023 Maui fires, and 9/11 are described by various community factions as DEW attacks. Cited as part of the SSP / MICSSP arsenal and as the technology behind the 'Rods from God' and HAARP.",
    links: ["star-wars-sdi", "haarp", "rods-of-god", "wtc7", "deep-state"],
  },
  {
    id: "nasa-dark-mission",
    label: "NASA: Dark Mission (Hoagland/Bara)",
    category: "tech",
    weight: 3,
    desc: "The 2007 book by Richard C. Hoagland and Mike Bara alleging that NASA is a front for a classified space program, that it deliberately airbrushes UFOs and ruins out of public imagery, that its mission patches and press releases contain 'hidden in plain sight' occult symbolism, and that its true mission has always been the suppression of the truth about ancient ET ruins across the solar system.",
    sources: [
      { label: "Richard C. Hoagland bibliography", url: "https://en.wikipedia.org/wiki/Richard_C._Hoagland" },
    ],
    links: ["richard-hoagland", "nasa-coverup", "stanley-kubrick", "face-on-mars"],
  },
  {
    id: "nasa-coverup",
    label: "NASA Cover-ups / Photo Manipulation",
    category: "tech",
    weight: 4,
    desc: "Within the narrative, NASA is described as a civilian-front agency whose real purpose is to suppress evidence of ET ruins and activity across the solar system — via airbrushing photos (the 'Brookings Report' is cited as the 1960 policy basis), color-shifting Mars imagery, faking the Apollo footage (Kubrick), and blurring Google Moon/Mars imagery. Whistleblowers (Karl Wolf, Donna Hare, Gary McKinnon) are cited as primary sources.",
    sources: [
      { label: "Brookings Report — Wikipedia", url: "https://en.wikipedia.org/wiki/Brookings_Report" },
    ],
    links: ["nasa-dark-mission", "richard-hoagland", "stanley-kubrick", "apollo-coverup", "face-on-mars"],
  },
  {
    id: "stanley-kubrick",
    label: "Stanley Kubrick (Faked Apollo)",
    category: "tech",
    weight: 3,
    desc: "Within the narrative, Stanley Kubrick was hired by NASA to fake the Apollo moon landing footage (in a studio, using his '2001: A Space Odyssey' techniques) because the real Apollo missions encountered ETs and ruins NASA couldn't show the public. 'The Shining' is read as Kubrick's coded confession (Room 237 = the Apollo 237,000-mile distance; the twins = the Gemini program; Jack's typewriter = the typewriter used in the studio). 'Eyes Wide Shut' is read as his exposure of the cabal's rituals, leading to his death before release.",
    sources: [
      { label: "Moon landing conspiracy theories — Wikipedia", url: "https://en.wikipedia.org/wiki/Moon_landing_conspiracy_theories" },
    ],
    links: ["apollo-coverup", "nasa-coverup", "deep-state", "moon"],
  },
];
