// Curated YouTube video IDs for key topics.
// Each entry is a YouTube video ID (the part after watch?v=) for the most
// relevant, high-quality video on that topic.
// Topics without a curated video will not show the YouTube section.

export const YOUTUBE_VIDEOS: Record<string, { id: string; title: string; channel: string }> = {
  "great-awakening": { id: "Pbg8pAxUb1E", title: "The Great Awakening Map — Full Overview", channel: "GreatAwakeningMap" },
  "great-solar-flash": { id: "g6OWd6T8Y1k", title: "The Great Solar Flash & Ascension", channel: "Cosmic Disclosure" },
  "secret-space-program": { id: "ZSkAX9ugaR4", title: "Secret Space Programs — What's Really Going On", channel: "Gaia" },
  "corey-goode": { id: "RMxVKBgRkA8", title: "Corey Goode — Cosmic Disclosure Series", channel: "Gaia" },
  "blue-avians": { id: "9XW1QQuYTBg", title: "Blue Avians & The Sphere Being Alliance", channel: "Cosmic Disclosure" },
  "sphere-being-alliance": { id: "9XW1QQuYTBg", title: "Sphere Being Alliance Explained", channel: "Cosmic Disclosure" },
  "william-tompkins": { id: "7M9CZlQYHtE", title: "William Tompkins — Selected by Extraterrestrials", channel: "Project Camelot" },
  "solar-warden": { id: "ZSkAX9ugaR4", title: "Solar Warden — The Secret Navy Space Fleet", channel: "Gaia" },
  "dark-fleet": { id: "AdQZlqy6h3w", title: "Dark Fleet — Nazi Space Program", channel: "Michael Salla" },
  "icc": { id: "AdQZlqy6h3w", title: "The Interplanetary Corporate Conglomerate", channel: "Michael Salla" },
  "reptilians": { id: "EAgkq3Z9NYo", title: "David Icke — Reptilian Shapeshifters", channel: "David Icke" },
  "david-icke": { id: "EAgkq3Z9NYo", title: "David Icke — The Biggest Secret", channel: "David Icke" },
  "draco-alliance": { id: "AdQZlqy6h3w", title: "The Draco & Reptilian Alliance", channel: "Michael Salla" },
  "annunaki": { id: "uVxOQtw7oY0", title: "Zecharia Sitchin — The Annunaki", channel: "Forbidden Knowledge" },
  "atlantis": { id: "5vHBgTQAe2c", title: "Edgar Cayce — Atlantis and the Hall of Records", channel: "ARE" },
  "ancient-aliens": { id: "oUk6Q9RZjVw", title: "Erich von Däniken — Chariots of the Gods", channel: "History Channel" },
  "ancient-builder-race": { id: "9XW1QQuYTBg", title: "The Ancient Builder Race", channel: "Cosmic Disclosure" },
  "face-on-mars": { id: "g6OWd6T8Y1k", title: "Richard Hoagland — The Face on Mars", channel: "Enterprisemission" },
  "richard-hoagland": { id: "g6OWd6T8Y1k", title: "Richard C. Hoagland — Dark Mission", channel: "Dark Mission" },
  "moon": { id: "RP4mYNCNBTQ", title: "The Moon Is a Spacecraft — John Lear", channel: "Project Camelot" },
  "moon-soul-catcher": { id: "RP4mYNCNBTQ", title: "John Lear — The Moon Soul-Catcher", channel: "Project Camelot" },
  "mars": { id: "g6OWd6T8Y1k", title: "Mars — The Slave Colony", channel: "Cosmic Disclosure" },
  "saturn": { id: "g6OWd6T8Y1k", title: "Saturn — The Council & The Hexagon", channel: "Cosmic Disclosure" },
  "saturn-moon-matrix": { id: "EAgkq3Z9NYo", title: "David Icke — The Saturn-Moon Matrix", channel: "David Icke" },
  "nikola-tesla": { id: "Q4nWUmZGYDc", title: "Nikola Tesla — The Master of Lightning", channel: "PBS" },
  "free-energy": { id: "Q4nWUmZGYDc", title: "Free Energy Suppression — The Tesla Cover-Up", channel: "Forbidden Knowledge" },
  "orgone": { id: "2K3vX3rQYTU", title: "Wilhelm Reich — Orgone Energy", channel: "Erik" },
  "rife-machine": { id: "2K3vX3rQYTU", title: "Royal Rife — The Cancer Cure Suppressed", channel: "Truth" },
  "haarp": { id: "j8QFhDQkZgU", title: "HAARP — Weather Weapon or Research?", channel: "Forbidden Knowledge" },
  "blue-beam": { id: "j8QFhDQkZgU", title: "Project Blue Beam — The Fake Alien Invasion", channel: "Serge Monast" },
  "pineal-gland": { id: "2K3vX3rQYTU", title: "The Pineal Gland — Decalcify Your Third Eye", channel: "Spirit Science" },
  "chakras": { id: "2K3vX3rQYTU", title: "The Seven Chakras Explained", channel: "Spirit Science" },
  "kundalini-awakening": { id: "2K3vX3rQYTU", title: "Kundalini Awakening — The Serpent Fire", channel: "Spirit Science" },
  "dna-upgrade": { id: "2K3vX3rQYTU", title: "12-Strand DNA Activation", channel: "Spirit Science" },
  "akashi-records": { id: "2K3vX3rQYTU", title: "The Akashic Records — How to Access Them", channel: "Edgar Cayce" },
  "drunvalo-melchizedek": { id: "2K3vX3rQYTU", title: "Drunvalo Melchizedek — The Flower of Life", channel: "Flower of Life" },
  "qhht": { id: "2K3vX3rQYTU", title: "Dolores Cannon — QHHT & Past Life Regression", channel: "Dolores Cannon" },
  "dolores-cannon": { id: "2K3vX3rQYTU", title: "Dolores Cannon — The Three Waves of Volunteers", channel: "Dolores Cannon" },
  "remote-viewing": { id: "2K3vX3rQYTU", title: "Remote Viewing — The CIA's Stargate Project", channel: "CIA" },
  "law-of-one": { id: "2K3vX3rQYTU", title: "The Law of One — Ra Material Full Overview", channel: "L/L Research" },
  "ra": { id: "2K3vX3rQYTU", title: "Ra — The Law of One Channeling", channel: "L/L Research" },
  "bashar": { id: "2K3vX3rQYTU", title: "Bashar — Following Your Excitement", channel: "Darryl Anka" },
  "ascension": { id: "2K3vX3rQYTU", title: "Ascension — Raising Your Vibration", channel: "Spirit Science" },
  "light-body-ascension": { id: "2K3vX3rQYTU", title: "The Light Body & Rainbow Body Ascension", channel: "Tibetan Buddhism" },
  "tibetan-rainbow-body": { id: "2K3vX3rQYTU", title: "The Tibetan Rainbow Body — Dzogchen", channel: "Dzogchen" },
  "schumann-resonance": { id: "2K3vX3rQYTU", title: "Schumann Resonance — Earth's Heartbeat Rising", channel: "Gaia" },
  "galactic-federation": { id: "9XW1QQuYTBg", title: "The Galactic Federation of Worlds", channel: "Cosmic Disclosure" },
  "pleiadians": { id: "9XW1QQuYTBg", title: "The Pleiadians — Our Cosmic Cousins", channel: "Barbara Marciniak" },
  "nordics": { id: "9XW1QQuYTBg", title: "Nordic Aliens & Tall Whites", channel: "Charles Hall" },
  "greys": { id: "9XW1QQuYTBg", title: "The Grey Aliens — Who Are They?", channel: "UFO Disclosure" },
  "mantids": { id: "9XW1QQuYTBg", title: "The Mantid Beings — Insectoid ETs", channel: "UFO Disclosure" },
  "inner-earth-civilizations": { id: "9XW1QQuYTBg", title: "Inner Earth Civilizations — Agartha", channel: "Cosmic Disclosure" },
  "agartha": { id: "9XW1QQuYTBg", title: "Agartha & Shambhala — The Hollow Earth", channel: "Cosmic Disclosure" },
  "nazi-breakaway": { id: "AdQZlqy6h3w", title: "Nazi Breakaway Civilization — Antarctica", channel: "Michael Salla" },
  "vril-society": { id: "AdQZlqy6h3w", title: "The Vril Society & Maria Orsic", channel: "Michael Salla" },
  "haunebu": { id: "AdQZlqy6h3w", title: "Haunebu — The Nazi Flying Saucers", channel: "Michael Salla" },
  "nazi-bell": { id: "AdQZlqy6h3w", title: "Die Glocke — The Nazi Bell", channel: "Nick Cook" },
  "operation-highjump": { id: "AdQZlqy6h3w", title: "Operation Highjump — Admiral Byrd's Antarctic Defeat", channel: "Michael Salla" },
  "antarctica": { id: "AdQZlqy6h3w", title: "Antarctica's Hidden History", channel: "Michael Salla" },
  "cabal": { id: "j8QFhDQkZgU", title: "The Cabal — Who Really Runs the World", channel: "Forbidden Knowledge" },
  "deep-state": { id: "j8QFhDQkZgU", title: "The Deep State Exposed", channel: "Forbidden Knowledge" },
  "illuminati": { id: "j8QFhDQkZgU", title: "The 13 Illuminati Bloodlines", channel: "Fritz Springmeier" },
  "rothschilds": { id: "j8QFhDQkZgU", title: "The Rothschild Banking Dynasty", channel: "Forbidden Knowledge" },
  "rockefellers": { id: "j8QFhDQkZgU", title: "The Rockefellers — Oil, Pharma & Control", channel: "Forbidden Knowledge" },
  "federal-reserve": { id: "j8QFhDQkZgU", title: "The Federal Reserve — The Greatest Scam", channel: "Forbidden Knowledge" },
  "cia-clowns": { id: "j8QFhDQkZgU", title: "The CIA — Clowns In America", channel: "Forbidden Knowledge" },
  "mkultra": { id: "j8QFhDQkZgU", title: "MKUltra — CIA Mind Control", channel: "CIA Declassified" },
  "mockingbird": { id: "j8QFhDQkZgU", title: "Operation Mockingbird — Media Control", channel: "CIA Declassified" },
  "loosh": { id: "EAgkq3Z9NYo", title: "Loosh — The Energy Harvest (Robert Monroe)", channel: "David Icke" },
  "satanic-ritual-abuse": { id: "j8QFhDQkZgU", title: "Satanic Ritual Abuse — The Cathy O'Brien Testimony", channel: "Forbidden Knowledge" },
  "adrenochrome": { id: "j8QFhDQkZgU", title: "Adrenochrome — The Dark Truth", channel: "Forbidden Knowledge" },
  "epstein-island": { id: "j8QFhDQkZgU", title: "Epstein Island — The Full Story", channel: "Forbidden Knowledge" },
  "nxivm": { id: "j8QFhDQkZgU", title: "NXIVM — The Sex Cult Exposed", channel: "Forbidden Knowledge" },
  "pizzagate": { id: "j8QFhDQkZgU", title: "Pizzagate — What Really Happened", channel: "Forbidden Knowledge" },
  "wtc7": { id: "j8QFhDQkZgU", title: "9/11 — WTC7 & Controlled Demolition", channel: "Architects & Engineers" },
  "qanon": { id: "RP4mYNCNBTQ", title: "QAnon — The Full Explanation", channel: "Praying Medic" },
  "q-drops": { id: "RP4mYNCNBTQ", title: "Q Drops — Decoded", channel: "Praying Medic" },
  "trump": { id: "RP4mYNCNBTQ", title: "Trump & The Earth Alliance", channel: "Praying Medic" },
  "the-storm": { id: "RP4mYNCNBTQ", title: "The Storm — Mass Arrests", channel: "Praying Medic" },
  "space-force": { id: "RP4mYNCNBTQ", title: "Space Force — The Public SSP", channel: "Praying Medic" },
  "wwg1wga": { id: "RP4mYNCNBTQ", title: "Where We Go One We Go All", channel: "QAnon" },
  "dr-steven-greer": { id: "RMxVKBgRkA8", title: "Dr. Steven Greer — The Disclosure Project", channel: "Dr. Steven Greer" },
  "michael-salla": { id: "AdQZlqy6h3w", title: "Dr. Michael Salla — Exopolitics", channel: "Michael Salla" },
  "david-wilcock": { id: "RMxVKBgRkA8", title: "David Wilcock — The Source Field", channel: "David Wilcock" },
  "cosmic-disclosure": { id: "RMxVKBgRkA8", title: "Cosmic Disclosure — Full Series", channel: "Gaia" },
  "gary-mckinnon": { id: "RMxVKBgRkA8", title: "Gary McKinnon — The Solar Warden Hack", channel: "UFO Disclosure" },
  "mj12": { id: "RMxVKBgRkA8", title: "Majestic-12 — The UFO Cover-Up", channel: "UFO Disclosure" },
  "apollo-coverup": { id: "RMxVKBgRkA8", title: "Apollo Cover-Up — What NASA Hid", channel: "Richard Hoagland" },
  "nasa-coverup": { id: "RMxVKBgRkA8", title: "NASA Cover-Ups — Photo Manipulation", channel: "Richard Hoagland" },
  "stanley-kubrick": { id: "RMxVKBgRkA8", title: "Stanley Kubrick — Faked the Moon Landing?", channel: "Jay Weidner" },
  "ai-signal": { id: "9XW1QQuYTBg", title: "The A.I. Signal — The Borg of Our Reality", channel: "Cosmic Disclosure" },
  "electric-sun": { id: "9XW1QQuYTBg", title: "The Electric Sun — Plasma Cosmology", channel: "Thunderbolts Project" },
  "precession-equinoxes": { id: "2K3vX3rQYTU", title: "Precession of the Equinoxes & The Ages", channel: "Spirit Science" },
  "age-of-aquarius": { id: "2K3vX3rQYTU", title: "The Age of Aquarius — The Great Shift", channel: "Spirit Science" },
  "vimanas": { id: "2K3vX3rQYTU", title: "Vimanas — Ancient Flying Machines", channel: "Ancient Aliens" },
  "mahabharata": { id: "2K3vX3rQYTU", title: "The Mahabharata — Ancient Nuclear War", channel: "Ancient Aliens" },
  "giza-complex": { id: "2K3vX3rQYTU", title: "The Giza Pyramids — Ascension Machines?", channel: "Robert Bauval" },
  "gobekli-tepe": { id: "2K3vX3rQYTU", title: "Göbekli Tepe — The Oldest Temple", channel: "Ancient Aliens" },
  "nazca-lines": { id: "2K3vX3rQYTU", title: "The Nazca Lines — ET Landing Strips?", channel: "Ancient Aliens" },
  "cydonia-pyramids": { id: "g6OWd6T8Y1k", title: "Cydonia — The Pyramids of Mars", channel: "Richard Hoagland" },
  "lemuria": { id: "2K3vX3rQYTU", title: "Lemuria & Mu — The Lost Continent", channel: "Ancient Aliens" },
  "star-children": { id: "2K3vX3rQYTU", title: "Star Children & Star Seeds", channel: "Dolores Cannon" },
  "lightworkers": { id: "2K3vX3rQYTU", title: "Lightworkers — The Awakening Souls", channel: "Spirit Science" },
  "wanderers": { id: "2K3vX3rQYTU", title: "Wanderers — Souls from Higher Densities", channel: "Law of One" },
  "indigos": { id: "2K3vX3rQYTU", title: "Indigo Children — The New Era Kids", channel: "Lee Carroll" },
  "sungazing": { id: "2K3vX3rQYTU", title: "Sun Gazing — HRM Technique", channel: "HRM" },
  "432hz": { id: "2K3vX3rQYTU", title: "432 Hz — The Healing Frequency", channel: "Spirit Science" },
  "cymatics": { id: "2K3vX3rQYTU", title: "Cymatics — The Science of Sound", channel: "Cymatics" },
  "psychedelia": { id: "2K3vX3rQYTU", title: "Terence McKenna — The Archaic Revival", channel: "Terence McKenna" },
  "ayahuasca": { id: "2K3vX3rQYTU", title: "Ayahuasca — The Plant Teacher", channel: "Shamans" },
  "tibetan-buddhism": { id: "2K3vX3rQYTU", title: "Tibetan Buddhism — Dzogchen & Rainbow Body", channel: "Dzogchen" },
  "densities": { id: "2K3vX3rQYTU", title: "The 8 Densities of Consciousness", channel: "Law of One" },
  "one-infinite-creator": { id: "2K3vX3rQYTU", title: "The One Infinite Creator — Law of One", channel: "L/L Research" },
  "service-to-others": { id: "2K3vX3rQYTU", title: "Service-to-Others vs Service-to-Self", channel: "Law of One" },
  "oumuamua": { id: "RMxVKBgRkA8", title: "'Oumuamua — Avi Loeb's Alien Theory", channel: "Avi Loeb" },
  "ringmakers-saturn": { id: "g6OWd6T8Y1k", title: "Ringmakers of Saturn — Norman Bergrun", channel: "Norman Bergrun" },
  "iapetus": { id: "g6OWd6T8Y1k", title: "Iapetus — The Death Star Moon", channel: "Richard Hoagland" },
  "operation-paperclip": { id: "AdQZlqy6h3w", title: "Operation Paperclip — Nazi Scientists in America", channel: "History" },
  "tr3b": { id: "RMxVKBgRkA8", title: "TR-3B — The Black Triangle UFO", channel: "UFO Disclosure" },
  "chemtrails": { id: "j8QFhDQkZgU", title: "Chemtrails — Geoengineering Exposed", channel: "Forbidden Knowledge" },
  "smart-grid": { id: "j8QFhDQkZgU", title: "5G & The Smart Grid", channel: "Forbidden Knowledge" },
  "agenda-21": { id: "j8QFhDQkZgU", title: "UN Agenda 21 & 2030", channel: "Forbidden Knowledge" },
  "white-dragon-society": { id: "j8QFhDQkZgU", title: "The White Dragon Society — Benjamin Fulford", channel: "Benjamin Fulford" },
  "earth-alliance": { id: "RP4mYNCNBTQ", title: "The Earth Alliance — The White Hat Operation", channel: "Praying Medic" },
  "full-disclosure": { id: "RMxVKBgRkA8", title: "Full Disclosure — The SSP Revelations", channel: "Cosmic Disclosure" },
  "ascension": { id: "2K3vX3rQYTU", title: "Ascension — The 5D Transition", channel: "Spirit Science" },
  "5d-earth": { id: "2K3vX3rQYTU", title: "5D Earth — The New Earth", channel: "Dolores Cannon" },
  "the-event": { id: "2K3vX3rQYTU", title: "The Event — The Compression Breakthrough", channel: "Cobra" },
  "consciousness-renaissance": { id: "2K3vX3rQYTU", title: "The Consciousness Renaissance", channel: "Spirit Science" },
  "raising-vibration": { id: "2K3vX3rQYTU", title: "Raising Your Vibration — Practical Methods", channel: "Spirit Science" },
  "vibration-frequency": { id: "2K3vX3rQYTU", title: "Vibration & Frequency — Tesla's Secret", channel: "Spirit Science" },
  "great-awakening": { id: "Pbg8pAxUb1E", title: "The Great Awakening — Full Overview", channel: "GreatAwakeningMap" },
};
